/* DROP FEATURE TABLES (4) */

DROP TABLE PLACE CASCADE CONSTRAINTS;

DROP INDEX COUNTRY1_SPIDX;
DROP TABLE COUNTRY CASCADE CONSTRAINTS;
DELETE FROM USER_SDO_GEOM_METADATA WHERE TABLE_NAME='COUNTRY';

DROP TABLE BOOK CASCADE CONSTRAINTS;

DROP TABLE PHILOSOPHER CASCADE CONSTRAINTS;


/* DROP JOIN TABLES (2) */

DROP INDEX IS_FRIEND0_PHILOSOPHER1_ID_IDX;
DROP INDEX IS_FRIEND1_PHILOSOPHER2_ID_IDX;
DROP TABLE IS_FRIEND_OF CASCADE CONSTRAINTS;

DROP INDEX IS_AUTHOR_2_PHILOSOPHER_ID_IDX;
DROP INDEX IS_AUTHOR_OF_BOOK_ID_IDX;
DROP TABLE IS_AUTHOR_OF CASCADE CONSTRAINTS;


/* DROP PROPERTY TABLES (1) */

DROP TABLE SUBJECT CASCADE CONSTRAINTS;


/* DROP SEQUENCES (1) */

DROP SEQUENCE FID_seq;
