//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.02.19 at 03:44:31 PM MEZ 
//


package org.deegree.services.controller.wcs.configuration;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.deegree.services.controller.wcs.configuration package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Version_QNAME = new QName("http://www.deegree.org/services/wcs", "Version");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.deegree.services.controller.wcs.configuration
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PublishedInformation.AllowedOperations.GetCoverage }
     * 
     */
    public PublishedInformation.AllowedOperations.GetCoverage createPublishedInformationAllowedOperationsGetCoverage() {
        return new PublishedInformation.AllowedOperations.GetCoverage();
    }

    /**
     * Create an instance of {@link PublishedInformation }
     * 
     */
    public PublishedInformation createPublishedInformation() {
        return new PublishedInformation();
    }

    /**
     * Create an instance of {@link PublishedInformation.SupportedVersions }
     * 
     */
    public PublishedInformation.SupportedVersions createPublishedInformationSupportedVersions() {
        return new PublishedInformation.SupportedVersions();
    }

    /**
     * Create an instance of {@link PublishedInformation.AllowedOperations }
     * 
     */
    public PublishedInformation.AllowedOperations createPublishedInformationAllowedOperations() {
        return new PublishedInformation.AllowedOperations();
    }

    /**
     * Create an instance of {@link PublishedInformation.AllowedOperations.DescribeCoverage }
     * 
     */
    public PublishedInformation.AllowedOperations.DescribeCoverage createPublishedInformationAllowedOperationsDescribeCoverage() {
        return new PublishedInformation.AllowedOperations.DescribeCoverage();
    }

    /**
     * Create an instance of {@link PublishedInformation.AllowedOperations.GetCapabilities }
     * 
     */
    public PublishedInformation.AllowedOperations.GetCapabilities createPublishedInformationAllowedOperationsGetCapabilities() {
        return new PublishedInformation.AllowedOperations.GetCapabilities();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.deegree.org/services/wcs", name = "Version")
    public JAXBElement<String> createVersion(String value) {
        return new JAXBElement<String>(_Version_QNAME, String.class, null, value);
    }

}
