//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.02.19 at 03:44:31 PM MEZ 
//


package org.deegree.services.controller.wcs.configuration;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import org.deegree.services.jaxb.metadata.ServiceIdentificationType;
import org.deegree.services.jaxb.metadata.ServiceProviderType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.deegree.org/webservices}ServiceIdentification" minOccurs="0"/>
 *         &lt;element ref="{http://www.deegree.org/webservices}ServiceProvider" minOccurs="0"/>
 *         &lt;element name="SupportedVersions">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{http://www.deegree.org/services/wcs}Version" maxOccurs="2"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="AllowedOperations" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;group ref="{http://www.deegree.org/services/wcs}AllowedOperations"/>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "serviceIdentification",
    "serviceProvider",
    "supportedVersions",
    "allowedOperations"
})
@XmlRootElement(name = "PublishedInformation")
public class PublishedInformation {

    @XmlElement(name = "ServiceIdentification", namespace = "http://www.deegree.org/webservices")
    protected ServiceIdentificationType serviceIdentification;
    @XmlElement(name = "ServiceProvider", namespace = "http://www.deegree.org/webservices")
    protected ServiceProviderType serviceProvider;
    @XmlElement(name = "SupportedVersions", required = true)
    protected PublishedInformation.SupportedVersions supportedVersions;
    @XmlElement(name = "AllowedOperations")
    protected PublishedInformation.AllowedOperations allowedOperations;

    /**
     * Gets the value of the serviceIdentification property.
     * 
     * @return
     *     possible object is
     *     {@link ServiceIdentificationType }
     *     
     */
    public ServiceIdentificationType getServiceIdentification() {
        return serviceIdentification;
    }

    /**
     * Sets the value of the serviceIdentification property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServiceIdentificationType }
     *     
     */
    public void setServiceIdentification(ServiceIdentificationType value) {
        this.serviceIdentification = value;
    }

    /**
     * Gets the value of the serviceProvider property.
     * 
     * @return
     *     possible object is
     *     {@link ServiceProviderType }
     *     
     */
    public ServiceProviderType getServiceProvider() {
        return serviceProvider;
    }

    /**
     * Sets the value of the serviceProvider property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServiceProviderType }
     *     
     */
    public void setServiceProvider(ServiceProviderType value) {
        this.serviceProvider = value;
    }

    /**
     * Gets the value of the supportedVersions property.
     * 
     * @return
     *     possible object is
     *     {@link PublishedInformation.SupportedVersions }
     *     
     */
    public PublishedInformation.SupportedVersions getSupportedVersions() {
        return supportedVersions;
    }

    /**
     * Sets the value of the supportedVersions property.
     * 
     * @param value
     *     allowed object is
     *     {@link PublishedInformation.SupportedVersions }
     *     
     */
    public void setSupportedVersions(PublishedInformation.SupportedVersions value) {
        this.supportedVersions = value;
    }

    /**
     * Gets the value of the allowedOperations property.
     * 
     * @return
     *     possible object is
     *     {@link PublishedInformation.AllowedOperations }
     *     
     */
    public PublishedInformation.AllowedOperations getAllowedOperations() {
        return allowedOperations;
    }

    /**
     * Sets the value of the allowedOperations property.
     * 
     * @param value
     *     allowed object is
     *     {@link PublishedInformation.AllowedOperations }
     *     
     */
    public void setAllowedOperations(PublishedInformation.AllowedOperations value) {
        this.allowedOperations = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;group ref="{http://www.deegree.org/services/wcs}AllowedOperations"/>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "getCapabilities",
        "describeCoverage",
        "getCoverage"
    })
    public static class AllowedOperations {

        @XmlElement(name = "GetCapabilities", required = true)
        protected PublishedInformation.AllowedOperations.GetCapabilities getCapabilities;
        @XmlElement(name = "DescribeCoverage", required = true)
        protected PublishedInformation.AllowedOperations.DescribeCoverage describeCoverage;
        @XmlElement(name = "GetCoverage", required = true)
        protected PublishedInformation.AllowedOperations.GetCoverage getCoverage;

        /**
         * Gets the value of the getCapabilities property.
         * 
         * @return
         *     possible object is
         *     {@link PublishedInformation.AllowedOperations.GetCapabilities }
         *     
         */
        public PublishedInformation.AllowedOperations.GetCapabilities getGetCapabilities() {
            return getCapabilities;
        }

        /**
         * Sets the value of the getCapabilities property.
         * 
         * @param value
         *     allowed object is
         *     {@link PublishedInformation.AllowedOperations.GetCapabilities }
         *     
         */
        public void setGetCapabilities(PublishedInformation.AllowedOperations.GetCapabilities value) {
            this.getCapabilities = value;
        }

        /**
         * Gets the value of the describeCoverage property.
         * 
         * @return
         *     possible object is
         *     {@link PublishedInformation.AllowedOperations.DescribeCoverage }
         *     
         */
        public PublishedInformation.AllowedOperations.DescribeCoverage getDescribeCoverage() {
            return describeCoverage;
        }

        /**
         * Sets the value of the describeCoverage property.
         * 
         * @param value
         *     allowed object is
         *     {@link PublishedInformation.AllowedOperations.DescribeCoverage }
         *     
         */
        public void setDescribeCoverage(PublishedInformation.AllowedOperations.DescribeCoverage value) {
            this.describeCoverage = value;
        }

        /**
         * Gets the value of the getCoverage property.
         * 
         * @return
         *     possible object is
         *     {@link PublishedInformation.AllowedOperations.GetCoverage }
         *     
         */
        public PublishedInformation.AllowedOperations.GetCoverage getGetCoverage() {
            return getCoverage;
        }

        /**
         * Sets the value of the getCoverage property.
         * 
         * @param value
         *     allowed object is
         *     {@link PublishedInformation.AllowedOperations.GetCoverage }
         *     
         */
        public void setGetCoverage(PublishedInformation.AllowedOperations.GetCoverage value) {
            this.getCoverage = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class DescribeCoverage {


        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class GetCapabilities {


        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class GetCoverage {


        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{http://www.deegree.org/services/wcs}Version" maxOccurs="2"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "version"
    })
    public static class SupportedVersions {

        @XmlElement(name = "Version", required = true)
        protected List<String> version;

        /**
         * Gets the value of the version property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the version property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getVersion().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getVersion() {
            if (version == null) {
                version = new ArrayList<String>();
            }
            return this.version;
        }

    }

}
