//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.11.13 at 03:16:35 PM MEZ 
//


package org.deegree.feature.persistence.postgis.jaxbconfig;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Definition of a measure property of a feature type.
 * 
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.deegree.org/feature/featuretype}AbstractPropertyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.deegree.org/feature/featuretype}MeasurePropertyMapping"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "measurePropertyMapping"
})
public class MeasurePropertyDecl
    extends AbstractPropertyDecl
{

    @XmlElement(name = "MeasurePropertyMapping", required = true)
    protected MeasurePropertyMappingType measurePropertyMapping;

    /**
     * Gets the value of the measurePropertyMapping property.
     * 
     * @return
     *     possible object is
     *     {@link MeasurePropertyMappingType }
     *     
     */
    public MeasurePropertyMappingType getMeasurePropertyMapping() {
        return measurePropertyMapping;
    }

    /**
     * Sets the value of the measurePropertyMapping property.
     * 
     * @param value
     *     allowed object is
     *     {@link MeasurePropertyMappingType }
     *     
     */
    public void setMeasurePropertyMapping(MeasurePropertyMappingType value) {
        this.measurePropertyMapping = value;
    }

}
