//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.12.16 at 05:01:18 PM GMT 
//


package org.deegree.portal.cataloguemanager.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element ref="{http://www.isotc211.org/2005/gco}Date"/>
 *         &lt;element ref="{http://www.isotc211.org/2005/gco}DateTime"/>
 *         &lt;element ref="{http://www.isotc211.org/2005/gmd}CI_Date"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "date",
    "dateTime",
    "ciDate"
})
@XmlRootElement(name = "date")
public class Date {

    @XmlElement(name = "Date", namespace = "http://www.isotc211.org/2005/gco")
    protected String date;
    @XmlElement(name = "DateTime", namespace = "http://www.isotc211.org/2005/gco")
    protected String dateTime;
    @XmlElement(name = "CI_Date")
    protected CIDate ciDate;

    /**
     * Gets the value of the date property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDate() {
        return date;
    }

    /**
     * Sets the value of the date property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDate(String value) {
        this.date = value;
    }

    /**
     * Gets the value of the dateTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDateTime() {
        return dateTime;
    }

    /**
     * Sets the value of the dateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDateTime(String value) {
        this.dateTime = value;
    }

    /**
     * Gets the value of the ciDate property.
     * 
     * @return
     *     possible object is
     *     {@link CIDate }
     *     
     */
    public CIDate getCIDate() {
        return ciDate;
    }

    /**
     * Sets the value of the ciDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link CIDate }
     *     
     */
    public void setCIDate(CIDate value) {
        this.ciDate = value;
    }

}
