//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.12.16 at 05:01:18 PM GMT 
//


package org.deegree.portal.cataloguemanager.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element ref="{http://www.isotc211.org/2005/gmd}MD_DataIdentification"/>
 *         &lt;element ref="{http://www.isotc211.org/2005/srv}SV_ServiceIdentification"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "mdDataIdentification",
    "svServiceIdentification"
})
@XmlRootElement(name = "identificationInfo")
public class IdentificationInfo {

    @XmlElement(name = "MD_DataIdentification")
    protected MDDataIdentification mdDataIdentification;
    @XmlElement(name = "SV_ServiceIdentification", namespace = "http://www.isotc211.org/2005/srv")
    protected SVServiceIdentification svServiceIdentification;

    /**
     * Gets the value of the mdDataIdentification property.
     * 
     * @return
     *     possible object is
     *     {@link MDDataIdentification }
     *     
     */
    public MDDataIdentification getMDDataIdentification() {
        return mdDataIdentification;
    }

    /**
     * Sets the value of the mdDataIdentification property.
     * 
     * @param value
     *     allowed object is
     *     {@link MDDataIdentification }
     *     
     */
    public void setMDDataIdentification(MDDataIdentification value) {
        this.mdDataIdentification = value;
    }

    /**
     * Gets the value of the svServiceIdentification property.
     * 
     * @return
     *     possible object is
     *     {@link SVServiceIdentification }
     *     
     */
    public SVServiceIdentification getSVServiceIdentification() {
        return svServiceIdentification;
    }

    /**
     * Sets the value of the svServiceIdentification property.
     * 
     * @param value
     *     allowed object is
     *     {@link SVServiceIdentification }
     *     
     */
    public void setSVServiceIdentification(SVServiceIdentification value) {
        this.svServiceIdentification = value;
    }

}
