//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.12.16 at 05:01:18 PM GMT 
//


package org.deegree.portal.cataloguemanager.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element ref="{http://www.isotc211.org/2005/gmd}MD_Constraints"/>
 *         &lt;element ref="{http://www.isotc211.org/2005/gmd}MD_LegalConstraints"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "mdConstraints",
    "mdLegalConstraints"
})
@XmlRootElement(name = "resourceConstraints")
public class ResourceConstraints {

    @XmlElement(name = "MD_Constraints")
    protected MDConstraints mdConstraints;
    @XmlElement(name = "MD_LegalConstraints")
    protected MDLegalConstraints mdLegalConstraints;

    /**
     * Gets the value of the mdConstraints property.
     * 
     * @return
     *     possible object is
     *     {@link MDConstraints }
     *     
     */
    public MDConstraints getMDConstraints() {
        return mdConstraints;
    }

    /**
     * Sets the value of the mdConstraints property.
     * 
     * @param value
     *     allowed object is
     *     {@link MDConstraints }
     *     
     */
    public void setMDConstraints(MDConstraints value) {
        this.mdConstraints = value;
    }

    /**
     * Gets the value of the mdLegalConstraints property.
     * 
     * @return
     *     possible object is
     *     {@link MDLegalConstraints }
     *     
     */
    public MDLegalConstraints getMDLegalConstraints() {
        return mdLegalConstraints;
    }

    /**
     * Sets the value of the mdLegalConstraints property.
     * 
     * @param value
     *     allowed object is
     *     {@link MDLegalConstraints }
     *     
     */
    public void setMDLegalConstraints(MDLegalConstraints value) {
        this.mdLegalConstraints = value;
    }

}
