//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.12.16 at 05:01:18 PM GMT 
//


package org.deegree.portal.cataloguemanager.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.isotc211.org/2005/gmd}citation"/>
 *         &lt;element ref="{http://www.isotc211.org/2005/gmd}abstract"/>
 *         &lt;element ref="{http://www.isotc211.org/2005/gmd}pointOfContact"/>
 *         &lt;element ref="{http://www.isotc211.org/2005/gmd}descriptiveKeywords" maxOccurs="unbounded"/>
 *         &lt;element ref="{http://www.isotc211.org/2005/gmd}resourceConstraints" maxOccurs="unbounded"/>
 *         &lt;element ref="{http://www.isotc211.org/2005/srv}serviceType"/>
 *         &lt;element ref="{http://www.isotc211.org/2005/srv}serviceTypeVersion"/>
 *         &lt;element ref="{http://www.isotc211.org/2005/srv}accessProperties"/>
 *         &lt;element ref="{http://www.isotc211.org/2005/srv}restrictions"/>
 *         &lt;element name="extent">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{http://www.isotc211.org/2005/gmd}EX_Extent"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element ref="{http://www.isotc211.org/2005/srv}coupledResource" maxOccurs="unbounded"/>
 *         &lt;element ref="{http://www.isotc211.org/2005/srv}couplingType"/>
 *         &lt;element ref="{http://www.isotc211.org/2005/srv}containsOperations" maxOccurs="unbounded"/>
 *         &lt;element ref="{http://www.isotc211.org/2005/srv}operatesOn"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "citation",
    "_abstract",
    "pointOfContact",
    "descriptiveKeywords",
    "resourceConstraints",
    "serviceType",
    "serviceTypeVersion",
    "accessProperties",
    "restrictions",
    "extent",
    "coupledResource",
    "couplingType",
    "containsOperations",
    "operatesOn"
})
@XmlRootElement(name = "SV_ServiceIdentification", namespace = "http://www.isotc211.org/2005/srv")
public class SVServiceIdentification {

    @XmlElement(required = true)
    protected Citation citation;
    @XmlElement(name = "abstract", required = true)
    protected Abstract _abstract;
    @XmlElement(required = true)
    protected PointOfContact pointOfContact;
    @XmlElement(required = true)
    protected List<DescriptiveKeywords> descriptiveKeywords;
    @XmlElement(required = true)
    protected List<ResourceConstraints> resourceConstraints;
    @XmlElement(namespace = "http://www.isotc211.org/2005/srv", required = true)
    protected ServiceType serviceType;
    @XmlElement(namespace = "http://www.isotc211.org/2005/srv", required = true)
    protected ServiceTypeVersion serviceTypeVersion;
    @XmlElement(namespace = "http://www.isotc211.org/2005/srv", required = true)
    protected AccessProperties accessProperties;
    @XmlElement(namespace = "http://www.isotc211.org/2005/srv", required = true)
    protected Restrictions restrictions;
    @XmlElement(namespace = "http://www.isotc211.org/2005/srv", required = true)
    protected SVServiceIdentification.Extent extent;
    @XmlElement(namespace = "http://www.isotc211.org/2005/srv", required = true)
    protected List<CoupledResource> coupledResource;
    @XmlElement(namespace = "http://www.isotc211.org/2005/srv", required = true)
    protected CouplingType couplingType;
    @XmlElement(namespace = "http://www.isotc211.org/2005/srv", required = true)
    protected List<ContainsOperations> containsOperations;
    @XmlElement(namespace = "http://www.isotc211.org/2005/srv", required = true)
    protected OperatesOn operatesOn;

    /**
     * Gets the value of the citation property.
     * 
     * @return
     *     possible object is
     *     {@link Citation }
     *     
     */
    public Citation getCitation() {
        return citation;
    }

    /**
     * Sets the value of the citation property.
     * 
     * @param value
     *     allowed object is
     *     {@link Citation }
     *     
     */
    public void setCitation(Citation value) {
        this.citation = value;
    }

    /**
     * Gets the value of the abstract property.
     * 
     * @return
     *     possible object is
     *     {@link Abstract }
     *     
     */
    public Abstract getAbstract() {
        return _abstract;
    }

    /**
     * Sets the value of the abstract property.
     * 
     * @param value
     *     allowed object is
     *     {@link Abstract }
     *     
     */
    public void setAbstract(Abstract value) {
        this._abstract = value;
    }

    /**
     * Gets the value of the pointOfContact property.
     * 
     * @return
     *     possible object is
     *     {@link PointOfContact }
     *     
     */
    public PointOfContact getPointOfContact() {
        return pointOfContact;
    }

    /**
     * Sets the value of the pointOfContact property.
     * 
     * @param value
     *     allowed object is
     *     {@link PointOfContact }
     *     
     */
    public void setPointOfContact(PointOfContact value) {
        this.pointOfContact = value;
    }

    /**
     * Gets the value of the descriptiveKeywords property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the descriptiveKeywords property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDescriptiveKeywords().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DescriptiveKeywords }
     * 
     * 
     */
    public List<DescriptiveKeywords> getDescriptiveKeywords() {
        if (descriptiveKeywords == null) {
            descriptiveKeywords = new ArrayList<DescriptiveKeywords>();
        }
        return this.descriptiveKeywords;
    }

    /**
     * Gets the value of the resourceConstraints property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the resourceConstraints property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getResourceConstraints().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ResourceConstraints }
     * 
     * 
     */
    public List<ResourceConstraints> getResourceConstraints() {
        if (resourceConstraints == null) {
            resourceConstraints = new ArrayList<ResourceConstraints>();
        }
        return this.resourceConstraints;
    }

    /**
     * Gets the value of the serviceType property.
     * 
     * @return
     *     possible object is
     *     {@link ServiceType }
     *     
     */
    public ServiceType getServiceType() {
        return serviceType;
    }

    /**
     * Sets the value of the serviceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServiceType }
     *     
     */
    public void setServiceType(ServiceType value) {
        this.serviceType = value;
    }

    /**
     * Gets the value of the serviceTypeVersion property.
     * 
     * @return
     *     possible object is
     *     {@link ServiceTypeVersion }
     *     
     */
    public ServiceTypeVersion getServiceTypeVersion() {
        return serviceTypeVersion;
    }

    /**
     * Sets the value of the serviceTypeVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServiceTypeVersion }
     *     
     */
    public void setServiceTypeVersion(ServiceTypeVersion value) {
        this.serviceTypeVersion = value;
    }

    /**
     * Gets the value of the accessProperties property.
     * 
     * @return
     *     possible object is
     *     {@link AccessProperties }
     *     
     */
    public AccessProperties getAccessProperties() {
        return accessProperties;
    }

    /**
     * Sets the value of the accessProperties property.
     * 
     * @param value
     *     allowed object is
     *     {@link AccessProperties }
     *     
     */
    public void setAccessProperties(AccessProperties value) {
        this.accessProperties = value;
    }

    /**
     * Gets the value of the restrictions property.
     * 
     * @return
     *     possible object is
     *     {@link Restrictions }
     *     
     */
    public Restrictions getRestrictions() {
        return restrictions;
    }

    /**
     * Sets the value of the restrictions property.
     * 
     * @param value
     *     allowed object is
     *     {@link Restrictions }
     *     
     */
    public void setRestrictions(Restrictions value) {
        this.restrictions = value;
    }

    /**
     * Gets the value of the extent property.
     * 
     * @return
     *     possible object is
     *     {@link SVServiceIdentification.Extent }
     *     
     */
    public SVServiceIdentification.Extent getExtent() {
        return extent;
    }

    /**
     * Sets the value of the extent property.
     * 
     * @param value
     *     allowed object is
     *     {@link SVServiceIdentification.Extent }
     *     
     */
    public void setExtent(SVServiceIdentification.Extent value) {
        this.extent = value;
    }

    /**
     * Gets the value of the coupledResource property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the coupledResource property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCoupledResource().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CoupledResource }
     * 
     * 
     */
    public List<CoupledResource> getCoupledResource() {
        if (coupledResource == null) {
            coupledResource = new ArrayList<CoupledResource>();
        }
        return this.coupledResource;
    }

    /**
     * Gets the value of the couplingType property.
     * 
     * @return
     *     possible object is
     *     {@link CouplingType }
     *     
     */
    public CouplingType getCouplingType() {
        return couplingType;
    }

    /**
     * Sets the value of the couplingType property.
     * 
     * @param value
     *     allowed object is
     *     {@link CouplingType }
     *     
     */
    public void setCouplingType(CouplingType value) {
        this.couplingType = value;
    }

    /**
     * Gets the value of the containsOperations property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the containsOperations property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContainsOperations().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ContainsOperations }
     * 
     * 
     */
    public List<ContainsOperations> getContainsOperations() {
        if (containsOperations == null) {
            containsOperations = new ArrayList<ContainsOperations>();
        }
        return this.containsOperations;
    }

    /**
     * Gets the value of the operatesOn property.
     * 
     * @return
     *     possible object is
     *     {@link OperatesOn }
     *     
     */
    public OperatesOn getOperatesOn() {
        return operatesOn;
    }

    /**
     * Sets the value of the operatesOn property.
     * 
     * @param value
     *     allowed object is
     *     {@link OperatesOn }
     *     
     */
    public void setOperatesOn(OperatesOn value) {
        this.operatesOn = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{http://www.isotc211.org/2005/gmd}EX_Extent"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "exExtent"
    })
    public static class Extent {

        @XmlElement(name = "EX_Extent", required = true)
        protected EXExtent exExtent;

        /**
         * Gets the value of the exExtent property.
         * 
         * @return
         *     possible object is
         *     {@link EXExtent }
         *     
         */
        public EXExtent getEXExtent() {
            return exExtent;
        }

        /**
         * Sets the value of the exExtent property.
         * 
         * @param value
         *     allowed object is
         *     {@link EXExtent }
         *     
         */
        public void setEXExtent(EXExtent value) {
            this.exExtent = value;
        }

    }

}
