[[anchor-logging-configuration]]
=== Logging configuration

The deegree webservices do use the https://logback.qos.ch[Logback Project] for logging. The configuration of the logging submodule is stored in XML format.
The web application contains a default configuration file _/WEB-INF/classes/logback.xml_ with two appenders, one logging to the console Stdout (`System.out`) and the other writes the log messages into a file _logs/deegree.log_.

The configuration in a nutshell:

The console appender is configured with:

[source,xml]
----
<appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender"> <1>
    <encoder>
        <pattern>%date %level %logger{1} [%thread] %msg%n</pattern> <2>
    </encoder>
    <!--
    <filter class="ch.qos.logback.classic.filter.ThresholdFilter">
        <level>INFO</level> <3>
    </filter>
    -->
</appender>
----
<1> defines the type of the appender
<2> defines the pattern for formatting the log message
<3> defines the threshold for this appender (In this example, it's disabled/commented out)

The file appender is configured with:

[source,xml]
----
<appender name="FILE" class="ch.qos.logback.core.rolling.RollingFileAppender"> <1>
    <file>${log.dir}/${log.prefix}.log</file> <2>
    <rollingPolicy class="ch.qos.logback.core.rolling.SizeAndTimeBasedRollingPolicy"> <3>
        <fileNamePattern>${log.dir}/${log.prefix}-%d{yyyy-MM-dd}.%i.log.gz</fileNamePattern> <4>
        <maxFileSize>100MB</maxFileSize>
        <maxHistory>20</maxHistory>
        <totalSizeCap>1GB</totalSizeCap>
    </rollingPolicy>
    <!--
    <filter class="ch.qos.logback.classic.filter.ThresholdFilter">
        <level>INFO</level> <6>
    </filter>
    -->
    <encoder>
        <pattern>%date %level %logger{1} [%thread] %msg%n</pattern> <5>
    </encoder>
</appender>
----
<1> defines the type of the appender
<2> defines the file name
<3> defines the policies when rolling over the files, triggered by size (>100MB) and time (> 1 day)
<4> defines the format of the archived file names, when the policies are applied
<5> defines the pattern for formatting the log message
<6> defines the threshold for this appender (In this example, it's disabled/commented out)

The log file name is defined by the following settings:

[source,xml]
----
<variable name="log.prefix" value="deegree" /> <1>
<variable name="log.dir" value="logs"/> <2>
----
<1> defines the prefix of the logfiles, default is _deegree_ and can be defined by an environment variable `log.prefix`
<2> defines the log directory, default is _logs/_ and can be defined by an environment variable `log.dir`

To turn off or on a specific logger use the logger definition as in the following example for `org.deegree`:

[source,xml]
----
<logger name="org.deegree" level="INFO"/> <1>
----
<1> defines the logger name and threshold which are applied to all logger starting with `org.deegree`

You will find more information about Logback configuration in the https://logback.qos.ch/documentation.html[Logback documentation].