//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.03.08 at 05:48:39 PM MEZ 
//


package org.deegree.services.controller.wms.configuration;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import org.deegree.services.controller.configuration.ServiceIdentificationType;
import org.deegree.services.controller.configuration.ServiceProviderType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.deegree.org/webservices}ServiceIdentification" minOccurs="0"/>
 *         &lt;element ref="{http://www.deegree.org/webservices}ServiceProvider" minOccurs="0"/>
 *         &lt;element name="SupportedVersions" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Version" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="AllowedOperations" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="GetFeatureInfo" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="GetLegendGraphic" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="GetFeatureInfoFormat" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;choice>
 *                     &lt;element name="File" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                     &lt;element name="Class" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;/choice>
 *                   &lt;element name="Format" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ImageFormat" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Class" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Format" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "serviceIdentification",
    "serviceProvider",
    "supportedVersions",
    "allowedOperations",
    "getFeatureInfoFormat",
    "imageFormat"
})
@XmlRootElement(name = "PublishedInformation")
public class PublishedInformation {

    @XmlElement(name = "ServiceIdentification", namespace = "http://www.deegree.org/webservices")
    protected ServiceIdentificationType serviceIdentification;
    @XmlElement(name = "ServiceProvider", namespace = "http://www.deegree.org/webservices")
    protected ServiceProviderType serviceProvider;
    @XmlElement(name = "SupportedVersions")
    protected PublishedInformation.SupportedVersions supportedVersions;
    @XmlElement(name = "AllowedOperations")
    protected PublishedInformation.AllowedOperations allowedOperations;
    @XmlElement(name = "GetFeatureInfoFormat")
    protected List<PublishedInformation.GetFeatureInfoFormat> getFeatureInfoFormat;
    @XmlElement(name = "ImageFormat")
    protected List<PublishedInformation.ImageFormat> imageFormat;

    /**
     * Gets the value of the serviceIdentification property.
     * 
     * @return
     *     possible object is
     *     {@link ServiceIdentificationType }
     *     
     */
    public ServiceIdentificationType getServiceIdentification() {
        return serviceIdentification;
    }

    /**
     * Sets the value of the serviceIdentification property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServiceIdentificationType }
     *     
     */
    public void setServiceIdentification(ServiceIdentificationType value) {
        this.serviceIdentification = value;
    }

    /**
     * Gets the value of the serviceProvider property.
     * 
     * @return
     *     possible object is
     *     {@link ServiceProviderType }
     *     
     */
    public ServiceProviderType getServiceProvider() {
        return serviceProvider;
    }

    /**
     * Sets the value of the serviceProvider property.
     * 
     * @param value
     *     allowed object is
     *     {@link ServiceProviderType }
     *     
     */
    public void setServiceProvider(ServiceProviderType value) {
        this.serviceProvider = value;
    }

    /**
     * Gets the value of the supportedVersions property.
     * 
     * @return
     *     possible object is
     *     {@link PublishedInformation.SupportedVersions }
     *     
     */
    public PublishedInformation.SupportedVersions getSupportedVersions() {
        return supportedVersions;
    }

    /**
     * Sets the value of the supportedVersions property.
     * 
     * @param value
     *     allowed object is
     *     {@link PublishedInformation.SupportedVersions }
     *     
     */
    public void setSupportedVersions(PublishedInformation.SupportedVersions value) {
        this.supportedVersions = value;
    }

    /**
     * Gets the value of the allowedOperations property.
     * 
     * @return
     *     possible object is
     *     {@link PublishedInformation.AllowedOperations }
     *     
     */
    public PublishedInformation.AllowedOperations getAllowedOperations() {
        return allowedOperations;
    }

    /**
     * Sets the value of the allowedOperations property.
     * 
     * @param value
     *     allowed object is
     *     {@link PublishedInformation.AllowedOperations }
     *     
     */
    public void setAllowedOperations(PublishedInformation.AllowedOperations value) {
        this.allowedOperations = value;
    }

    /**
     * Gets the value of the getFeatureInfoFormat property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the getFeatureInfoFormat property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGetFeatureInfoFormat().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PublishedInformation.GetFeatureInfoFormat }
     * 
     * 
     */
    public List<PublishedInformation.GetFeatureInfoFormat> getGetFeatureInfoFormat() {
        if (getFeatureInfoFormat == null) {
            getFeatureInfoFormat = new ArrayList<PublishedInformation.GetFeatureInfoFormat>();
        }
        return this.getFeatureInfoFormat;
    }

    /**
     * Gets the value of the imageFormat property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the imageFormat property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getImageFormat().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PublishedInformation.ImageFormat }
     * 
     * 
     */
    public List<PublishedInformation.ImageFormat> getImageFormat() {
        if (imageFormat == null) {
            imageFormat = new ArrayList<PublishedInformation.ImageFormat>();
        }
        return this.imageFormat;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="GetFeatureInfo" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="GetLegendGraphic" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "getFeatureInfo",
        "getLegendGraphic"
    })
    public static class AllowedOperations {

        @XmlElement(name = "GetFeatureInfo")
        protected PublishedInformation.AllowedOperations.GetFeatureInfo getFeatureInfo;
        @XmlElement(name = "GetLegendGraphic")
        protected PublishedInformation.AllowedOperations.GetLegendGraphic getLegendGraphic;

        /**
         * Gets the value of the getFeatureInfo property.
         * 
         * @return
         *     possible object is
         *     {@link PublishedInformation.AllowedOperations.GetFeatureInfo }
         *     
         */
        public PublishedInformation.AllowedOperations.GetFeatureInfo getGetFeatureInfo() {
            return getFeatureInfo;
        }

        /**
         * Sets the value of the getFeatureInfo property.
         * 
         * @param value
         *     allowed object is
         *     {@link PublishedInformation.AllowedOperations.GetFeatureInfo }
         *     
         */
        public void setGetFeatureInfo(PublishedInformation.AllowedOperations.GetFeatureInfo value) {
            this.getFeatureInfo = value;
        }

        /**
         * Gets the value of the getLegendGraphic property.
         * 
         * @return
         *     possible object is
         *     {@link PublishedInformation.AllowedOperations.GetLegendGraphic }
         *     
         */
        public PublishedInformation.AllowedOperations.GetLegendGraphic getGetLegendGraphic() {
            return getLegendGraphic;
        }

        /**
         * Sets the value of the getLegendGraphic property.
         * 
         * @param value
         *     allowed object is
         *     {@link PublishedInformation.AllowedOperations.GetLegendGraphic }
         *     
         */
        public void setGetLegendGraphic(PublishedInformation.AllowedOperations.GetLegendGraphic value) {
            this.getLegendGraphic = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class GetFeatureInfo {


        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class GetLegendGraphic {


        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;choice>
     *           &lt;element name="File" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *           &lt;element name="Class" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;/choice>
     *         &lt;element name="Format" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "file",
        "clazz",
        "format"
    })
    public static class GetFeatureInfoFormat {

        @XmlElement(name = "File")
        protected String file;
        @XmlElement(name = "Class")
        protected String clazz;
        @XmlElement(name = "Format", required = true)
        protected String format;

        /**
         * Gets the value of the file property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFile() {
            return file;
        }

        /**
         * Sets the value of the file property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFile(String value) {
            this.file = value;
        }

        /**
         * Gets the value of the clazz property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getClazz() {
            return clazz;
        }

        /**
         * Sets the value of the clazz property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setClazz(String value) {
            this.clazz = value;
        }

        /**
         * Gets the value of the format property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFormat() {
            return format;
        }

        /**
         * Sets the value of the format property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFormat(String value) {
            this.format = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Class" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Format" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "clazz",
        "format"
    })
    public static class ImageFormat {

        @XmlElement(name = "Class", required = true)
        protected String clazz;
        @XmlElement(name = "Format", required = true)
        protected String format;

        /**
         * Gets the value of the clazz property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getClazz() {
            return clazz;
        }

        /**
         * Sets the value of the clazz property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setClazz(String value) {
            this.clazz = value;
        }

        /**
         * Gets the value of the format property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFormat() {
            return format;
        }

        /**
         * Sets the value of the format property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFormat(String value) {
            this.format = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Version" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "version"
    })
    public static class SupportedVersions {

        @XmlElement(name = "Version", required = true)
        protected List<String> version;

        /**
         * Gets the value of the version property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the version property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getVersion().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getVersion() {
            if (version == null) {
                version = new ArrayList<String>();
            }
            return this.version;
        }

    }

}
