//$HeadURL$
/*----------------------------------------------------------------------------
 This file is part of deegree, http://deegree.org/
 Copyright (C) 2001-2009 by:
   Department of Geography, University of Bonn
 and
   lat/lon GmbH

 This library is free software; you can redistribute it and/or modify it under
 the terms of the GNU Lesser General Public License as published by the Free
 Software Foundation; either version 2.1 of the License, or (at your option)
 any later version.
 This library is distributed in the hope that it will be useful, but WITHOUT
 ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 details.
 You should have received a copy of the GNU Lesser General Public License
 along with this library; if not, write to the Free Software Foundation, Inc.,
 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA

 Contact information:

 lat/lon GmbH
 Aennchenstr. 19, 53177 Bonn
 Germany
 http://lat-lon.de/

 Department of Geography, University of Bonn
 Prof. Dr. Klaus Greve
 Postfach 1147, 53001 Bonn
 Germany
 http://www.geographie.uni-bonn.de/deegree/

 e-mail: info@deegree.org
----------------------------------------------------------------------------*/

package org.deegree.ogcwebservices.wpvs.operation;

import java.awt.image.BufferedImage;


/**
 * The <code>GetViewResponse</code> encapsulates the result (a BufferedImage)  of a {@link GetView} request.
 *
 * @author <a href="mailto:taddei@lat-lon.de">Ugo Taddei</a>
 * @author last edited by: $Author$
 *
 * @version 2.0, $Revision$, $Date$
 *
 * @since 2.0
 */
public class GetViewResponse {


    private final BufferedImage output;
    private final String outputformat;

    /**
     * @param output the result of a request
     * @param outputformat specified by the request
     */
    public GetViewResponse( BufferedImage output, String outputformat){
        this.output = output;
        this.outputformat = outputformat;
    }
    /**
     * Gets the format of this response
     * @return a String describing the output format
     */
    public String getOutputFormat() {
        return this.outputformat;
    }

    /**
     * Gets the output of a GetView request
     * @return an Image that is the actual image generated by a GetView request
     */
    public BufferedImage getOutput() {
        return this.output;
    }

}
