DELETE FROM USER_SDO_GEOM_METADATA WHERE TABLE_NAME='EX_BOUNDINGPOLYGON' AND COLUMN_NAME='GEOM';
drop INDEX SPX_BOUNDINGPOLYGON;

DELETE FROM USER_SDO_GEOM_METADATA WHERE TABLE_NAME='EX_GEOGRBBOX' AND COLUMN_NAME='GEOM';
drop INDEX SPX_GEOGRBBOX;

