INSERT INTO USER_SDO_GEOM_METADATA (TABLE_NAME, COLUMN_NAME, DIMINFO, SRID) 
  VALUES ('EX_BOUNDINGPOLYGON', 'GEOM', 
    MDSYS.SDO_DIM_ARRAY 
    (
       MDSYS.SDO_DIM_ELEMENT('X', -360, 360.000, 0.0005), 
       MDSYS.SDO_DIM_ELEMENT('Y', -90, 90, 0.0005)
    ), 4326
  );

CREATE INDEX SPX_BOUNDINGPOLYGON on EX_BOUNDINGPOLYGON(GEOM) INDEXTYPE is MDSYS.SPATIAL_INDEX;


INSERT INTO USER_SDO_GEOM_METADATA (TABLE_NAME, COLUMN_NAME, DIMINFO, SRID) 
  VALUES ('EX_GEOGRBBOX', 'GEOM', 
    MDSYS.SDO_DIM_ARRAY 
    (
       MDSYS.SDO_DIM_ELEMENT('X', -360, 360.000, 0.0005), 
       MDSYS.SDO_DIM_ELEMENT('Y', -90, 90, 0.0005)
    ), 4326
  );

CREATE INDEX SPX_GEOGRBBOX on EX_GEOGRBBOX(GEOM) INDEXTYPE is MDSYS.SPATIAL_INDEX;