DROP INDEX DC_FEATURE_SPATIAL_IDX;
SELECT DropGeometryColumn ('public','dc_feature', 'dc_coverage');
DROP TABLE DC_FEATURE CASCADE;

DROP TABLE DC_DESCRIPTION CASCADE;

DROP TABLE DC_RELATION CASCADE;

DROP TABLE DC_CONTRIBUTOR CASCADE;

DROP TABLE DC_FORMAT CASCADE;

DROP TABLE DC_SOURCE CASCADE;

DROP TABLE DC_CREATOR CASCADE;

DROP TABLE DC_SUBJECT CASCADE;

DROP TABLE DC_PUBLISHER CASCADE;

DROP SEQUENCE DC_FID_seq;

CREATE TABLE DC_FEATURE(
    FID				INT8 		NOT NULL PRIMARY KEY,
    DCT_ABSTRACT 	VARCHAR,
    DC_DATE			DATE,
    DC_IDENTIFIER	VARCHAR 	NOT NULL UNIQUE,
    DC_LANGUAGE		VARCHAR(10),
    DC_RIGHTS		TEXT,
    DC_TYPE			VARCHAR 	NOT NULL,
    DC_TITLE		VARCHAR 	NOT NULL
);
SELECT AddGeometryColumn ('public', 'dc_feature', 'dc_coverage', -1, 'POLYGON', '2');
ALTER TABLE DC_FEATURE ADD CONSTRAINT DC_FEATURE_GEOM_CHECK CHECK (isvalid(dc_coverage));
CREATE INDEX DC_FEATURE_SPATIAL_IDX ON DC_FEATURE USING GIST (dc_coverage GIST_GEOMETRY_OPS);
VACUUM ANALYZE DC_FEATURE;

CREATE TABLE DC_DESCRIPTION(
    FID				INT8  		NOT NULL REFERENCES DC_FEATURE,
    DC_DESCRIPTION	VARCHAR		NOT NULL
);

CREATE TABLE DC_RELATION(
    FID				INT8  		NOT NULL REFERENCES DC_FEATURE,
    DC_RELATION 	VARCHAR 	NOT NULL
);

CREATE TABLE DC_CONTRIBUTOR(
    FID				INT8  		NOT NULL REFERENCES DC_FEATURE,
    DC_CONTRIBUTOR	VARCHAR 	NOT NULL
);

CREATE TABLE DC_FORMAT(
    FID				INT8  		NOT NULL REFERENCES DC_FEATURE,
    DC_FORMAT 		VARCHAR 	NOT NULL
);

CREATE TABLE DC_SOURCE(
    FID				INT8  		NOT NULL REFERENCES DC_FEATURE,
    DC_SOURCE 		VARCHAR 	NOT NULL
);

CREATE TABLE DC_CREATOR(
    FID				INT8  		NOT NULL REFERENCES DC_FEATURE,
    DC_CREATOR 		VARCHAR 	NOT NULL
);

CREATE TABLE DC_SUBJECT(
    FID				INT8  		NOT NULL REFERENCES DC_FEATURE,
    DC_SUBJECT 		VARCHAR 	NOT NULL
);

CREATE TABLE DC_PUBLISHER(
    FID				INT8  		NOT NULL REFERENCES DC_FEATURE,
    DC_PUBLISHER	VARCHAR 	NOT NULL
);

CREATE SEQUENCE DC_FID_seq;
