DROP INDEX DC_FEATURE_SPATIAL_IDX;
SELECT DropGeometryColumn ('public','dc_feature', 'dc_coverage');
DROP TABLE DC_FEATURE CASCADE;

DROP TABLE DC_DESCRIPTION CASCADE;

DROP TABLE DC_RELATION CASCADE;

DROP TABLE DC_CONTRIBUTOR CASCADE;

DROP TABLE DC_FORMAT CASCADE;

DROP TABLE DC_SOURCE CASCADE;

DROP TABLE DC_CREATOR CASCADE;

DROP TABLE DC_SUBJECT CASCADE;

DROP TABLE DC_PUBLISHER CASCADE;

DROP SEQUENCE DC_FID_seq;

