
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Fri Oct 09 13:13:23 CEST 2009
//----------------------------------------------------

package org.deegree.protocol.wms.dims;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int COMMA = 2;
  public static final int error = 1;
  public static final int TOKEN = 4;
  public static final int SLASH = 3;
  public static final int EOF = 0;
}

