/*----------------------------------------------------------------------------
 This file is part of deegree, http://deegree.org/
 Copyright (C) 2001-2009 by:
   Department of Geography, University of Bonn
 and
   lat/lon GmbH

 This library is free software; you can redistribute it and/or modify it under
 the terms of the GNU Lesser General Public License as published by the Free
 Software Foundation; either version 2.1 of the License, or (at your option)
 any later version.
 This library is distributed in the hope that it will be useful, but WITHOUT
 ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 details.
 You should have received a copy of the GNU Lesser General Public License
 along with this library; if not, write to the Free Software Foundation, Inc.,
 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA

 Contact information:

 lat/lon GmbH
 Aennchenstr. 19, 53177 Bonn
 Germany
 http://lat-lon.de/

 Department of Geography, University of Bonn
 Prof. Dr. Klaus Greve
 Postfach 1147, 53001 Bonn
 Germany
 http://www.geographie.uni-bonn.de/deegree/

 e-mail: info@deegree.org
----------------------------------------------------------------------------*/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2008.07.01 at 03:49:29 PM CEST
//


package org.deegree.geometry.configuration;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the org.deegree.geometry.configuration package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 *
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.deegree.geometry.configuration
     *
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ModelConfiguration }
     *
     */
    public ModelConfiguration createModelConfiguration() {
        return new ModelConfiguration();
    }

    /**
     * Create an instance of {@link SupportedSurfaceInterpolationType }
     *
     */
    public SupportedSurfaceInterpolationType createSupportedSurfaceInterpolationType() {
        return new SupportedSurfaceInterpolationType();
    }

    /**
     * Create an instance of {@link SupportedGeometriesType }
     *
     */
    public SupportedGeometriesType createSupportedGeometriesType() {
        return new SupportedGeometriesType();
    }

    /**
     * Create an instance of {@link InitParamType }
     *
     */
    public InitParamType createInitParamType() {
        return new InitParamType();
    }

    /**
     * Create an instance of {@link GeometryFactoryType }
     *
     */
    public GeometryFactoryType createGeometryFactoryType() {
        return new GeometryFactoryType();
    }

    /**
     * Create an instance of {@link GeometryFactoriesType }
     *
     */
    public GeometryFactoriesType createGeometryFactoriesType() {
        return new GeometryFactoriesType();
    }

    /**
     * Create an instance of {@link SupportedCurveInterpolationType }
     *
     */
    public SupportedCurveInterpolationType createSupportedCurveInterpolationType() {
        return new SupportedCurveInterpolationType();
    }

}
