//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.07.01 at 03:49:29 PM CEST 
//


package org.deegree.geometry.configuration;

import java.util.ArrayList;
import java.util.List;
import javax.annotation.Generated;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SupportedSurfaceInterpolationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SupportedSurfaceInterpolationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SurfaceInterpolation" maxOccurs="unbounded">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="none"/>
 *               &lt;enumeration value="planar"/>
 *               &lt;enumeration value="spherical"/>
 *               &lt;enumeration value="elliptical"/>
 *               &lt;enumeration value="conic"/>
 *               &lt;enumeration value="tin"/>
 *               &lt;enumeration value="bilinear"/>
 *               &lt;enumeration value="biquadratic"/>
 *               &lt;enumeration value="bicubic"/>
 *               &lt;enumeration value="polynomialSpline"/>
 *               &lt;enumeration value="rationalSpline"/>
 *               &lt;enumeration value="triangulatedSpline"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SupportedSurfaceInterpolationType", propOrder = {
    "surfaceInterpolation"
})
@Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2008-07-01T03:49:29+02:00", comments = "JAXB RI vJAXB 2.1.3 in JDK 1.6")
public class SupportedSurfaceInterpolationType {

    @XmlElement(name = "SurfaceInterpolation", required = true)
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2008-07-01T03:49:29+02:00", comments = "JAXB RI vJAXB 2.1.3 in JDK 1.6")
    protected List<String> surfaceInterpolation;

    /**
     * Gets the value of the surfaceInterpolation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the surfaceInterpolation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSurfaceInterpolation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    @Generated(value = "com.sun.tools.internal.xjc.Driver", date = "2008-07-01T03:49:29+02:00", comments = "JAXB RI vJAXB 2.1.3 in JDK 1.6")
    public List<String> getSurfaceInterpolation() {
        if (surfaceInterpolation == null) {
            surfaceInterpolation = new ArrayList<String>();
        }
        return this.surfaceInterpolation;
    }

}
