/*----------------------------------------------------------------------------
 This file is part of deegree, http://deegree.org/
 Copyright (C) 2001-2009 by:
   Department of Geography, University of Bonn
 and
   lat/lon GmbH

 This library is free software; you can redistribute it and/or modify it under
 the terms of the GNU Lesser General Public License as published by the Free
 Software Foundation; either version 2.1 of the License, or (at your option)
 any later version.
 This library is distributed in the hope that it will be useful, but WITHOUT
 ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 details.
 You should have received a copy of the GNU Lesser General Public License
 along with this library; if not, write to the Free Software Foundation, Inc.,
 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA

 Contact information:

 lat/lon GmbH
 Aennchenstr. 19, 53177 Bonn
 Germany
 http://lat-lon.de/

 Department of Geography, University of Bonn
 Prof. Dr. Klaus Greve
 Postfach 1147, 53001 Bonn
 Germany
 http://www.geographie.uni-bonn.de/deegree/

 e-mail: info@deegree.org
----------------------------------------------------------------------------*/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2009.05.12 at 09:37:19 AM CEST
//


package org.deegree.commons.datasource.configuration;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * Base type of all data sources.
 *
 * <p>Java class for AbstractGeospatialDataSourceType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="AbstractGeospatialDataSourceType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.deegree.org/datasource}AbstractDataSourceType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.deegree.org/datasource}BBoxConstraint" minOccurs="0"/>
 *         &lt;element ref="{http://www.deegree.org/datasource}ScaleConstraint" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AbstractGeospatialDataSourceType", propOrder = {
    "bBoxConstraint",
    "scaleConstraint"
})
@XmlSeeAlso({
    AbstractWebBasedDataSourceType.class,
    MultiResolutionDataSource.class,
    GeospatialFileSystemDataSourceType.class,
    ConstrainedDatabaseDataSourceType.class,
    RasterFileDataSourceType.class
})
public abstract class AbstractGeospatialDataSourceType
    extends AbstractDataSourceType
{

    @XmlElement(name = "BBoxConstraint")
    protected BBoxConstraint bBoxConstraint;
    @XmlElement(name = "ScaleConstraint")
    protected ScaleConstraint scaleConstraint;

    /**
     * Gets the value of the bBoxConstraint property.
     *
     * @return
     *     possible object is
     *     {@link BBoxConstraint }
     *
     */
    public BBoxConstraint getBBoxConstraint() {
        return bBoxConstraint;
    }

    /**
     * Sets the value of the bBoxConstraint property.
     *
     * @param value
     *     allowed object is
     *     {@link BBoxConstraint }
     *
     */
    public void setBBoxConstraint(BBoxConstraint value) {
        this.bBoxConstraint = value;
    }

    /**
     * Gets the value of the scaleConstraint property.
     *
     * @return
     *     possible object is
     *     {@link ScaleConstraint }
     *
     */
    public ScaleConstraint getScaleConstraint() {
        return scaleConstraint;
    }

    /**
     * Sets the value of the scaleConstraint property.
     *
     * @param value
     *     allowed object is
     *     {@link ScaleConstraint }
     *
     */
    public void setScaleConstraint(ScaleConstraint value) {
        this.scaleConstraint = value;
    }

}
