//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.12.08 at 05:30:06 PM CET 
//


package org.deegree.commons.datasource.configuration;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DirectSQLDataSourceType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DirectSQLDataSourceType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.deegree.org/datasource}FeatureStoreType">
 *       &lt;sequence>
 *         &lt;element name="ConnectionPoolId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SQLStatement" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CoordinateSystem" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DirectSQLDataSourceType", propOrder = {
    "connectionPoolId",
    "sqlStatement",
    "coordinateSystem"
})
public class DirectSQLDataSourceType
    extends FeatureStoreType
{

    @XmlElement(name = "ConnectionPoolId", required = true)
    protected String connectionPoolId;
    @XmlElement(name = "SQLStatement", required = true)
    protected String sqlStatement;
    @XmlElement(name = "CoordinateSystem", required = true)
    protected String coordinateSystem;

    /**
     * Gets the value of the connectionPoolId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConnectionPoolId() {
        return connectionPoolId;
    }

    /**
     * Sets the value of the connectionPoolId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConnectionPoolId(String value) {
        this.connectionPoolId = value;
    }

    /**
     * Gets the value of the sqlStatement property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSQLStatement() {
        return sqlStatement;
    }

    /**
     * Sets the value of the sqlStatement property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSQLStatement(String value) {
        this.sqlStatement = value;
    }

    /**
     * Gets the value of the coordinateSystem property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCoordinateSystem() {
        return coordinateSystem;
    }

    /**
     * Sets the value of the coordinateSystem property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCoordinateSystem(String value) {
        this.coordinateSystem = value;
    }

}
