//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.11.24 at 06:09:05 PM MEZ 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.deegree.org/datasource", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.deegree.commons.datasource.configuration;
