<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:fo="http://www.w3.org/1999/XSL/Format" xmlns:java="java" xmlns:ows2iso="org.deegree.ogcwebservices.csw.iso_profile.OWS2ISO19119" xmlns:smXML="http://metadata.dgiwg.org/smXML" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:iso19119="http://schemas.opengis.net/iso19119">
	<xsl:output encoding="UTF-8"></xsl:output>
	<!-- 
		start variable definitions
	-->
	<xsl:variable name="TIMESTAMP">
		<!--
		date is required but there is no way to to read its value from a WMS capabilities document; 
		instead use current timestamp default
	-->
		<xsl:value-of select="ows2iso:getCurrentTimestamp()"/>
	</xsl:variable>
	<xsl:variable name="DEFAULT_ABSTRACT">BB WMS</xsl:variable>
	<!-- 
		start template definitions
	-->
	<xsl:template match="WMT_MS_Capabilities">
		<smXML:MD_Metadata xmlns:csw="http://www.opengis.net/cat/csw" xmlns:gml="http://www.opengis.net/gml">
			<smXML:fileIdentifier>
				<smXML:CharacterString>
					<xsl:value-of select="./Service/Title"/>
				</smXML:CharacterString>
			</smXML:fileIdentifier>
			<smXML:language>
				<smXML:CharacterString>de</smXML:CharacterString>
			</smXML:language>
			<smXML:hierarchyLevel>
				<smXML:MD_ScopeCode codeList="MD_ScopeCode" codeListValue="service"/>
			</smXML:hierarchyLevel>
			<smXML:hierarchyLevelName>
				<smXML:CharacterString>service</smXML:CharacterString>
			</smXML:hierarchyLevelName>
			<smXML:contact>
				<xsl:choose>
					<xsl:when test="Service/ContactInformation">
						<xsl:call-template name="wms_service_respParty"/>
					</xsl:when>
					<xsl:otherwise>
						<xsl:call-template name="defaultRespParty"/>
					</xsl:otherwise>
				</xsl:choose>
			</smXML:contact>
			<smXML:dateStamp>
				<smXML:DateTime>
					<xsl:value-of select="$TIMESTAMP"/>
				</smXML:DateTime>
			</smXML:dateStamp>
			<smXML:metadataStandardName>
				<smXML:CharacterString>ISO 19115 Geographic Information Metadata</smXML:CharacterString>
			</smXML:metadataStandardName>
			<smXML:metadataStandardVersion>
				<smXML:CharacterString>DIS</smXML:CharacterString>
			</smXML:metadataStandardVersion>
			<xsl:call-template name="identification"/>
			<xsl:apply-templates select="Capability/Layer/SRS"/>
		</smXML:MD_Metadata>
	</xsl:template>
	<xsl:template name="defaultRespParty">
		<!--
		TODO
		add a default definition for a smXML:CI_ResponsibleParty
	-->
	</xsl:template>
	<xsl:template name="wms_service_respParty">
		<!--
			template for adding a reesponsible party from service section of WMS capabilities
		-->
		<smXML:CI_ResponsibleParty>
			<xsl:if test="boolean(./Service/ContactInformation/ContactPersonPrimary/ContactPerson)">
				<smXML:individualName>
					<smXML:CharacterString>
						<xsl:value-of select="./Service/ContactInformation/ContactPersonPrimary/ContactPerson"/>
					</smXML:CharacterString>
				</smXML:individualName>
			</xsl:if>
			<xsl:if test="boolean(./Service/ContactInformation/ContactPersonPrimary/ContactOrganization)">
				<smXML:organisationName>
					<smXML:CharacterString>
						<xsl:value-of select="./Service/ContactInformation/ContactPersonPrimary/ContactOrganization"/>
					</smXML:CharacterString>
				</smXML:organisationName>
			</xsl:if>
			<smXML:contactInfo>
				<smXML:CI_Contact>
					<xsl:if test="./Service/ContactInformation/ContactVoiceTelephone or ./Service/ContactInformation/ContactFacsimileTelephone">
						<smXML:phone>
							<smXML:CI_Telephone>
								<xsl:if test="./Service/ContactInformation/ContactVoiceTelephone">
									<smXML:voice>
										<smXML:CharacterString>
											<xsl:value-of select="./Service/ContactInformation/ContactVoiceTelephone"/>
										</smXML:CharacterString>
									</smXML:voice>
								</xsl:if>
								<xsl:if test="./Service/ContactInformation/ContactFacsimileTelephone">
									<smXML:facsimile>
										<smXML:CharacterString>
											<xsl:value-of select="./Service/ContactInformation/ContactFacsimileTelephone"/>
										</smXML:CharacterString>
									</smXML:facsimile>
								</xsl:if>
							</smXML:CI_Telephone>
						</smXML:phone>
					</xsl:if>
					<xsl:if test="boolean(./Service/ContactInformation/ContactAddress)">
						<smXML:address>
							<smXML:CI_Address>
								<smXML:deliveryPoint>
									<smXML:CharacterString>
										<xsl:value-of select="./Service/ContactInformation/ContactAddress/Address"/>
									</smXML:CharacterString>
								</smXML:deliveryPoint>
								<smXML:city>
									<smXML:CharacterString>
										<xsl:value-of select="./Service/ContactInformation/ContactAddress/City"/>
									</smXML:CharacterString>
								</smXML:city>
								<smXML:administrativeArea>
									<smXML:CharacterString>
										<xsl:value-of select="./Service/ContactInformation/ContactAddress/StateOrProvince"/>
									</smXML:CharacterString>
								</smXML:administrativeArea>
								<smXML:postalCode>
									<smXML:CharacterString>
										<xsl:value-of select="./Service/ContactInformation/ContactAddress/PostCode"/>
									</smXML:CharacterString>
								</smXML:postalCode>
								<smXML:country>
									<smXML:CharacterString>
										<xsl:value-of select="./Service/ContactInformation/ContactAddress/Country"/>
									</smXML:CharacterString>
								</smXML:country>
								<xsl:if test="boolean(./Service/ContactInformation/ContactElectronicMailAddress)">
									<smXML:electronicMailAddress>
										<smXML:CharacterString>
											<xsl:value-of select="./Service/ContactInformation/ContactElectronicMailAddress"/>
										</smXML:CharacterString>
									</smXML:electronicMailAddress>
								</xsl:if>
							</smXML:CI_Address>
						</smXML:address>
					</xsl:if>
					<xsl:if test="boolean(./Service/OnlineResource)">
						<smXML:onlineResource>
							<smXML:CI_OnlineResource>
								<smXML:linkage>
									<smXML:URL>
										<xsl:value-of select="./Service/OnlineResource/@xlink:href"/>
									</smXML:URL>
								</smXML:linkage>
							</smXML:CI_OnlineResource>
						</smXML:onlineResource>
					</xsl:if>
				</smXML:CI_Contact>
			</smXML:contactInfo>
			<smXML:role>
				<smXML:CI_RoleCode codeList="MD_ScopeCode" codeListValue="pointOfContact"/>
			</smXML:role>
		</smXML:CI_ResponsibleParty>
	</xsl:template>
	<xsl:template name="identification">
		<smXML:identificationInfo>
			<iso19119:CSW_ServiceIdentification>
				<smXML:citation>
					<smXML:CI_Citation>
						<smXML:title>
							<smXML:CharacterString>
								<xsl:value-of select="Service/Title"/>
							</smXML:CharacterString>
						</smXML:title>
						<smXML:date>
							<smXML:CI_Date>
								<smXML:date>
									<smXML:DateTime>
										<xsl:value-of select="$TIMESTAMP"/>
									</smXML:DateTime>
								</smXML:date>
								<smXML:dateType>
									<smXML:CI_DateTypeCode codeList="CI_DateTypeCode" codeListValue="creation"/>
								</smXML:dateType>
							</smXML:CI_Date>
						</smXML:date>
					</smXML:CI_Citation>
				</smXML:citation>
				<smXML:abstract>
					<smXML:CharacterString>
						<xsl:choose>
							<xsl:when test="boolean( Service/Abstract )">
								<xsl:value-of select="Service/Abstract"/>
							</xsl:when>
							<xsl:otherwise>
								<xsl:value-of select="$DEFAULT_ABSTRACT"/>
							</xsl:otherwise>
						</xsl:choose>
					</smXML:CharacterString>
				</smXML:abstract>
				<iso19119:serviceType>
					<smXML:CharacterString>OGC:WMS</smXML:CharacterString>
				</iso19119:serviceType>
				<iso19119:serviceTypeVersion>
					<smXML:CharacterString>1.1.1</smXML:CharacterString>
				</iso19119:serviceTypeVersion>
				<xsl:if test="Service/Fees">
					<iso19119:accessProperties>
						<smXML:fees>
							<smXML:CharacterString>
								<xsl:value-of select="Service/Fees"/>
							</smXML:CharacterString>
						</smXML:fees>
					</iso19119:accessProperties>
				</xsl:if>
				<xsl:if test="Service/AccessConstraints">
					<iso19119:restrictions>
						<smXML:MD_LegalConstraints>
							<smXML:useLimitation>
								<smXML:CharacterString>
									<xsl:value-of select="Service/AccessConstraints"/>
								</smXML:CharacterString>
							</smXML:useLimitation>
						</smXML:MD_LegalConstraints>
					</iso19119:restrictions>
				</xsl:if>
				<xsl:call-template name="addGetCapabilitiesOpMetadata"/>
				<xsl:call-template name="addGetMapOpMetadata"/>
				<xsl:if test="boolean(Capability/Request/GetFeatureInfo)">
					<xsl:call-template name="addGetFeatureInfoOpMetadata"/>
				</xsl:if>
				<xsl:if test="boolean(Capability/Request/DescribeLayer)">
					<xsl:call-template name="addDescribeLayerOpMetadata"/>
				</xsl:if>
				<xsl:if test="boolean(Capability/Request/GetLegendGraphic)">
					<xsl:call-template name="addGetLegendGraphicOpMetadata"/>
				</xsl:if>
				<xsl:apply-templates select="Capability/Layer"/>
				<xsl:apply-templates select="Capability/Layer/LatLonBoundingBox"/>
				<iso19119:couplingType>
					<xsl:choose>
						<xsl:when test="Capability/UserDefinedSymbolization/@UserLayer = 1">
							<iso19119:CSW_CouplingType codeList="http://schemas.opengis.net/iso19119/couplingType" codeListValue="mixed"/>
						</xsl:when>
						<xsl:otherwise>
							<iso19119:CSW_CouplingType codeList="http://schemas.opengis.net/iso19119/couplingType" codeListValue="tight"/>
						</xsl:otherwise>
					</xsl:choose>
				</iso19119:couplingType>
			</iso19119:CSW_ServiceIdentification>
		</smXML:identificationInfo>
	</xsl:template>
	<xsl:template name="addGetCapabilitiesOpMetadata">
		<!--
			append GetCapabilities description
		-->
		<iso19119:operationMetadata>
			<iso19119:SV_OperationMetadata>
				<iso19119:operationName>
					<smXML:CharacterString>GetCapabilities</smXML:CharacterString>
				</iso19119:operationName>
				<xsl:apply-templates select="Capability/Request/GetCapabilities/DCPType/HTTP"/>
				<xsl:choose>
					<xsl:when test="boolean(Capability/Request/GetCapabilities/DCPType/HTTP/*)">
						<xsl:apply-templates select="Capability/Request/GetCapabilities/DCPType/HTTP/Get/OnlineResource"/>
					</xsl:when>
					<xsl:otherwise>
						<xsl:apply-templates select="Capability/Request/GetCapabilities/DCPType/HTTP/Post/OnlineResource"/>
					</xsl:otherwise>
				</xsl:choose>
				<iso19119:parameters>
					<iso19119:SV_Parameter>
						<iso19119:name>
							<smXML:MemberName>
								<smXML:aName>
									<smXML:CharacterString>Service</smXML:CharacterString>
								</smXML:aName>
								<smXML:attributeType>
									<smXML:TypeName>
										<smXML:aName>
											<smXML:CharacterString>String</smXML:CharacterString>
										</smXML:aName>
									</smXML:TypeName>
								</smXML:attributeType>
							</smXML:MemberName>
						</iso19119:name>
						<iso19119:direction>
							<iso19119:SV_ParameterDirection>in</iso19119:SV_ParameterDirection>
						</iso19119:direction>
						<iso19119:description>
							<smXML:CharacterString>-</smXML:CharacterString>
						</iso19119:description>
						<iso19119:optionality>
							<smXML:CharacterString>mandatory</smXML:CharacterString>
						</iso19119:optionality>
						<iso19119:repeatability>
							<smXML:Boolean>false</smXML:Boolean>
						</iso19119:repeatability>
					</iso19119:SV_Parameter>
				</iso19119:parameters>
				<iso19119:parameters>
					<iso19119:SV_Parameter>
						<iso19119:name>
							<smXML:MemberName>
								<smXML:aName>
									<smXML:CharacterString>Version</smXML:CharacterString>
								</smXML:aName>
								<smXML:attributeType>
									<smXML:TypeName>
										<smXML:aName>
											<smXML:CharacterString>String</smXML:CharacterString>
										</smXML:aName>
									</smXML:TypeName>
								</smXML:attributeType>
							</smXML:MemberName>
						</iso19119:name>
						<iso19119:direction>
							<iso19119:SV_ParameterDirection>in</iso19119:SV_ParameterDirection>
						</iso19119:direction>
						<iso19119:description>
							<smXML:CharacterString>-</smXML:CharacterString>
						</iso19119:description>
						<iso19119:optionality>
							<smXML:CharacterString>optional</smXML:CharacterString>
						</iso19119:optionality>
						<iso19119:repeatability>
							<smXML:Boolean>false</smXML:Boolean>
						</iso19119:repeatability>
					</iso19119:SV_Parameter>
				</iso19119:parameters>
				<iso19119:parameters>
					<iso19119:SV_Parameter>
						<iso19119:name>
							<smXML:MemberName>
								<smXML:aName>
									<smXML:CharacterString>Request</smXML:CharacterString>
								</smXML:aName>
								<smXML:attributeType>
									<smXML:TypeName>
										<smXML:aName>
											<smXML:CharacterString>String</smXML:CharacterString>
										</smXML:aName>
									</smXML:TypeName>
								</smXML:attributeType>
							</smXML:MemberName>
						</iso19119:name>
						<iso19119:direction>
							<iso19119:SV_ParameterDirection>in</iso19119:SV_ParameterDirection>
						</iso19119:direction>
						<iso19119:description>
							<smXML:CharacterString>fixed value: GetCapabilities</smXML:CharacterString>
						</iso19119:description>
						<iso19119:optionality>
							<smXML:CharacterString>mandatory</smXML:CharacterString>
						</iso19119:optionality>
						<iso19119:repeatability>
							<smXML:Boolean>false</smXML:Boolean>
						</iso19119:repeatability>
					</iso19119:SV_Parameter>
				</iso19119:parameters>
			</iso19119:SV_OperationMetadata>
		</iso19119:operationMetadata>
	</xsl:template>
	<xsl:template name="addGetMapOpMetadata">
		<!--
			append GetMap description
		-->
		<iso19119:operationMetadata>
			<iso19119:SV_OperationMetadata>
				<iso19119:operationName>
					<smXML:CharacterString>GetMap</smXML:CharacterString>
				</iso19119:operationName>
				<xsl:apply-templates select="Capability/Request/GetMap/DCPType/HTTP"/>
				<xsl:choose>
					<xsl:when test="boolean(Capability/Request/GetMap/DCPType/HTTP/*)">
						<xsl:apply-templates select="Capability/Request/GetMap/DCPType/HTTP/Get/OnlineResource"/>
					</xsl:when>
					<xsl:otherwise>
						<xsl:apply-templates select="Capability/Request/GetMap/DCPType/HTTP/Post/OnlineResource"/>
					</xsl:otherwise>
				</xsl:choose>
				<iso19119:parameters>
					<iso19119:SV_Parameter>
						<iso19119:name>
							<smXML:MemberName>
								<smXML:aName>
									<smXML:CharacterString>Version</smXML:CharacterString>
								</smXML:aName>
								<smXML:attributeType>
									<smXML:TypeName>
										<smXML:aName>
											<smXML:CharacterString>String</smXML:CharacterString>
										</smXML:aName>
									</smXML:TypeName>
								</smXML:attributeType>
							</smXML:MemberName>
						</iso19119:name>
						<iso19119:direction>
							<iso19119:SV_ParameterDirection>in</iso19119:SV_ParameterDirection>
						</iso19119:direction>
						<iso19119:description>
							<smXML:CharacterString>-</smXML:CharacterString>
						</iso19119:description>
						<iso19119:optionality>
							<smXML:CharacterString>mandatory</smXML:CharacterString>
						</iso19119:optionality>
						<iso19119:repeatability>
							<smXML:Boolean>false</smXML:Boolean>
						</iso19119:repeatability>
					</iso19119:SV_Parameter>
				</iso19119:parameters>
				<iso19119:parameters>
					<iso19119:SV_Parameter>
						<iso19119:name>
							<smXML:MemberName>
								<smXML:aName>
									<smXML:CharacterString>Request</smXML:CharacterString>
								</smXML:aName>
								<smXML:attributeType>
									<smXML:TypeName>
										<smXML:aName>
											<smXML:CharacterString>String</smXML:CharacterString>
										</smXML:aName>
									</smXML:TypeName>
								</smXML:attributeType>
							</smXML:MemberName>
						</iso19119:name>
						<iso19119:direction>
							<iso19119:SV_ParameterDirection>in</iso19119:SV_ParameterDirection>
						</iso19119:direction>
						<iso19119:description>
							<smXML:CharacterString>fixed value: GetMap</smXML:CharacterString>
						</iso19119:description>
						<iso19119:optionality>
							<smXML:CharacterString>mandatory</smXML:CharacterString>
						</iso19119:optionality>
						<iso19119:repeatability>
							<smXML:Boolean>false</smXML:Boolean>
						</iso19119:repeatability>
					</iso19119:SV_Parameter>
				</iso19119:parameters>
				<iso19119:parameters>
					<iso19119:SV_Parameter>
						<iso19119:name>
							<smXML:MemberName>
								<smXML:aName>
									<smXML:CharacterString>Layers</smXML:CharacterString>
								</smXML:aName>
								<smXML:attributeType>
									<smXML:TypeName>
										<smXML:aName>
											<smXML:CharacterString>String</smXML:CharacterString>
										</smXML:aName>
									</smXML:TypeName>
								</smXML:attributeType>
							</smXML:MemberName>
						</iso19119:name>
						<iso19119:direction>
							<iso19119:SV_ParameterDirection>in</iso19119:SV_ParameterDirection>
						</iso19119:direction>
						<iso19119:description>
							<smXML:CharacterString>-</smXML:CharacterString>
						</iso19119:description>
						<iso19119:optionality>
							<smXML:CharacterString>mandatory</smXML:CharacterString>
						</iso19119:optionality>
						<iso19119:repeatability>
							<smXML:Boolean>false</smXML:Boolean>
						</iso19119:repeatability>
					</iso19119:SV_Parameter>
				</iso19119:parameters>
				<iso19119:parameters>
					<iso19119:SV_Parameter>
						<iso19119:name>
							<smXML:MemberName>
								<smXML:aName>
									<smXML:CharacterString>Styles</smXML:CharacterString>
								</smXML:aName>
								<smXML:attributeType>
									<smXML:TypeName>
										<smXML:aName>
											<smXML:CharacterString>String</smXML:CharacterString>
										</smXML:aName>
									</smXML:TypeName>
								</smXML:attributeType>
							</smXML:MemberName>
						</iso19119:name>
						<iso19119:direction>
							<iso19119:SV_ParameterDirection>in</iso19119:SV_ParameterDirection>
						</iso19119:direction>
						<iso19119:description>
							<smXML:CharacterString>-</smXML:CharacterString>
						</iso19119:description>
						<iso19119:optionality>
							<smXML:CharacterString>mandatory</smXML:CharacterString>
						</iso19119:optionality>
						<iso19119:repeatability>
							<smXML:Boolean>false</smXML:Boolean>
						</iso19119:repeatability>
					</iso19119:SV_Parameter>
				</iso19119:parameters>
				<iso19119:parameters>
					<iso19119:SV_Parameter>
						<iso19119:name>
							<smXML:MemberName>
								<smXML:aName>
									<smXML:CharacterString>srs</smXML:CharacterString>
								</smXML:aName>
								<smXML:attributeType>
									<smXML:TypeName>
										<smXML:aName>
											<smXML:CharacterString>String</smXML:CharacterString>
										</smXML:aName>
									</smXML:TypeName>
								</smXML:attributeType>
							</smXML:MemberName>
						</iso19119:name>
						<iso19119:direction>
							<iso19119:SV_ParameterDirection>in</iso19119:SV_ParameterDirection>
						</iso19119:direction>
						<iso19119:description>
							<smXML:CharacterString>-</smXML:CharacterString>
						</iso19119:description>
						<iso19119:optionality>
							<smXML:CharacterString>mandatory</smXML:CharacterString>
						</iso19119:optionality>
						<iso19119:repeatability>
							<smXML:Boolean>false</smXML:Boolean>
						</iso19119:repeatability>
					</iso19119:SV_Parameter>
				</iso19119:parameters>
				<iso19119:parameters>
					<iso19119:SV_Parameter>
						<iso19119:name>
							<smXML:MemberName>
								<smXML:aName>
									<smXML:CharacterString>BBOX</smXML:CharacterString>
								</smXML:aName>
								<smXML:attributeType>
									<smXML:TypeName>
										<smXML:aName>
											<smXML:CharacterString>String</smXML:CharacterString>
										</smXML:aName>
									</smXML:TypeName>
								</smXML:attributeType>
							</smXML:MemberName>
						</iso19119:name>
						<iso19119:direction>
							<iso19119:SV_ParameterDirection>in</iso19119:SV_ParameterDirection>
						</iso19119:direction>
						<iso19119:description>
							<smXML:CharacterString>-</smXML:CharacterString>
						</iso19119:description>
						<iso19119:optionality>
							<smXML:CharacterString>mandatory</smXML:CharacterString>
						</iso19119:optionality>
						<iso19119:repeatability>
							<smXML:Boolean>false</smXML:Boolean>
						</iso19119:repeatability>
					</iso19119:SV_Parameter>
				</iso19119:parameters>
				<iso19119:parameters>
					<iso19119:SV_Parameter>
						<iso19119:name>
							<smXML:MemberName>
								<smXML:aName>
									<smXML:CharacterString>width</smXML:CharacterString>
								</smXML:aName>
								<smXML:attributeType>
									<smXML:TypeName>
										<smXML:aName>
											<smXML:CharacterString>integer</smXML:CharacterString>
										</smXML:aName>
									</smXML:TypeName>
								</smXML:attributeType>
							</smXML:MemberName>
						</iso19119:name>
						<iso19119:direction>
							<iso19119:SV_ParameterDirection>in</iso19119:SV_ParameterDirection>
						</iso19119:direction>
						<iso19119:description>
							<smXML:CharacterString>-</smXML:CharacterString>
						</iso19119:description>
						<iso19119:optionality>
							<smXML:CharacterString>mandatory</smXML:CharacterString>
						</iso19119:optionality>
						<iso19119:repeatability>
							<smXML:Boolean>false</smXML:Boolean>
						</iso19119:repeatability>
					</iso19119:SV_Parameter>
				</iso19119:parameters>
				<iso19119:parameters>
					<iso19119:SV_Parameter>
						<iso19119:name>
							<smXML:MemberName>
								<smXML:aName>
									<smXML:CharacterString>height</smXML:CharacterString>
								</smXML:aName>
								<smXML:attributeType>
									<smXML:TypeName>
										<smXML:aName>
											<smXML:CharacterString>integer</smXML:CharacterString>
										</smXML:aName>
									</smXML:TypeName>
								</smXML:attributeType>
							</smXML:MemberName>
						</iso19119:name>
						<iso19119:direction>
							<iso19119:SV_ParameterDirection>in</iso19119:SV_ParameterDirection>
						</iso19119:direction>
						<iso19119:description>
							<smXML:CharacterString>-</smXML:CharacterString>
						</iso19119:description>
						<iso19119:optionality>
							<smXML:CharacterString>mandatory</smXML:CharacterString>
						</iso19119:optionality>
						<iso19119:repeatability>
							<smXML:Boolean>false</smXML:Boolean>
						</iso19119:repeatability>
					</iso19119:SV_Parameter>
				</iso19119:parameters>
				<iso19119:parameters>
					<iso19119:SV_Parameter>
						<iso19119:name>
							<smXML:MemberName>
								<smXML:aName>
									<smXML:CharacterString>Format</smXML:CharacterString>
								</smXML:aName>
								<smXML:attributeType>
									<smXML:TypeName>
										<smXML:aName>
											<smXML:CharacterString>String</smXML:CharacterString>
										</smXML:aName>
									</smXML:TypeName>
								</smXML:attributeType>
							</smXML:MemberName>
						</iso19119:name>
						<iso19119:direction>
							<iso19119:SV_ParameterDirection>in</iso19119:SV_ParameterDirection>
						</iso19119:direction>
						<iso19119:description>
							<smXML:CharacterString>-</smXML:CharacterString>
						</iso19119:description>
						<iso19119:optionality>
							<smXML:CharacterString>mandatory</smXML:CharacterString>
						</iso19119:optionality>
						<iso19119:repeatability>
							<smXML:Boolean>false</smXML:Boolean>
						</iso19119:repeatability>
					</iso19119:SV_Parameter>
				</iso19119:parameters>
				<iso19119:parameters>
					<iso19119:SV_Parameter>
						<iso19119:name>
							<smXML:MemberName>
								<smXML:aName>
									<smXML:CharacterString>TRANSPARENT</smXML:CharacterString>
								</smXML:aName>
								<smXML:attributeType>
									<smXML:TypeName>
										<smXML:aName>
											<smXML:CharacterString>boolean</smXML:CharacterString>
										</smXML:aName>
									</smXML:TypeName>
								</smXML:attributeType>
							</smXML:MemberName>
						</iso19119:name>
						<iso19119:direction>
							<iso19119:SV_ParameterDirection>in</iso19119:SV_ParameterDirection>
						</iso19119:direction>
						<iso19119:description>
							<smXML:CharacterString>-</smXML:CharacterString>
						</iso19119:description>
						<iso19119:optionality>
							<smXML:CharacterString>optional</smXML:CharacterString>
						</iso19119:optionality>
						<iso19119:repeatability>
							<smXML:Boolean>false</smXML:Boolean>
						</iso19119:repeatability>
					</iso19119:SV_Parameter>
				</iso19119:parameters>
				<iso19119:parameters>
					<iso19119:SV_Parameter>
						<iso19119:name>
							<smXML:MemberName>
								<smXML:aName>
									<smXML:CharacterString>BGCOLOR</smXML:CharacterString>
								</smXML:aName>
								<smXML:attributeType>
									<smXML:TypeName>
										<smXML:aName>
											<smXML:CharacterString>String</smXML:CharacterString>
										</smXML:aName>
									</smXML:TypeName>
								</smXML:attributeType>
							</smXML:MemberName>
						</iso19119:name>
						<iso19119:direction>
							<iso19119:SV_ParameterDirection>in</iso19119:SV_ParameterDirection>
						</iso19119:direction>
						<iso19119:description>
							<smXML:CharacterString>-</smXML:CharacterString>
						</iso19119:description>
						<iso19119:optionality>
							<smXML:CharacterString>optional</smXML:CharacterString>
						</iso19119:optionality>
						<iso19119:repeatability>
							<smXML:Boolean>false</smXML:Boolean>
						</iso19119:repeatability>
					</iso19119:SV_Parameter>
				</iso19119:parameters>
				<iso19119:parameters>
					<iso19119:SV_Parameter>
						<iso19119:name>
							<smXML:MemberName>
								<smXML:aName>
									<smXML:CharacterString>EXCEPTIONS</smXML:CharacterString>
								</smXML:aName>
								<smXML:attributeType>
									<smXML:TypeName>
										<smXML:aName>
											<smXML:CharacterString>String</smXML:CharacterString>
										</smXML:aName>
									</smXML:TypeName>
								</smXML:attributeType>
							</smXML:MemberName>
						</iso19119:name>
						<iso19119:direction>
							<iso19119:SV_ParameterDirection>in</iso19119:SV_ParameterDirection>
						</iso19119:direction>
						<iso19119:description>
							<smXML:CharacterString>-</smXML:CharacterString>
						</iso19119:description>
						<iso19119:optionality>
							<smXML:CharacterString>optional</smXML:CharacterString>
						</iso19119:optionality>
						<iso19119:repeatability>
							<smXML:Boolean>false</smXML:Boolean>
						</iso19119:repeatability>
					</iso19119:SV_Parameter>
				</iso19119:parameters>
				<iso19119:parameters>
					<iso19119:SV_Parameter>
						<iso19119:name>
							<smXML:MemberName>
								<smXML:aName>
									<smXML:CharacterString>TIME</smXML:CharacterString>
								</smXML:aName>
								<smXML:attributeType>
									<smXML:TypeName>
										<smXML:aName>
											<smXML:CharacterString>String</smXML:CharacterString>
										</smXML:aName>
									</smXML:TypeName>
								</smXML:attributeType>
							</smXML:MemberName>
						</iso19119:name>
						<iso19119:direction>
							<iso19119:SV_ParameterDirection>in</iso19119:SV_ParameterDirection>
						</iso19119:direction>
						<iso19119:description>
							<smXML:CharacterString>-</smXML:CharacterString>
						</iso19119:description>
						<iso19119:optionality>
							<smXML:CharacterString>optional</smXML:CharacterString>
						</iso19119:optionality>
						<iso19119:repeatability>
							<smXML:Boolean>false</smXML:Boolean>
						</iso19119:repeatability>
					</iso19119:SV_Parameter>
				</iso19119:parameters>
				<iso19119:parameters>
					<iso19119:SV_Parameter>
						<iso19119:name>
							<smXML:MemberName>
								<smXML:aName>
									<smXML:CharacterString>ELEVATION</smXML:CharacterString>
								</smXML:aName>
								<smXML:attributeType>
									<smXML:TypeName>
										<smXML:aName>
											<smXML:CharacterString>String</smXML:CharacterString>
										</smXML:aName>
									</smXML:TypeName>
								</smXML:attributeType>
							</smXML:MemberName>
						</iso19119:name>
						<iso19119:direction>
							<iso19119:SV_ParameterDirection>in</iso19119:SV_ParameterDirection>
						</iso19119:direction>
						<iso19119:description>
							<smXML:CharacterString>-</smXML:CharacterString>
						</iso19119:description>
						<iso19119:optionality>
							<smXML:CharacterString>optional</smXML:CharacterString>
						</iso19119:optionality>
						<iso19119:repeatability>
							<smXML:Boolean>false</smXML:Boolean>
						</iso19119:repeatability>
					</iso19119:SV_Parameter>
				</iso19119:parameters>
			</iso19119:SV_OperationMetadata>
		</iso19119:operationMetadata>
	</xsl:template>
	<xsl:template name="addGetFeatureInfoOpMetadata">
		<!--
			append GetFeatureInfo description
		-->
		<iso19119:operationMetadata>
			<iso19119:SV_OperationMetadata>
				<iso19119:operationName>
					<smXML:CharacterString>GetFeatureInfo</smXML:CharacterString>
				</iso19119:operationName>
				<xsl:apply-templates select="Capability/Request/GetFeatureInfo/DCPType/HTTP"/>
				<xsl:choose>
					<xsl:when test="boolean(Capability/Request/GetFeatureInfo/DCPType/HTTP/*)">
						<xsl:apply-templates select="Capability/Request/GetFeatureInfo/DCPType/HTTP/Get/OnlineResource"/>
					</xsl:when>
					<xsl:otherwise>
						<xsl:apply-templates select="Capability/Request/GetFeatureInfo/DCPType/HTTP/Post/OnlineResource"/>
					</xsl:otherwise>
				</xsl:choose>
				<iso19119:parameters>
					<iso19119:SV_Parameter>
						<iso19119:name>
							<smXML:MemberName>
								<smXML:aName>
									<smXML:CharacterString>Version</smXML:CharacterString>
								</smXML:aName>
								<smXML:attributeType>
									<smXML:TypeName>
										<smXML:aName>
											<smXML:CharacterString>String</smXML:CharacterString>
										</smXML:aName>
									</smXML:TypeName>
								</smXML:attributeType>
							</smXML:MemberName>
						</iso19119:name>
						<iso19119:direction>
							<iso19119:SV_ParameterDirection>in</iso19119:SV_ParameterDirection>
						</iso19119:direction>
						<iso19119:description>
							<smXML:CharacterString>-</smXML:CharacterString>
						</iso19119:description>
						<iso19119:optionality>
							<smXML:CharacterString>optional</smXML:CharacterString>
						</iso19119:optionality>
						<iso19119:repeatability>
							<smXML:Boolean>false</smXML:Boolean>
						</iso19119:repeatability>
					</iso19119:SV_Parameter>
				</iso19119:parameters>
				<iso19119:parameters>
					<iso19119:SV_Parameter>
						<iso19119:name>
							<smXML:MemberName>
								<smXML:aName>
									<smXML:CharacterString>Request</smXML:CharacterString>
								</smXML:aName>
								<smXML:attributeType>
									<smXML:TypeName>
										<smXML:aName>
											<smXML:CharacterString>String</smXML:CharacterString>
										</smXML:aName>
									</smXML:TypeName>
								</smXML:attributeType>
							</smXML:MemberName>
						</iso19119:name>
						<iso19119:direction>
							<iso19119:SV_ParameterDirection>in</iso19119:SV_ParameterDirection>
						</iso19119:direction>
						<iso19119:description>
							<smXML:CharacterString>fixed value: GetFeatureInfo</smXML:CharacterString>
						</iso19119:description>
						<iso19119:optionality>
							<smXML:CharacterString>mandatory</smXML:CharacterString>
						</iso19119:optionality>
						<iso19119:repeatability>
							<smXML:Boolean>false</smXML:Boolean>
						</iso19119:repeatability>
					</iso19119:SV_Parameter>
				</iso19119:parameters>
				<iso19119:parameters>
					<iso19119:SV_Parameter>
						<iso19119:name>
							<smXML:MemberName>
								<smXML:aName>
									<smXML:CharacterString>Layers</smXML:CharacterString>
								</smXML:aName>
								<smXML:attributeType>
									<smXML:TypeName>
										<smXML:aName>
											<smXML:CharacterString>String</smXML:CharacterString>
										</smXML:aName>
									</smXML:TypeName>
								</smXML:attributeType>
							</smXML:MemberName>
						</iso19119:name>
						<iso19119:direction>
							<iso19119:SV_ParameterDirection>in</iso19119:SV_ParameterDirection>
						</iso19119:direction>
						<iso19119:description>
							<smXML:CharacterString>-</smXML:CharacterString>
						</iso19119:description>
						<iso19119:optionality>
							<smXML:CharacterString>mandatory</smXML:CharacterString>
						</iso19119:optionality>
						<iso19119:repeatability>
							<smXML:Boolean>false</smXML:Boolean>
						</iso19119:repeatability>
					</iso19119:SV_Parameter>
				</iso19119:parameters>
				<iso19119:parameters>
					<iso19119:SV_Parameter>
						<iso19119:name>
							<smXML:MemberName>
								<smXML:aName>
									<smXML:CharacterString>Styles</smXML:CharacterString>
								</smXML:aName>
								<smXML:attributeType>
									<smXML:TypeName>
										<smXML:aName>
											<smXML:CharacterString>String</smXML:CharacterString>
										</smXML:aName>
									</smXML:TypeName>
								</smXML:attributeType>
							</smXML:MemberName>
						</iso19119:name>
						<iso19119:direction>
							<iso19119:SV_ParameterDirection>in</iso19119:SV_ParameterDirection>
						</iso19119:direction>
						<iso19119:description>
							<smXML:CharacterString>-</smXML:CharacterString>
						</iso19119:description>
						<iso19119:optionality>
							<smXML:CharacterString>mandatory</smXML:CharacterString>
						</iso19119:optionality>
						<iso19119:repeatability>
							<smXML:Boolean>false</smXML:Boolean>
						</iso19119:repeatability>
					</iso19119:SV_Parameter>
				</iso19119:parameters>
				<iso19119:parameters>
					<iso19119:SV_Parameter>
						<iso19119:name>
							<smXML:MemberName>
								<smXML:aName>
									<smXML:CharacterString>srs</smXML:CharacterString>
								</smXML:aName>
								<smXML:attributeType>
									<smXML:TypeName>
										<smXML:aName>
											<smXML:CharacterString>String</smXML:CharacterString>
										</smXML:aName>
									</smXML:TypeName>
								</smXML:attributeType>
							</smXML:MemberName>
						</iso19119:name>
						<iso19119:direction>
							<iso19119:SV_ParameterDirection>in</iso19119:SV_ParameterDirection>
						</iso19119:direction>
						<iso19119:description>
							<smXML:CharacterString>-</smXML:CharacterString>
						</iso19119:description>
						<iso19119:optionality>
							<smXML:CharacterString>mandatory</smXML:CharacterString>
						</iso19119:optionality>
						<iso19119:repeatability>
							<smXML:Boolean>false</smXML:Boolean>
						</iso19119:repeatability>
					</iso19119:SV_Parameter>
				</iso19119:parameters>
				<iso19119:parameters>
					<iso19119:SV_Parameter>
						<iso19119:name>
							<smXML:MemberName>
								<smXML:aName>
									<smXML:CharacterString>BBOX</smXML:CharacterString>
								</smXML:aName>
								<smXML:attributeType>
									<smXML:TypeName>
										<smXML:aName>
											<smXML:CharacterString>String</smXML:CharacterString>
										</smXML:aName>
									</smXML:TypeName>
								</smXML:attributeType>
							</smXML:MemberName>
						</iso19119:name>
						<iso19119:direction>
							<iso19119:SV_ParameterDirection>in</iso19119:SV_ParameterDirection>
						</iso19119:direction>
						<iso19119:description>
							<smXML:CharacterString>-</smXML:CharacterString>
						</iso19119:description>
						<iso19119:optionality>
							<smXML:CharacterString>mandatory</smXML:CharacterString>
						</iso19119:optionality>
						<iso19119:repeatability>
							<smXML:Boolean>false</smXML:Boolean>
						</iso19119:repeatability>
					</iso19119:SV_Parameter>
				</iso19119:parameters>
				<iso19119:parameters>
					<iso19119:SV_Parameter>
						<iso19119:name>
							<smXML:MemberName>
								<smXML:aName>
									<smXML:CharacterString>width</smXML:CharacterString>
								</smXML:aName>
								<smXML:attributeType>
									<smXML:TypeName>
										<smXML:aName>
											<smXML:CharacterString>integer</smXML:CharacterString>
										</smXML:aName>
									</smXML:TypeName>
								</smXML:attributeType>
							</smXML:MemberName>
						</iso19119:name>
						<iso19119:direction>
							<iso19119:SV_ParameterDirection>in</iso19119:SV_ParameterDirection>
						</iso19119:direction>
						<iso19119:description>
							<smXML:CharacterString>-</smXML:CharacterString>
						</iso19119:description>
						<iso19119:optionality>
							<smXML:CharacterString>mandatory</smXML:CharacterString>
						</iso19119:optionality>
						<iso19119:repeatability>
							<smXML:Boolean>false</smXML:Boolean>
						</iso19119:repeatability>
					</iso19119:SV_Parameter>
				</iso19119:parameters>
				<iso19119:parameters>
					<iso19119:SV_Parameter>
						<iso19119:name>
							<smXML:MemberName>
								<smXML:aName>
									<smXML:CharacterString>height</smXML:CharacterString>
								</smXML:aName>
								<smXML:attributeType>
									<smXML:TypeName>
										<smXML:aName>
											<smXML:CharacterString>integer</smXML:CharacterString>
										</smXML:aName>
									</smXML:TypeName>
								</smXML:attributeType>
							</smXML:MemberName>
						</iso19119:name>
						<iso19119:direction>
							<iso19119:SV_ParameterDirection>in</iso19119:SV_ParameterDirection>
						</iso19119:direction>
						<iso19119:description>
							<smXML:CharacterString>-</smXML:CharacterString>
						</iso19119:description>
						<iso19119:optionality>
							<smXML:CharacterString>mandatory</smXML:CharacterString>
						</iso19119:optionality>
						<iso19119:repeatability>
							<smXML:Boolean>false</smXML:Boolean>
						</iso19119:repeatability>
					</iso19119:SV_Parameter>
				</iso19119:parameters>
				<iso19119:parameters>
					<iso19119:SV_Parameter>
						<iso19119:name>
							<smXML:MemberName>
								<smXML:aName>
									<smXML:CharacterString>Format</smXML:CharacterString>
								</smXML:aName>
								<smXML:attributeType>
									<smXML:TypeName>
										<smXML:aName>
											<smXML:CharacterString>String</smXML:CharacterString>
										</smXML:aName>
									</smXML:TypeName>
								</smXML:attributeType>
							</smXML:MemberName>
						</iso19119:name>
						<iso19119:direction>
							<iso19119:SV_ParameterDirection>in</iso19119:SV_ParameterDirection>
						</iso19119:direction>
						<iso19119:description>
							<smXML:CharacterString>-</smXML:CharacterString>
						</iso19119:description>
						<iso19119:optionality>
							<smXML:CharacterString>mandatory</smXML:CharacterString>
						</iso19119:optionality>
						<iso19119:repeatability>
							<smXML:Boolean>false</smXML:Boolean>
						</iso19119:repeatability>
					</iso19119:SV_Parameter>
				</iso19119:parameters>
				<iso19119:parameters>
					<iso19119:SV_Parameter>
						<iso19119:name>
							<smXML:MemberName>
								<smXML:aName>
									<smXML:CharacterString>TRANSPARENT</smXML:CharacterString>
								</smXML:aName>
								<smXML:attributeType>
									<smXML:TypeName>
										<smXML:aName>
											<smXML:CharacterString>boolean</smXML:CharacterString>
										</smXML:aName>
									</smXML:TypeName>
								</smXML:attributeType>
							</smXML:MemberName>
						</iso19119:name>
						<iso19119:direction>
							<iso19119:SV_ParameterDirection>in</iso19119:SV_ParameterDirection>
						</iso19119:direction>
						<iso19119:description>
							<smXML:CharacterString>-</smXML:CharacterString>
						</iso19119:description>
						<iso19119:optionality>
							<smXML:CharacterString>optional</smXML:CharacterString>
						</iso19119:optionality>
						<iso19119:repeatability>
							<smXML:Boolean>false</smXML:Boolean>
						</iso19119:repeatability>
					</iso19119:SV_Parameter>
				</iso19119:parameters>
				<iso19119:parameters>
					<iso19119:SV_Parameter>
						<iso19119:name>
							<smXML:MemberName>
								<smXML:aName>
									<smXML:CharacterString>BGCOLOR</smXML:CharacterString>
								</smXML:aName>
								<smXML:attributeType>
									<smXML:TypeName>
										<smXML:aName>
											<smXML:CharacterString>String</smXML:CharacterString>
										</smXML:aName>
									</smXML:TypeName>
								</smXML:attributeType>
							</smXML:MemberName>
						</iso19119:name>
						<iso19119:direction>
							<iso19119:SV_ParameterDirection>in</iso19119:SV_ParameterDirection>
						</iso19119:direction>
						<iso19119:description>
							<smXML:CharacterString>-</smXML:CharacterString>
						</iso19119:description>
						<iso19119:optionality>
							<smXML:CharacterString>optional</smXML:CharacterString>
						</iso19119:optionality>
						<iso19119:repeatability>
							<smXML:Boolean>false</smXML:Boolean>
						</iso19119:repeatability>
					</iso19119:SV_Parameter>
				</iso19119:parameters>
				<iso19119:parameters>
					<iso19119:SV_Parameter>
						<iso19119:name>
							<smXML:MemberName>
								<smXML:aName>
									<smXML:CharacterString>EXCEPTIONS</smXML:CharacterString>
								</smXML:aName>
								<smXML:attributeType>
									<smXML:TypeName>
										<smXML:aName>
											<smXML:CharacterString>String</smXML:CharacterString>
										</smXML:aName>
									</smXML:TypeName>
								</smXML:attributeType>
							</smXML:MemberName>
						</iso19119:name>
						<iso19119:direction>
							<iso19119:SV_ParameterDirection>in</iso19119:SV_ParameterDirection>
						</iso19119:direction>
						<iso19119:description>
							<smXML:CharacterString>-</smXML:CharacterString>
						</iso19119:description>
						<iso19119:optionality>
							<smXML:CharacterString>optional</smXML:CharacterString>
						</iso19119:optionality>
						<iso19119:repeatability>
							<smXML:Boolean>false</smXML:Boolean>
						</iso19119:repeatability>
					</iso19119:SV_Parameter>
				</iso19119:parameters>
				<iso19119:parameters>
					<iso19119:SV_Parameter>
						<iso19119:name>
							<smXML:MemberName>
								<smXML:aName>
									<smXML:CharacterString>TIME</smXML:CharacterString>
								</smXML:aName>
								<smXML:attributeType>
									<smXML:TypeName>
										<smXML:aName>
											<smXML:CharacterString>String</smXML:CharacterString>
										</smXML:aName>
									</smXML:TypeName>
								</smXML:attributeType>
							</smXML:MemberName>
						</iso19119:name>
						<iso19119:direction>
							<iso19119:SV_ParameterDirection>in</iso19119:SV_ParameterDirection>
						</iso19119:direction>
						<iso19119:description>
							<smXML:CharacterString>-</smXML:CharacterString>
						</iso19119:description>
						<iso19119:optionality>
							<smXML:CharacterString>optional</smXML:CharacterString>
						</iso19119:optionality>
						<iso19119:repeatability>
							<smXML:Boolean>false</smXML:Boolean>
						</iso19119:repeatability>
					</iso19119:SV_Parameter>
				</iso19119:parameters>
				<iso19119:parameters>
					<iso19119:SV_Parameter>
						<iso19119:name>
							<smXML:MemberName>
								<smXML:aName>
									<smXML:CharacterString>ELEVATION</smXML:CharacterString>
								</smXML:aName>
								<smXML:attributeType>
									<smXML:TypeName>
										<smXML:aName>
											<smXML:CharacterString>String</smXML:CharacterString>
										</smXML:aName>
									</smXML:TypeName>
								</smXML:attributeType>
							</smXML:MemberName>
						</iso19119:name>
						<iso19119:direction>
							<iso19119:SV_ParameterDirection>in</iso19119:SV_ParameterDirection>
						</iso19119:direction>
						<iso19119:description>
							<smXML:CharacterString>-</smXML:CharacterString>
						</iso19119:description>
						<iso19119:optionality>
							<smXML:CharacterString>optional</smXML:CharacterString>
						</iso19119:optionality>
						<iso19119:repeatability>
							<smXML:Boolean>false</smXML:Boolean>
						</iso19119:repeatability>
					</iso19119:SV_Parameter>
				</iso19119:parameters>
				<iso19119:parameters>
					<iso19119:SV_Parameter>
						<iso19119:name>
							<smXML:MemberName>
								<smXML:aName>
									<smXML:CharacterString>QUERY_LAYERS</smXML:CharacterString>
								</smXML:aName>
								<smXML:attributeType>
									<smXML:TypeName>
										<smXML:aName>
											<smXML:CharacterString>String</smXML:CharacterString>
										</smXML:aName>
									</smXML:TypeName>
								</smXML:attributeType>
							</smXML:MemberName>
						</iso19119:name>
						<iso19119:direction>
							<iso19119:SV_ParameterDirection>in</iso19119:SV_ParameterDirection>
						</iso19119:direction>
						<iso19119:description>
							<smXML:CharacterString>-</smXML:CharacterString>
						</iso19119:description>
						<iso19119:optionality>
							<smXML:CharacterString>mandatory</smXML:CharacterString>
						</iso19119:optionality>
						<iso19119:repeatability>
							<smXML:Boolean>false</smXML:Boolean>
						</iso19119:repeatability>
					</iso19119:SV_Parameter>
				</iso19119:parameters>
				<iso19119:parameters>
					<iso19119:SV_Parameter>
						<iso19119:name>
							<smXML:MemberName>
								<smXML:aName>
									<smXML:CharacterString>INFO_FORMAT</smXML:CharacterString>
								</smXML:aName>
								<smXML:attributeType>
									<smXML:TypeName>
										<smXML:aName>
											<smXML:CharacterString>String</smXML:CharacterString>
										</smXML:aName>
									</smXML:TypeName>
								</smXML:attributeType>
							</smXML:MemberName>
						</iso19119:name>
						<iso19119:direction>
							<iso19119:SV_ParameterDirection>in</iso19119:SV_ParameterDirection>
						</iso19119:direction>
						<iso19119:description>
							<smXML:CharacterString>-</smXML:CharacterString>
						</iso19119:description>
						<iso19119:optionality>
							<smXML:CharacterString>optional</smXML:CharacterString>
						</iso19119:optionality>
						<iso19119:repeatability>
							<smXML:Boolean>false</smXML:Boolean>
						</iso19119:repeatability>
					</iso19119:SV_Parameter>
				</iso19119:parameters>
				<iso19119:parameters>
					<iso19119:SV_Parameter>
						<iso19119:name>
							<smXML:MemberName>
								<smXML:aName>
									<smXML:CharacterString>FEATURE_COUNT</smXML:CharacterString>
								</smXML:aName>
								<smXML:attributeType>
									<smXML:TypeName>
										<smXML:aName>
											<smXML:CharacterString>integer</smXML:CharacterString>
										</smXML:aName>
									</smXML:TypeName>
								</smXML:attributeType>
							</smXML:MemberName>
						</iso19119:name>
						<iso19119:direction>
							<iso19119:SV_ParameterDirection>in</iso19119:SV_ParameterDirection>
						</iso19119:direction>
						<iso19119:description>
							<smXML:CharacterString>-</smXML:CharacterString>
						</iso19119:description>
						<iso19119:optionality>
							<smXML:CharacterString>optional</smXML:CharacterString>
						</iso19119:optionality>
						<iso19119:repeatability>
							<smXML:Boolean>false</smXML:Boolean>
						</iso19119:repeatability>
					</iso19119:SV_Parameter>
				</iso19119:parameters>
				<iso19119:parameters>
					<iso19119:SV_Parameter>
						<iso19119:name>
							<smXML:MemberName>
								<smXML:aName>
									<smXML:CharacterString>x</smXML:CharacterString>
								</smXML:aName>
								<smXML:attributeType>
									<smXML:TypeName>
										<smXML:aName>
											<smXML:CharacterString>integer</smXML:CharacterString>
										</smXML:aName>
									</smXML:TypeName>
								</smXML:attributeType>
							</smXML:MemberName>
						</iso19119:name>
						<iso19119:direction>
							<iso19119:SV_ParameterDirection>in</iso19119:SV_ParameterDirection>
						</iso19119:direction>
						<iso19119:description>
							<smXML:CharacterString>-</smXML:CharacterString>
						</iso19119:description>
						<iso19119:optionality>
							<smXML:CharacterString>mandatory</smXML:CharacterString>
						</iso19119:optionality>
						<iso19119:repeatability>
							<smXML:Boolean>false</smXML:Boolean>
						</iso19119:repeatability>
					</iso19119:SV_Parameter>
				</iso19119:parameters>
				<iso19119:parameters>
					<iso19119:SV_Parameter>
						<iso19119:name>
							<smXML:MemberName>
								<smXML:aName>
									<smXML:CharacterString>y</smXML:CharacterString>
								</smXML:aName>
								<smXML:attributeType>
									<smXML:TypeName>
										<smXML:aName>
											<smXML:CharacterString>integer</smXML:CharacterString>
										</smXML:aName>
									</smXML:TypeName>
								</smXML:attributeType>
							</smXML:MemberName>
						</iso19119:name>
						<iso19119:direction>
							<iso19119:SV_ParameterDirection>in</iso19119:SV_ParameterDirection>
						</iso19119:direction>
						<iso19119:description>
							<smXML:CharacterString>-</smXML:CharacterString>
						</iso19119:description>
						<iso19119:optionality>
							<smXML:CharacterString>mandatory</smXML:CharacterString>
						</iso19119:optionality>
						<iso19119:repeatability>
							<smXML:Boolean>false</smXML:Boolean>
						</iso19119:repeatability>
					</iso19119:SV_Parameter>
				</iso19119:parameters>
			</iso19119:SV_OperationMetadata>
		</iso19119:operationMetadata>
	</xsl:template>
	<xsl:template name="addDescribeLayerOpMetadata">
		<!--
			append DescribeLayer description
		-->
		<iso19119:operationMetadata>
			<iso19119:SV_OperationMetadata>
				<iso19119:operationName>
					<smXML:CharacterString>DescribeLayer</smXML:CharacterString>
				</iso19119:operationName>
				<xsl:apply-templates select="Capability/Request/DescribeLayer/DCPType/HTTP"/>
				<xsl:choose>
					<xsl:when test="boolean(Capability/Request/DescribeLayer/DCPType/HTTP/*)">
						<xsl:apply-templates select="Capability/Request/DescribeLayer/DCPType/HTTP/Get/OnlineResource"/>
					</xsl:when>
					<xsl:otherwise>
						<xsl:apply-templates select="Capability/Request/DescribeLayer/DCPType/HTTP/Post/OnlineResource"/>
					</xsl:otherwise>
				</xsl:choose>
				<iso19119:parameters>
					<iso19119:SV_Parameter>
						<iso19119:name>
							<smXML:MemberName>
								<smXML:aName>
									<smXML:CharacterString>Version</smXML:CharacterString>
								</smXML:aName>
								<smXML:attributeType>
									<smXML:TypeName>
										<smXML:aName>
											<smXML:CharacterString>String</smXML:CharacterString>
										</smXML:aName>
									</smXML:TypeName>
								</smXML:attributeType>
							</smXML:MemberName>
						</iso19119:name>
						<iso19119:direction>
							<iso19119:SV_ParameterDirection>in</iso19119:SV_ParameterDirection>
						</iso19119:direction>
						<iso19119:description>
							<smXML:CharacterString>-</smXML:CharacterString>
						</iso19119:description>
						<iso19119:optionality>
							<smXML:CharacterString>optional</smXML:CharacterString>
						</iso19119:optionality>
						<iso19119:repeatability>
							<smXML:Boolean>false</smXML:Boolean>
						</iso19119:repeatability>
					</iso19119:SV_Parameter>
				</iso19119:parameters>
				<iso19119:parameters>
					<iso19119:SV_Parameter>
						<iso19119:name>
							<smXML:MemberName>
								<smXML:aName>
									<smXML:CharacterString>Request</smXML:CharacterString>
								</smXML:aName>
								<smXML:attributeType>
									<smXML:TypeName>
										<smXML:aName>
											<smXML:CharacterString>String</smXML:CharacterString>
										</smXML:aName>
									</smXML:TypeName>
								</smXML:attributeType>
							</smXML:MemberName>
						</iso19119:name>
						<iso19119:direction>
							<iso19119:SV_ParameterDirection>in</iso19119:SV_ParameterDirection>
						</iso19119:direction>
						<iso19119:description>
							<smXML:CharacterString>fixed value: DescribeLayer</smXML:CharacterString>
						</iso19119:description>
						<iso19119:optionality>
							<smXML:CharacterString>mandatory</smXML:CharacterString>
						</iso19119:optionality>
						<iso19119:repeatability>
							<smXML:Boolean>false</smXML:Boolean>
						</iso19119:repeatability>
					</iso19119:SV_Parameter>
				</iso19119:parameters>
				<iso19119:parameters>
					<iso19119:SV_Parameter>
						<iso19119:name>
							<smXML:MemberName>
								<smXML:aName>
									<smXML:CharacterString>Layers</smXML:CharacterString>
								</smXML:aName>
								<smXML:attributeType>
									<smXML:TypeName>
										<smXML:aName>
											<smXML:CharacterString>String</smXML:CharacterString>
										</smXML:aName>
									</smXML:TypeName>
								</smXML:attributeType>
							</smXML:MemberName>
						</iso19119:name>
						<iso19119:direction>
							<iso19119:SV_ParameterDirection>in</iso19119:SV_ParameterDirection>
						</iso19119:direction>
						<iso19119:description>
							<smXML:CharacterString>fixed value: DescribeLayer</smXML:CharacterString>
						</iso19119:description>
						<iso19119:optionality>
							<smXML:CharacterString>mandatory</smXML:CharacterString>
						</iso19119:optionality>
						<iso19119:repeatability>
							<smXML:Boolean>false</smXML:Boolean>
						</iso19119:repeatability>
					</iso19119:SV_Parameter>
				</iso19119:parameters>
			</iso19119:SV_OperationMetadata>
		</iso19119:operationMetadata>
	</xsl:template>
	<xsl:template name="addGetLegendGraphicOpMetadata">
		<!--
			append GetLegendGraphic description
		-->
		<iso19119:operationMetadata>
			<iso19119:SV_OperationMetadata>
				<iso19119:operationName>
					<smXML:CharacterString>GetLegendGraphic</smXML:CharacterString>
				</iso19119:operationName>
				<xsl:apply-templates select="Capability/Request/GetLegendGraphic/DCPType/HTTP"/>
				<xsl:choose>
					<xsl:when test="boolean(Capability/Request/GetLegendGraphic/DCPType/HTTP/*)">
						<xsl:apply-templates select="Capability/Request/GetLegendGraphic/DCPType/HTTP/Get/OnlineResource"/>
					</xsl:when>
					<xsl:otherwise>
						<xsl:apply-templates select="Capability/Request/GetLegendGraphic/DCPType/HTTP/Post/OnlineResource"/>
					</xsl:otherwise>
				</xsl:choose>
				<iso19119:parameters>
					<iso19119:SV_Parameter>
						<iso19119:name>
							<smXML:MemberName>
								<smXML:aName>
									<smXML:CharacterString>Version</smXML:CharacterString>
								</smXML:aName>
								<smXML:attributeType>
									<smXML:TypeName>
										<smXML:aName>
											<smXML:CharacterString>String</smXML:CharacterString>
										</smXML:aName>
									</smXML:TypeName>
								</smXML:attributeType>
							</smXML:MemberName>
						</iso19119:name>
						<iso19119:direction>
							<iso19119:SV_ParameterDirection>in</iso19119:SV_ParameterDirection>
						</iso19119:direction>
						<iso19119:description>
							<smXML:CharacterString>-</smXML:CharacterString>
						</iso19119:description>
						<iso19119:optionality>
							<smXML:CharacterString>optional</smXML:CharacterString>
						</iso19119:optionality>
						<iso19119:repeatability>
							<smXML:Boolean>false</smXML:Boolean>
						</iso19119:repeatability>
					</iso19119:SV_Parameter>
				</iso19119:parameters>
				<iso19119:parameters>
					<iso19119:SV_Parameter>
						<iso19119:name>
							<smXML:MemberName>
								<smXML:aName>
									<smXML:CharacterString>Request</smXML:CharacterString>
								</smXML:aName>
								<smXML:attributeType>
									<smXML:TypeName>
										<smXML:aName>
											<smXML:CharacterString>String</smXML:CharacterString>
										</smXML:aName>
									</smXML:TypeName>
								</smXML:attributeType>
							</smXML:MemberName>
						</iso19119:name>
						<iso19119:direction>
							<iso19119:SV_ParameterDirection>in</iso19119:SV_ParameterDirection>
						</iso19119:direction>
						<iso19119:description>
							<smXML:CharacterString>fixed value: GetLegendGraphic</smXML:CharacterString>
						</iso19119:description>
						<iso19119:optionality>
							<smXML:CharacterString>mandatory</smXML:CharacterString>
						</iso19119:optionality>
						<iso19119:repeatability>
							<smXML:Boolean>false</smXML:Boolean>
						</iso19119:repeatability>
					</iso19119:SV_Parameter>
				</iso19119:parameters>
				<iso19119:parameters>
					<iso19119:SV_Parameter>
						<iso19119:name>
							<smXML:MemberName>
								<smXML:aName>
									<smXML:CharacterString>Layer</smXML:CharacterString>
								</smXML:aName>
								<smXML:attributeType>
									<smXML:TypeName>
										<smXML:aName>
											<smXML:CharacterString>String</smXML:CharacterString>
										</smXML:aName>
									</smXML:TypeName>
								</smXML:attributeType>
							</smXML:MemberName>
						</iso19119:name>
						<iso19119:direction>
							<iso19119:SV_ParameterDirection>in</iso19119:SV_ParameterDirection>
						</iso19119:direction>
						<iso19119:description>
							<smXML:CharacterString>fixed value: DescribeLayer</smXML:CharacterString>
						</iso19119:description>
						<iso19119:optionality>
							<smXML:CharacterString>mandatory</smXML:CharacterString>
						</iso19119:optionality>
						<iso19119:repeatability>
							<smXML:Boolean>false</smXML:Boolean>
						</iso19119:repeatability>
					</iso19119:SV_Parameter>
				</iso19119:parameters>
				<iso19119:parameters>
					<iso19119:SV_Parameter>
						<iso19119:name>
							<smXML:MemberName>
								<smXML:aName>
									<smXML:CharacterString>Style</smXML:CharacterString>
								</smXML:aName>
								<smXML:attributeType>
									<smXML:TypeName>
										<smXML:aName>
											<smXML:CharacterString>String</smXML:CharacterString>
										</smXML:aName>
									</smXML:TypeName>
								</smXML:attributeType>
							</smXML:MemberName>
						</iso19119:name>
						<iso19119:direction>
							<iso19119:SV_ParameterDirection>in</iso19119:SV_ParameterDirection>
						</iso19119:direction>
						<iso19119:description>
							<smXML:CharacterString>fixed value: DescribeLayer</smXML:CharacterString>
						</iso19119:description>
						<iso19119:optionality>
							<smXML:CharacterString>optional</smXML:CharacterString>
						</iso19119:optionality>
						<iso19119:repeatability>
							<smXML:Boolean>false</smXML:Boolean>
						</iso19119:repeatability>
					</iso19119:SV_Parameter>
				</iso19119:parameters>
				<iso19119:parameters>
					<iso19119:SV_Parameter>
						<iso19119:name>
							<smXML:MemberName>
								<smXML:aName>
									<smXML:CharacterString>FEATURETYPE</smXML:CharacterString>
								</smXML:aName>
								<smXML:attributeType>
									<smXML:TypeName>
										<smXML:aName>
											<smXML:CharacterString>String</smXML:CharacterString>
										</smXML:aName>
									</smXML:TypeName>
								</smXML:attributeType>
							</smXML:MemberName>
						</iso19119:name>
						<iso19119:direction>
							<iso19119:SV_ParameterDirection>in</iso19119:SV_ParameterDirection>
						</iso19119:direction>
						<iso19119:description>
							<smXML:CharacterString>fixed value: DescribeLayer</smXML:CharacterString>
						</iso19119:description>
						<iso19119:optionality>
							<smXML:CharacterString>optional</smXML:CharacterString>
						</iso19119:optionality>
						<iso19119:repeatability>
							<smXML:Boolean>false</smXML:Boolean>
						</iso19119:repeatability>
					</iso19119:SV_Parameter>
				</iso19119:parameters>
				<iso19119:parameters>
					<iso19119:SV_Parameter>
						<iso19119:name>
							<smXML:MemberName>
								<smXML:aName>
									<smXML:CharacterString>RULE</smXML:CharacterString>
								</smXML:aName>
								<smXML:attributeType>
									<smXML:TypeName>
										<smXML:aName>
											<smXML:CharacterString>String</smXML:CharacterString>
										</smXML:aName>
									</smXML:TypeName>
								</smXML:attributeType>
							</smXML:MemberName>
						</iso19119:name>
						<iso19119:direction>
							<iso19119:SV_ParameterDirection>in</iso19119:SV_ParameterDirection>
						</iso19119:direction>
						<iso19119:description>
							<smXML:CharacterString>fixed value: DescribeLayer</smXML:CharacterString>
						</iso19119:description>
						<iso19119:optionality>
							<smXML:CharacterString>optional</smXML:CharacterString>
						</iso19119:optionality>
						<iso19119:repeatability>
							<smXML:Boolean>false</smXML:Boolean>
						</iso19119:repeatability>
					</iso19119:SV_Parameter>
				</iso19119:parameters>
				<iso19119:parameters>
					<iso19119:SV_Parameter>
						<iso19119:name>
							<smXML:MemberName>
								<smXML:aName>
									<smXML:CharacterString>SCALE</smXML:CharacterString>
								</smXML:aName>
								<smXML:attributeType>
									<smXML:TypeName>
										<smXML:aName>
											<smXML:CharacterString>integer</smXML:CharacterString>
										</smXML:aName>
									</smXML:TypeName>
								</smXML:attributeType>
							</smXML:MemberName>
						</iso19119:name>
						<iso19119:direction>
							<iso19119:SV_ParameterDirection>in</iso19119:SV_ParameterDirection>
						</iso19119:direction>
						<iso19119:description>
							<smXML:CharacterString>fixed value: DescribeLayer</smXML:CharacterString>
						</iso19119:description>
						<iso19119:optionality>
							<smXML:CharacterString>optional</smXML:CharacterString>
						</iso19119:optionality>
						<iso19119:repeatability>
							<smXML:Boolean>false</smXML:Boolean>
						</iso19119:repeatability>
					</iso19119:SV_Parameter>
				</iso19119:parameters>
				<iso19119:parameters>
					<iso19119:SV_Parameter>
						<iso19119:name>
							<smXML:MemberName>
								<smXML:aName>
									<smXML:CharacterString>SLD</smXML:CharacterString>
								</smXML:aName>
								<smXML:attributeType>
									<smXML:TypeName>
										<smXML:aName>
											<smXML:CharacterString>String</smXML:CharacterString>
										</smXML:aName>
									</smXML:TypeName>
								</smXML:attributeType>
							</smXML:MemberName>
						</iso19119:name>
						<iso19119:direction>
							<iso19119:SV_ParameterDirection>in</iso19119:SV_ParameterDirection>
						</iso19119:direction>
						<iso19119:description>
							<smXML:CharacterString>fixed value: DescribeLayer</smXML:CharacterString>
						</iso19119:description>
						<iso19119:optionality>
							<smXML:CharacterString>optional</smXML:CharacterString>
						</iso19119:optionality>
						<iso19119:repeatability>
							<smXML:Boolean>false</smXML:Boolean>
						</iso19119:repeatability>
					</iso19119:SV_Parameter>
				</iso19119:parameters>
				<iso19119:parameters>
					<iso19119:SV_Parameter>
						<iso19119:name>
							<smXML:MemberName>
								<smXML:aName>
									<smXML:CharacterString>SLD_BODY</smXML:CharacterString>
								</smXML:aName>
								<smXML:attributeType>
									<smXML:TypeName>
										<smXML:aName>
											<smXML:CharacterString>String</smXML:CharacterString>
										</smXML:aName>
									</smXML:TypeName>
								</smXML:attributeType>
							</smXML:MemberName>
						</iso19119:name>
						<iso19119:direction>
							<iso19119:SV_ParameterDirection>in</iso19119:SV_ParameterDirection>
						</iso19119:direction>
						<iso19119:description>
							<smXML:CharacterString>fixed value: DescribeLayer</smXML:CharacterString>
						</iso19119:description>
						<iso19119:optionality>
							<smXML:CharacterString>optional</smXML:CharacterString>
						</iso19119:optionality>
						<iso19119:repeatability>
							<smXML:Boolean>false</smXML:Boolean>
						</iso19119:repeatability>
					</iso19119:SV_Parameter>
				</iso19119:parameters>
				<iso19119:parameters>
					<iso19119:SV_Parameter>
						<iso19119:name>
							<smXML:MemberName>
								<smXML:aName>
									<smXML:CharacterString>FORMAT</smXML:CharacterString>
								</smXML:aName>
								<smXML:attributeType>
									<smXML:TypeName>
										<smXML:aName>
											<smXML:CharacterString>String</smXML:CharacterString>
										</smXML:aName>
									</smXML:TypeName>
								</smXML:attributeType>
							</smXML:MemberName>
						</iso19119:name>
						<iso19119:direction>
							<iso19119:SV_ParameterDirection>in</iso19119:SV_ParameterDirection>
						</iso19119:direction>
						<iso19119:description>
							<smXML:CharacterString>fixed value: DescribeLayer</smXML:CharacterString>
						</iso19119:description>
						<iso19119:optionality>
							<smXML:CharacterString>mandatory</smXML:CharacterString>
						</iso19119:optionality>
						<iso19119:repeatability>
							<smXML:Boolean>false</smXML:Boolean>
						</iso19119:repeatability>
					</iso19119:SV_Parameter>
				</iso19119:parameters>
				<iso19119:parameters>
					<iso19119:SV_Parameter>
						<iso19119:name>
							<smXML:MemberName>
								<smXML:aName>
									<smXML:CharacterString>WIDTH</smXML:CharacterString>
								</smXML:aName>
								<smXML:attributeType>
									<smXML:TypeName>
										<smXML:aName>
											<smXML:CharacterString>integer</smXML:CharacterString>
										</smXML:aName>
									</smXML:TypeName>
								</smXML:attributeType>
							</smXML:MemberName>
						</iso19119:name>
						<iso19119:direction>
							<iso19119:SV_ParameterDirection>in</iso19119:SV_ParameterDirection>
						</iso19119:direction>
						<iso19119:description>
							<smXML:CharacterString>fixed value: DescribeLayer</smXML:CharacterString>
						</iso19119:description>
						<iso19119:optionality>
							<smXML:CharacterString>optional</smXML:CharacterString>
						</iso19119:optionality>
						<iso19119:repeatability>
							<smXML:Boolean>false</smXML:Boolean>
						</iso19119:repeatability>
					</iso19119:SV_Parameter>
				</iso19119:parameters>
				<iso19119:parameters>
					<iso19119:SV_Parameter>
						<iso19119:name>
							<smXML:MemberName>
								<smXML:aName>
									<smXML:CharacterString>HEIGHT</smXML:CharacterString>
								</smXML:aName>
								<smXML:attributeType>
									<smXML:TypeName>
										<smXML:aName>
											<smXML:CharacterString>integer</smXML:CharacterString>
										</smXML:aName>
									</smXML:TypeName>
								</smXML:attributeType>
							</smXML:MemberName>
						</iso19119:name>
						<iso19119:direction>
							<iso19119:SV_ParameterDirection>in</iso19119:SV_ParameterDirection>
						</iso19119:direction>
						<iso19119:description>
							<smXML:CharacterString>fixed value: DescribeLayer</smXML:CharacterString>
						</iso19119:description>
						<iso19119:optionality>
							<smXML:CharacterString>optional</smXML:CharacterString>
						</iso19119:optionality>
						<iso19119:repeatability>
							<smXML:Boolean>false</smXML:Boolean>
						</iso19119:repeatability>
					</iso19119:SV_Parameter>
				</iso19119:parameters>
				<iso19119:parameters>
					<iso19119:SV_Parameter>
						<iso19119:name>
							<smXML:MemberName>
								<smXML:aName>
									<smXML:CharacterString>EXCEPTIONS</smXML:CharacterString>
								</smXML:aName>
								<smXML:attributeType>
									<smXML:TypeName>
										<smXML:aName>
											<smXML:CharacterString>String</smXML:CharacterString>
										</smXML:aName>
									</smXML:TypeName>
								</smXML:attributeType>
							</smXML:MemberName>
						</iso19119:name>
						<iso19119:direction>
							<iso19119:SV_ParameterDirection>in</iso19119:SV_ParameterDirection>
						</iso19119:direction>
						<iso19119:description>
							<smXML:CharacterString>fixed value: DescribeLayer</smXML:CharacterString>
						</iso19119:description>
						<iso19119:optionality>
							<smXML:CharacterString>optional</smXML:CharacterString>
						</iso19119:optionality>
						<iso19119:repeatability>
							<smXML:Boolean>false</smXML:Boolean>
						</iso19119:repeatability>
					</iso19119:SV_Parameter>
				</iso19119:parameters>
			</iso19119:SV_OperationMetadata>
		</iso19119:operationMetadata>
	</xsl:template>
	<xsl:template match="HTTP">
		<xsl:if test="boolean(Get)">
			<iso19119:DCP>
				<iso19119:SV_DCPList codeList="SV_DCPTypeCode" codeListValue="HTTPGet"/>
			</iso19119:DCP>
		</xsl:if>
		<xsl:if test="boolean(Post)">
			<iso19119:DCP>
				<iso19119:SV_DCPList codeList="SV_DCPTypeCode" codeListValue="HTTPPost"/>
			</iso19119:DCP>
		</xsl:if>
	</xsl:template>
	<xsl:template match="OnlineResource">
		<iso19119:connectPoint>
			<smXML:CI_OnlineResource>
				<smXML:linkage>
					<smXML:URL>
						<xsl:value-of select="./@xlink:href"/>
					</smXML:URL>
				</smXML:linkage>
			</smXML:CI_OnlineResource>
		</iso19119:connectPoint>
	</xsl:template>
	<xsl:template match="Layer">
		<xsl:if test="boolean(Name)">
			<iso19119:operatesOn>
				<smXML:MD_DataIdentification>
					<smXML:citation>
						<smXML:CI_Citation>
							<smXML:title>
								<smXML:CharacterString>
									<xsl:value-of select="Title"/>
								</smXML:CharacterString>
							</smXML:title>
							<smXML:date>
								<!--
									date is required but there is no way to to read its value from a WMS capabilities
									document; instead use current timestamp and revision as default
								-->
								<smXML:CI_Date>
									<smXML:date>
										<smXML:DateTime>
											<xsl:value-of select="$TIMESTAMP"/>
										</smXML:DateTime>
									</smXML:date>
									<smXML:dateType>
										<smXML:CI_DateTypeCode codeList="CI_DateTypeCode" codeListValue="revision"/>
									</smXML:dateType>
								</smXML:CI_Date>
							</smXML:date>
							<smXML:identifier>
								<smXML:MD_Identifier>
									<smXML:code>
										<smXML:CharacterString>
											<xsl:value-of select="Name"/>
										</smXML:CharacterString>
									</smXML:code>
								</smXML:MD_Identifier>
							</smXML:identifier>
						</smXML:CI_Citation>
					</smXML:citation>
					<xsl:choose>
						<xsl:when test="Abstract">
							<smXML:abstract>
								<smXML:CharacterString>
									<xsl:value-of select="Abstract"/>
								</smXML:CharacterString>
							</smXML:abstract>
						</xsl:when>
						<xsl:otherwise>
							<smXML:abstract>
								<smXML:CharacterString>
									<!-- use layer title as default abstract -->
									<xsl:value-of select="Title"/>
								</smXML:CharacterString>
							</smXML:abstract>
						</xsl:otherwise>
					</xsl:choose>
					<smXML:language>
						<smXML:CharacterString>de</smXML:CharacterString>
					</smXML:language>
					<smXML:topicCategory>
						<!--
							topicCategory is required but there is no way to read its value from a WMS capabilities
							document nor to set a meaningful default
						-->
						<smXML:MD_TopicCategoryCode>environment</smXML:MD_TopicCategoryCode>
					</smXML:topicCategory>
				</smXML:MD_DataIdentification>
			</iso19119:operatesOn>
		</xsl:if>
		<xsl:apply-templates select="Layer"/>
	</xsl:template>
	<xsl:template match="LatLonBoundingBox">
		<iso19119:extent>
			<smXML:EX_Extent>
				<smXML:geographicElement>
					<smXML:EX_GeographicBoundingBox>
						<smXML:westBoundLongitude>
							<smXML:approximateLongitude>
								<xsl:value-of select="format-number(./@minx, '###.##' )"/>
							</smXML:approximateLongitude>
						</smXML:westBoundLongitude>
						<smXML:eastBoundLongitude>
							<smXML:approximateLongitude>
								<xsl:value-of select="format-number(./@maxx, '###.##' )"/>
							</smXML:approximateLongitude>
						</smXML:eastBoundLongitude>
						<smXML:southBoundLatitude>
							<smXML:approximateLatitude>
								<xsl:value-of select="format-number(./@miny, '###.##' )"/>
							</smXML:approximateLatitude>
						</smXML:southBoundLatitude>
						<smXML:northBoundLatitude>
							<smXML:approximateLatitude>
								<xsl:value-of select="format-number(./@maxy, '###.##' )"/>
							</smXML:approximateLatitude>
						</smXML:northBoundLatitude>
					</smXML:EX_GeographicBoundingBox>
				</smXML:geographicElement>
			</smXML:EX_Extent>
		</iso19119:extent>
	</xsl:template>
	<xsl:template match="SRS">
		<smXML:referenceSystemInfo>
			<smXML:MD_ReferenceSystem>
				<smXML:referenceSystemIdentifier>
					<smXML:RS_Identifier>
						<smXML:code>
							<smXML:CharacterString>
								<xsl:value-of select="."/>
							</smXML:CharacterString>
						</smXML:code>
					</smXML:RS_Identifier>
				</smXML:referenceSystemIdentifier>
			</smXML:MD_ReferenceSystem>
		</smXML:referenceSystemInfo>
	</xsl:template>
</xsl:stylesheet>
