-- Drop Foreign Key Constraints 
--ALTER TABLE Datasets DROP CONSTRAINT FK_Datasets_SelfQueryableProperties;
ALTER TABLE IDXTB_CRS DROP CONSTRAINT FK_IDXTB_CRS_IDXTB_MAIN;
ALTER TABLE IDXTB_KEYWORD DROP CONSTRAINT FK_IDXTB_KEYWORD_IDXTB_MAIN;
ALTER TABLE IDXTB_OperatesOnData DROP CONSTRAINT FK_IDXTB_OperatesOnData_IDXTB_MAIN;
ALTER TABLE IDXTB_Constraint DROP CONSTRAINT FK_IDXTB_Constraint_IDXTB_MAIN;

-- Drop Tables, Stored Procedures and Views
DROP TABLE IDXTB_MAIN;
DROP TABLE IDXTB_CRS;
DROP TABLE IDXTB_KEYWORD;
DROP TABLE IDXTB_OperatesOnData;
DROP TABLE IDXTB_Constraint;