DROP TABLE harvestsource CASCADE CONSTRAINT PURGE;
DROP TABLE jt_source_responsehandler CASCADE CONSTRAINT PURGE;
DROP TABLE metadatacache CASCADE CONSTRAINT PURGE;
DROP TABLE responsehandler CASCADE CONSTRAINT PURGE;

DROP SEQUENCE harvestsource_ID_SEQ;
DROP SEQUENCE metadatacache_ID_SEQ;
DROP SEQUENCE responsehandler_ID_SEQ;