DELETE FROM SEC_JT_GROUPS_GROUPS;
DELETE FROM SEC_JT_GROUPS_ROLES;
DELETE FROM SEC_JT_ROLES_PRIVILEGES;
DELETE FROM SEC_JT_ROLES_SECOBJECTS;
DELETE FROM SEC_JT_USERS_GROUPS;
DELETE FROM SEC_JT_USERS_ROLES;
DELETE FROM SEC_PRIVILEGES;
DELETE FROM SEC_ROLES;
DELETE FROM SEC_USERS;
DELETE FROM SEC_GROUPS;
DELETE FROM SEC_SECURED_OBJECT_TYPES;
DELETE FROM SEC_SECURED_OBJECTS;
DELETE FROM SEC_SECURABLE_OBJECTS;

INSERT INTO SEC_PRIVILEGES (ID, NAME) VALUES (1, 'write');
INSERT INTO SEC_PRIVILEGES (ID, NAME) VALUES (2, 'adduser');
INSERT INTO SEC_PRIVILEGES (ID, NAME) VALUES (3, 'addgroup');
INSERT INTO SEC_PRIVILEGES (ID, NAME) VALUES (4, 'addrole');
INSERT INTO SEC_PRIVILEGES (ID, NAME) VALUES (5, 'addobject');

INSERT INTO SEC_SECURABLE_OBJECTS (ID, NAME, TITLE) VALUES (1, 'SEC_ADMIN', 'Security Admin User');
INSERT INTO SEC_USERS (ID, PASSWORD, FIRSTNAME, LASTNAME, EMAIL) VALUES (1, 'JOSE67', 'SEC_ADMIN', 'SEC_ADMIN', NULL);

INSERT INTO SEC_SECURABLE_OBJECTS (ID, NAME, TITLE) VALUES (2, 'SEC_ADMIN', 'Security Admin Group');
INSERT INTO SEC_GROUPS (ID) VALUES (2);

INSERT INTO SEC_SECURABLE_OBJECTS (ID, NAME, TITLE) VALUES (3, 'SEC_ADMIN', 'Security Admin Role');
INSERT INTO SEC_ROLES (ID) VALUES (3);

INSERT INTO SEC_JT_GROUPS_ROLES (FK_GROUPS, FK_ROLES) VALUES (2, 3);
INSERT INTO SEC_JT_ROLES_PRIVILEGES (FK_ROLES, FK_PRIVILEGES) VALUES (3, 1);
INSERT INTO SEC_JT_ROLES_PRIVILEGES (FK_ROLES, FK_PRIVILEGES) VALUES (3, 2);
INSERT INTO SEC_JT_ROLES_PRIVILEGES (FK_ROLES, FK_PRIVILEGES) VALUES (3, 3);
INSERT INTO SEC_JT_ROLES_PRIVILEGES (FK_ROLES, FK_PRIVILEGES) VALUES (3, 4);
INSERT INTO SEC_JT_ROLES_PRIVILEGES (FK_ROLES, FK_PRIVILEGES) VALUES (3, 5);

INSERT INTO SEC_JT_ROLES_SECOBJECTS (FK_ROLES, FK_SECURABLE_OBJECTS, FK_RIGHTS) VALUES (3, 2, 8);
INSERT INTO SEC_JT_USERS_GROUPS (FK_USERS, FK_GROUPS) VALUES (1, 2);

