/*----------------------------------------------------------------------------
 This file is part of deegree, http://deegree.org/
 Copyright (C) 2001-2009 by:
   Department of Geography, University of Bonn
 and
   lat/lon GmbH

 This library is free software; you can redistribute it and/or modify it under
 the terms of the GNU Lesser General Public License as published by the Free
 Software Foundation; either version 2.1 of the License, or (at your option)
 any later version.
 This library is distributed in the hope that it will be useful, but WITHOUT
 ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 details.
 You should have received a copy of the GNU Lesser General Public License
 along with this library; if not, write to the Free Software Foundation, Inc.,
 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA

 Contact information:

 lat/lon GmbH
 Aennchenstr. 19, 53177 Bonn
 Germany
 http://lat-lon.de/

 Department of Geography, University of Bonn
 Prof. Dr. Klaus Greve
 Postfach 1147, 53001 Bonn
 Germany
 http://www.geographie.uni-bonn.de/deegree/

 e-mail: info@deegree.org
----------------------------------------------------------------------------*/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2009.06.02 at 06:08:37 PM MESZ
//


package org.deegree.feature.types.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;
import javax.xml.namespace.QName;


/**
 * Declaration of a feature type of the schema.
 *
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.deegree.org/feature/featuretype}AbstractProperty" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}QName" />
 *       &lt;attribute name="javaClass" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "abstractProperty"
})
public class FeatureTypeDecl {

    @XmlElementRef(name = "AbstractProperty", namespace = "http://www.deegree.org/feature/featuretype", type = JAXBElement.class)
    protected List<JAXBElement<? extends AbstractPropertyDecl>> abstractProperty;
    @XmlAttribute
    protected QName name;
    @XmlAttribute
    protected String javaClass;

    /**
     * Gets the value of the abstractProperty property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the abstractProperty property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAbstractProperty().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link AbstractPropertyDecl }{@code >}
     * {@link CustomComplexPropertyDecl }
     * {@link JAXBElement }{@code <}{@link SimplePropertyDecl }{@code >}
     * {@link JAXBElement }{@code <}{@link FeaturePropertyDecl }{@code >}
     * {@link JAXBElement }{@code <}{@link GeometryPropertyDecl }{@code >}
     *
     *
     */
    public List<JAXBElement<? extends AbstractPropertyDecl>> getAbstractProperty() {
        if (abstractProperty == null) {
            abstractProperty = new ArrayList<JAXBElement<? extends AbstractPropertyDecl>>();
        }
        return this.abstractProperty;
    }

    /**
     * Gets the value of the name property.
     *
     * @return
     *     possible object is
     *     {@link QName }
     *
     */
    public QName getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     *
     * @param value
     *     allowed object is
     *     {@link QName }
     *
     */
    public void setName(QName value) {
        this.name = value;
    }

    /**
     * Gets the value of the javaClass property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getJavaClass() {
        return javaClass;
    }

    /**
     * Sets the value of the javaClass property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setJavaClass(String value) {
        this.javaClass = value;
    }

}
