//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.10.06 at 05:10:14 PM MESZ 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.deegree.org/feature/featuretype", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.deegree.feature.types.jaxb;
