/*----------------------------------------------------------------------------
 This file is part of deegree, http://deegree.org/
 Copyright (C) 2001-2009 by:
   Department of Geography, University of Bonn
 and
   lat/lon GmbH

 This library is free software; you can redistribute it and/or modify it under
 the terms of the GNU Lesser General Public License as published by the Free
 Software Foundation; either version 2.1 of the License, or (at your option)
 any later version.
 This library is distributed in the hope that it will be useful, but WITHOUT
 ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 details.
 You should have received a copy of the GNU Lesser General Public License
 along with this library; if not, write to the Free Software Foundation, Inc.,
 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA

 Contact information:

 lat/lon GmbH
 Aennchenstr. 19, 53177 Bonn
 Germany
 http://lat-lon.de/

 Department of Geography, University of Bonn
 Prof. Dr. Klaus Greve
 Postfach 1147, 53001 Bonn
 Germany
 http://www.geographie.uni-bonn.de/deegree/

 e-mail: info@deegree.org
----------------------------------------------------------------------------*/
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2009.06.02 at 06:08:37 PM MESZ
//


package org.deegree.feature.types.jaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PrimitiveType.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="PrimitiveType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="string"/>
 *     &lt;enumeration value="boolean"/>
 *     &lt;enumeration value="integer"/>
 *     &lt;enumeration value="decimal"/>
 *     &lt;enumeration value="float"/>
 *     &lt;enumeration value="date"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 *
 */
@XmlType(name = "PrimitiveType")
@XmlEnum
public enum PrimitiveType {


    /**
     * String-valued property
     *
     */
    @XmlEnumValue("string")
    STRING("string"),

    /**
     * Boolean-valued property
     *
     */
    @XmlEnumValue("boolean")
    BOOLEAN("boolean"),

    /**
     * Integer-valued property
     *
     */
    @XmlEnumValue("integer")
    INTEGER("integer"),

    /**
     * Decimal-valued property
     *
     */
    @XmlEnumValue("decimal")
    DECIMAL("decimal"),

    /**
     * Float-valued property
     *
     */
    @XmlEnumValue("float")
    FLOAT("float"),

    /**
     * Decimal-valued property
     *
     */
    @XmlEnumValue("date")
    DATE("date");
    private final String value;

    PrimitiveType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static PrimitiveType fromValue(String v) {
        for (PrimitiveType c: PrimitiveType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
