//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.03.22 at 10:25:52 AM MEZ 
//


package org.deegree.services.controller.configuration;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DCPType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DCPType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="HTTPGet" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *         &lt;element name="HTTPPost" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *         &lt;element name="SOAP" type="{http://www.w3.org/2001/XMLSchema}anyURI" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DCPType", propOrder = {
    "httpGet",
    "httpPost",
    "soap"
})
public class DCPType {

    @XmlElement(name = "HTTPGet")
    @XmlSchemaType(name = "anyURI")
    protected String httpGet;
    @XmlElement(name = "HTTPPost")
    @XmlSchemaType(name = "anyURI")
    protected String httpPost;
    @XmlElement(name = "SOAP")
    @XmlSchemaType(name = "anyURI")
    protected String soap;

    /**
     * Gets the value of the httpGet property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHTTPGet() {
        return httpGet;
    }

    /**
     * Sets the value of the httpGet property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHTTPGet(String value) {
        this.httpGet = value;
    }

    /**
     * Gets the value of the httpPost property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHTTPPost() {
        return httpPost;
    }

    /**
     * Sets the value of the httpPost property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHTTPPost(String value) {
        this.httpPost = value;
    }

    /**
     * Gets the value of the soap property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSOAP() {
        return soap;
    }

    /**
     * Sets the value of the soap property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSOAP(String value) {
        this.soap = value;
    }

}
