//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.03.22 at 10:25:52 AM MEZ 
//


package org.deegree.services.controller.configuration;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.deegree.services.controller.configuration package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ServiceIdentification_QNAME = new QName("http://www.deegree.org/webservices", "ServiceIdentification");
    private final static QName _ServiceProvider_QNAME = new QName("http://www.deegree.org/webservices", "ServiceProvider");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.deegree.services.controller.configuration
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AddressType }
     * 
     */
    public AddressType createAddressType() {
        return new AddressType();
    }

    /**
     * Create an instance of {@link ServiceType }
     * 
     */
    public ServiceType createServiceType() {
        return new ServiceType();
    }

    /**
     * Create an instance of {@link ServiceProviderType }
     * 
     */
    public ServiceProviderType createServiceProviderType() {
        return new ServiceProviderType();
    }

    /**
     * Create an instance of {@link DCPType }
     * 
     */
    public DCPType createDCPType() {
        return new DCPType();
    }

    /**
     * Create an instance of {@link ConfiguredServicesType }
     * 
     */
    public ConfiguredServicesType createConfiguredServicesType() {
        return new ConfiguredServicesType();
    }

    /**
     * Create an instance of {@link ServiceIdentificationType }
     * 
     */
    public ServiceIdentificationType createServiceIdentificationType() {
        return new ServiceIdentificationType();
    }

    /**
     * Create an instance of {@link AuthenticationMethodType }
     * 
     */
    public AuthenticationMethodType createAuthenticationMethodType() {
        return new AuthenticationMethodType();
    }

    /**
     * Create an instance of {@link DeegreeServicesMetadata }
     * 
     */
    public DeegreeServicesMetadata createDeegreeServicesMetadata() {
        return new DeegreeServicesMetadata();
    }

    /**
     * Create an instance of {@link ServiceContactType }
     * 
     */
    public ServiceContactType createServiceContactType() {
        return new ServiceContactType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ServiceIdentificationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.deegree.org/webservices", name = "ServiceIdentification")
    public JAXBElement<ServiceIdentificationType> createServiceIdentification(ServiceIdentificationType value) {
        return new JAXBElement<ServiceIdentificationType>(_ServiceIdentification_QNAME, ServiceIdentificationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ServiceProviderType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.deegree.org/webservices", name = "ServiceProvider")
    public JAXBElement<ServiceProviderType> createServiceProvider(ServiceProviderType value) {
        return new JAXBElement<ServiceProviderType>(_ServiceProvider_QNAME, ServiceProviderType.class, null, value);
    }

}
