ALTER TABLE IDXTB_CRS DROP CONSTRAINT FK_IDXTB_CRS_IDXTB_MAIN;
ALTER TABLE IDXTB_KEYWORD DROP CONSTRAINT FK_IDXTB_KEYWORD_IDXTB_MAIN;
ALTER TABLE IDXTB_OperatesOnData DROP CONSTRAINT FK_IDXTB_OpOnData_IDXTB_MAIN;
ALTER TABLE IDXTB_Constraint DROP CONSTRAINT FK_IDXTB_Constraint_IDXTB_MAIN;


DROP TABLE IDXTB_MAIN CASCADE CONSTRAINTS PURGE;
DROP TABLE IDXTB_CRS CASCADE CONSTRAINTS PURGE;
DROP TABLE IDXTB_KEYWORD CASCADE CONSTRAINTS PURGE;
DROP TABLE IDXTB_OperatesOnData CASCADE CONSTRAINTS PURGE;
DROP TABLE IDXTB_Constraint CASCADE CONSTRAINTS PURGE;