//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.02.19 at 03:46:10 PM MEZ 
//


package org.deegree.services.wpvs.configuration;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.deegree.org/services/wpvs}AbstractFeatureDatasetType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.deegree.org/services/wpvs}SwitchLevels"/>
 *         &lt;element ref="{http://www.deegree.org/services/wpvs}Buildings" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "switchLevels",
    "buildings"
})
@XmlRootElement(name = "Buildings")
public class Buildings
    extends AbstractFeatureDatasetType
{

    @XmlElement(name = "SwitchLevels", required = true)
    protected SwitchLevels switchLevels;
    @XmlElement(name = "Buildings")
    protected List<Buildings> buildings;

    /**
     * Gets the value of the switchLevels property.
     * 
     * @return
     *     possible object is
     *     {@link SwitchLevels }
     *     
     */
    public SwitchLevels getSwitchLevels() {
        return switchLevels;
    }

    /**
     * Sets the value of the switchLevels property.
     * 
     * @param value
     *     allowed object is
     *     {@link SwitchLevels }
     *     
     */
    public void setSwitchLevels(SwitchLevels value) {
        this.switchLevels = value;
    }

    /**
     * Gets the value of the buildings property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the buildings property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBuildings().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Buildings }
     * 
     * 
     */
    public List<Buildings> getBuildings() {
        if (buildings == null) {
            buildings = new ArrayList<Buildings>();
        }
        return this.buildings;
    }

}
