//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.02.19 at 03:46:10 PM MEZ 
//


package org.deegree.services.wpvs.configuration;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.deegree.org/services/wpvs}AbstractDataType">
 *       &lt;sequence>
 *         &lt;element name="MinColor" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="MaxColor" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="HeightISOColor" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="MinZValue" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="MaxZValue" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "minColor",
    "maxColor",
    "heightISOColor",
    "minZValue",
    "maxZValue"
})
@XmlRootElement(name = "ColormapDataset")
public class ColormapDataset
    extends AbstractDataType
{

    @XmlElement(name = "MinColor")
    protected String minColor;
    @XmlElement(name = "MaxColor")
    protected String maxColor;
    @XmlElement(name = "HeightISOColor")
    protected String heightISOColor;
    @XmlElement(name = "MinZValue")
    protected Double minZValue;
    @XmlElement(name = "MaxZValue")
    protected Double maxZValue;

    /**
     * Gets the value of the minColor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMinColor() {
        return minColor;
    }

    /**
     * Sets the value of the minColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMinColor(String value) {
        this.minColor = value;
    }

    /**
     * Gets the value of the maxColor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaxColor() {
        return maxColor;
    }

    /**
     * Sets the value of the maxColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaxColor(String value) {
        this.maxColor = value;
    }

    /**
     * Gets the value of the heightISOColor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHeightISOColor() {
        return heightISOColor;
    }

    /**
     * Sets the value of the heightISOColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHeightISOColor(String value) {
        this.heightISOColor = value;
    }

    /**
     * Gets the value of the minZValue property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getMinZValue() {
        return minZValue;
    }

    /**
     * Sets the value of the minZValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setMinZValue(Double value) {
        this.minZValue = value;
    }

    /**
     * Gets the value of the maxZValue property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getMaxZValue() {
        return maxZValue;
    }

    /**
     * Sets the value of the maxZValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setMaxZValue(Double value) {
        this.maxZValue = value;
    }

}
