//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.02.19 at 03:46:10 PM MEZ 
//


package org.deegree.services.wpvs.configuration;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import org.deegree.commons.configuration.KeywordsType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Title" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="MetadataURL" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Abstract" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element ref="{http://www.deegree.org/commons}Keywords" minOccurs="0"/>
 *         &lt;element name="BaseCRS" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element ref="{http://www.deegree.org/services/wpvs}TranslationToLocalCRS"/>
 *         &lt;element name="MaxPixelError" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element ref="{http://www.deegree.org/services/wpvs}ElevationDataset"/>
 *         &lt;element ref="{http://www.deegree.org/services/wpvs}DEMTextureDataset" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.deegree.org/services/wpvs}ColormapDataset" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;sequence>
 *           &lt;element ref="{http://www.deegree.org/services/wpvs}Buildings" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element ref="{http://www.deegree.org/services/wpvs}Trees" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;/sequence>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "title",
    "metadataURL",
    "_abstract",
    "keywords",
    "baseCRS",
    "translationToLocalCRS",
    "maxPixelError",
    "elevationDataset",
    "demTextureDataset",
    "colormapDataset",
    "buildings",
    "trees"
})
@XmlRootElement(name = "DatasetDefinitions")
public class DatasetDefinitions {

    @XmlElement(name = "Title", required = true)
    protected String title;
    @XmlElement(name = "MetadataURL")
    protected List<String> metadataURL;
    @XmlElement(name = "Abstract")
    protected String _abstract;
    @XmlElement(name = "Keywords", namespace = "http://www.deegree.org/commons")
    protected KeywordsType keywords;
    @XmlElement(name = "BaseCRS", required = true)
    protected String baseCRS;
    @XmlElement(name = "TranslationToLocalCRS", required = true)
    protected TranslationToLocalCRS translationToLocalCRS;
    @XmlElement(name = "MaxPixelError", defaultValue = "5.0")
    protected Double maxPixelError;
    @XmlElement(name = "ElevationDataset", required = true)
    protected ElevationDataset elevationDataset;
    @XmlElement(name = "DEMTextureDataset")
    protected List<DEMTextureDataset> demTextureDataset;
    @XmlElement(name = "ColormapDataset")
    protected List<ColormapDataset> colormapDataset;
    @XmlElement(name = "Buildings")
    protected List<Buildings> buildings;
    @XmlElement(name = "Trees")
    protected List<Trees> trees;

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the metadataURL property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the metadataURL property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMetadataURL().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getMetadataURL() {
        if (metadataURL == null) {
            metadataURL = new ArrayList<String>();
        }
        return this.metadataURL;
    }

    /**
     * Gets the value of the abstract property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAbstract() {
        return _abstract;
    }

    /**
     * Sets the value of the abstract property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAbstract(String value) {
        this._abstract = value;
    }

    /**
     * Gets the value of the keywords property.
     * 
     * @return
     *     possible object is
     *     {@link KeywordsType }
     *     
     */
    public KeywordsType getKeywords() {
        return keywords;
    }

    /**
     * Sets the value of the keywords property.
     * 
     * @param value
     *     allowed object is
     *     {@link KeywordsType }
     *     
     */
    public void setKeywords(KeywordsType value) {
        this.keywords = value;
    }

    /**
     * Gets the value of the baseCRS property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBaseCRS() {
        return baseCRS;
    }

    /**
     * Sets the value of the baseCRS property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBaseCRS(String value) {
        this.baseCRS = value;
    }

    /**
     * Gets the value of the translationToLocalCRS property.
     * 
     * @return
     *     possible object is
     *     {@link TranslationToLocalCRS }
     *     
     */
    public TranslationToLocalCRS getTranslationToLocalCRS() {
        return translationToLocalCRS;
    }

    /**
     * Sets the value of the translationToLocalCRS property.
     * 
     * @param value
     *     allowed object is
     *     {@link TranslationToLocalCRS }
     *     
     */
    public void setTranslationToLocalCRS(TranslationToLocalCRS value) {
        this.translationToLocalCRS = value;
    }

    /**
     * Gets the value of the maxPixelError property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getMaxPixelError() {
        return maxPixelError;
    }

    /**
     * Sets the value of the maxPixelError property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setMaxPixelError(Double value) {
        this.maxPixelError = value;
    }

    /**
     * Gets the value of the elevationDataset property.
     * 
     * @return
     *     possible object is
     *     {@link ElevationDataset }
     *     
     */
    public ElevationDataset getElevationDataset() {
        return elevationDataset;
    }

    /**
     * Sets the value of the elevationDataset property.
     * 
     * @param value
     *     allowed object is
     *     {@link ElevationDataset }
     *     
     */
    public void setElevationDataset(ElevationDataset value) {
        this.elevationDataset = value;
    }

    /**
     * Gets the value of the demTextureDataset property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the demTextureDataset property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDEMTextureDataset().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DEMTextureDataset }
     * 
     * 
     */
    public List<DEMTextureDataset> getDEMTextureDataset() {
        if (demTextureDataset == null) {
            demTextureDataset = new ArrayList<DEMTextureDataset>();
        }
        return this.demTextureDataset;
    }

    /**
     * Gets the value of the colormapDataset property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the colormapDataset property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getColormapDataset().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ColormapDataset }
     * 
     * 
     */
    public List<ColormapDataset> getColormapDataset() {
        if (colormapDataset == null) {
            colormapDataset = new ArrayList<ColormapDataset>();
        }
        return this.colormapDataset;
    }

    /**
     * Gets the value of the buildings property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the buildings property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBuildings().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Buildings }
     * 
     * 
     */
    public List<Buildings> getBuildings() {
        if (buildings == null) {
            buildings = new ArrayList<Buildings>();
        }
        return this.buildings;
    }

    /**
     * Gets the value of the trees property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the trees property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTrees().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Trees }
     * 
     * 
     */
    public List<Trees> getTrees() {
        if (trees == null) {
            trees = new ArrayList<Trees>();
        }
        return this.trees;
    }

}
