//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.02.19 at 03:46:10 PM MEZ 
//


package org.deegree.services.wpvs.configuration;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import org.deegree.commons.datasource.configuration.AbstractGeospatialDataSourceType;
import org.deegree.commons.datasource.configuration.MultiResolutionDataSource;
import org.deegree.commons.datasource.configuration.RasterDataSource;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.deegree.org/services/wpvs}AbstractDataType">
 *       &lt;sequence>
 *         &lt;element name="MaxPixelError" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="MaxProjectedTexelSize" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;group ref="{http://www.deegree.org/services/wpvs}TextureProviders"/>
 *       &lt;/sequence>
 *       &lt;attribute name="RequestTimeout" type="{http://www.w3.org/2001/XMLSchema}int" default="30" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "maxPixelError",
    "maxProjectedTexelSize",
    "abstractRasterDataSource",
    "styledGeometryProvider"
})
@XmlRootElement(name = "DEMTextureDataset")
public class DEMTextureDataset
    extends AbstractDataType
{

    @XmlElement(name = "MaxPixelError", defaultValue = "5.0")
    protected Double maxPixelError;
    @XmlElement(name = "MaxProjectedTexelSize", defaultValue = "5.0")
    protected Double maxProjectedTexelSize;
    @XmlElementRef(name = "AbstractRasterDataSource", namespace = "http://www.deegree.org/datasource", type = JAXBElement.class)
    protected JAXBElement<? extends AbstractGeospatialDataSourceType> abstractRasterDataSource;
    @XmlElement(name = "StyledGeometryProvider")
    protected StyledGeometryProvider styledGeometryProvider;
    @XmlAttribute(name = "RequestTimeout")
    protected Integer requestTimeout;

    /**
     * Gets the value of the maxPixelError property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getMaxPixelError() {
        return maxPixelError;
    }

    /**
     * Sets the value of the maxPixelError property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setMaxPixelError(Double value) {
        this.maxPixelError = value;
    }

    /**
     * Gets the value of the maxProjectedTexelSize property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getMaxProjectedTexelSize() {
        return maxProjectedTexelSize;
    }

    /**
     * Sets the value of the maxProjectedTexelSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setMaxProjectedTexelSize(Double value) {
        this.maxProjectedTexelSize = value;
    }

    /**
     * Gets the value of the abstractRasterDataSource property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link RasterDataSource }{@code >}
     *     {@link JAXBElement }{@code <}{@link AbstractGeospatialDataSourceType }{@code >}
     *     {@link JAXBElement }{@code <}{@link MultiResolutionDataSource }{@code >}
     *     
     */
    public JAXBElement<? extends AbstractGeospatialDataSourceType> getAbstractRasterDataSource() {
        return abstractRasterDataSource;
    }

    /**
     * Sets the value of the abstractRasterDataSource property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link RasterDataSource }{@code >}
     *     {@link JAXBElement }{@code <}{@link AbstractGeospatialDataSourceType }{@code >}
     *     {@link JAXBElement }{@code <}{@link MultiResolutionDataSource }{@code >}
     *     
     */
    public void setAbstractRasterDataSource(JAXBElement<? extends AbstractGeospatialDataSourceType> value) {
        this.abstractRasterDataSource = ((JAXBElement<? extends AbstractGeospatialDataSourceType> ) value);
    }

    /**
     * Gets the value of the styledGeometryProvider property.
     * 
     * @return
     *     possible object is
     *     {@link StyledGeometryProvider }
     *     
     */
    public StyledGeometryProvider getStyledGeometryProvider() {
        return styledGeometryProvider;
    }

    /**
     * Sets the value of the styledGeometryProvider property.
     * 
     * @param value
     *     allowed object is
     *     {@link StyledGeometryProvider }
     *     
     */
    public void setStyledGeometryProvider(StyledGeometryProvider value) {
        this.styledGeometryProvider = value;
    }

    /**
     * Gets the value of the requestTimeout property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getRequestTimeout() {
        if (requestTimeout == null) {
            return  30;
        } else {
            return requestTimeout;
        }
    }

    /**
     * Sets the value of the requestTimeout property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setRequestTimeout(Integer value) {
        this.requestTimeout = value;
    }

}
