//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.02.19 at 03:46:10 PM MEZ 
//


package org.deegree.services.wpvs.configuration;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import org.deegree.commons.datasource.configuration.ElevationModelDataSource;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.deegree.org/services/wpvs}AbstractDataType">
 *       &lt;sequence>
 *         &lt;element name="MaxPixelError" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element ref="{http://www.deegree.org/datasource}ElevationModelDataSource"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "maxPixelError",
    "elevationModelDataSource"
})
@XmlRootElement(name = "ElevationDataset")
public class ElevationDataset
    extends AbstractDataType
{

    @XmlElement(name = "MaxPixelError", defaultValue = "5.0")
    protected Double maxPixelError;
    @XmlElement(name = "ElevationModelDataSource", namespace = "http://www.deegree.org/datasource", required = true)
    protected ElevationModelDataSource elevationModelDataSource;

    /**
     * Gets the value of the maxPixelError property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getMaxPixelError() {
        return maxPixelError;
    }

    /**
     * Sets the value of the maxPixelError property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setMaxPixelError(Double value) {
        this.maxPixelError = value;
    }

    /**
     * Gets the value of the elevationModelDataSource property.
     * 
     * @return
     *     possible object is
     *     {@link ElevationModelDataSource }
     *     
     */
    public ElevationModelDataSource getElevationModelDataSource() {
        return elevationModelDataSource;
    }

    /**
     * Sets the value of the elevationModelDataSource property.
     * 
     * @param value
     *     allowed object is
     *     {@link ElevationModelDataSource }
     *     
     */
    public void setElevationModelDataSource(ElevationModelDataSource value) {
        this.elevationModelDataSource = value;
    }

}
