--  -------------------------------------------------- 
--  Generated by Enterprise Architect Version 7.1.834
--  Created On : Dienstag, 22 September, 2009 
--  DBMS       : PostgreSQL 
--  -------------------------------------------------- 


-- Drop Foreign Key Constraints 
ALTER TABLE Datasets DROP CONSTRAINT FK_Datasets_SelfQueryableProperties;
ALTER TABLE ISOQP_Abstract DROP CONSTRAINT FK_ISOQP_Abstract_Datasets;
ALTER TABLE ISOQP_AlternateTitle DROP CONSTRAINT FK_ISOQP_AlternateTitle_Datasets;
ALTER TABLE ISOQP_BoundingBox DROP CONSTRAINT FK_ISOQP_BoundingBox_Datasets;
ALTER TABLE ISOQP_CouplingType DROP CONSTRAINT FK_ISOQP_CouplingType_Datasets;
ALTER TABLE ISOQP_CreationDate DROP CONSTRAINT FK_ISOQP_CreationDate_Datasets;
ALTER TABLE ISOQP_CRS DROP CONSTRAINT FK_ISOQP_CRS_Datasets;
ALTER TABLE ISOQP_Format DROP CONSTRAINT FK_ISOQP_Format_Datasets;
ALTER TABLE ISOQP_GeographicDescriptionCode DROP CONSTRAINT FK_ISOQP_GeographicDescriptionCode_Datasets;
ALTER TABLE ISOQP_Keyword DROP CONSTRAINT FK_ISOQP_KeywordType_Datasets;
ALTER TABLE ISOQP_OperatesOnData DROP CONSTRAINT FK_ISOQP_OperatesOnData_Datasets;
ALTER TABLE ISOQP_Operation DROP CONSTRAINT FK_ISOQP_Operation_Datasets;
ALTER TABLE ISOQP_OrganisationName DROP CONSTRAINT FK_ISOQP_OrganisationName_Datasets;
ALTER TABLE ISOQP_PublicationDate DROP CONSTRAINT FK_ISOQP_PublicationDate_Datasets;
ALTER TABLE ISOQP_ResourceIdentifier DROP CONSTRAINT FK_ISOQP_ResourceIdentifier_Datasets;
ALTER TABLE ISOQP_ResourceLanguage DROP CONSTRAINT FK_ISOQP_ResourceLanguage_Datasets;
ALTER TABLE ISOQP_RevisionDate DROP CONSTRAINT FK_ISOQP_RevisionDate_Datasets;
ALTER TABLE ISOQP_ServiceType DROP CONSTRAINT FK_ISOQP_ServiceType_Datasets;
ALTER TABLE ISOQP_ServiceTypeVersion DROP CONSTRAINT FK_ISOQP_ServiceTypeVersion_Datasets;
ALTER TABLE ISOQP_SpatialResolution DROP CONSTRAINT FK_ISOQP_SpatialResolution_Datasets;
ALTER TABLE ISOQP_TemporalExtent DROP CONSTRAINT FK_ISOQP_TemporalExtent_Datasets;
ALTER TABLE ISOQP_Title DROP CONSTRAINT FK_ISOQP_Title_Datasets;
ALTER TABLE ISOQP_TopicCategory DROP CONSTRAINT FK_ISOQP_TopicCategory_Datasets;
ALTER TABLE ISOQP_Type DROP CONSTRAINT FK_ISOQP_Type_Datasets;
ALTER TABLE RecordFull DROP CONSTRAINT fk_recordfull_datasets;
ALTER TABLE RecordBrief DROP CONSTRAINT fk_recordbrief_datasets;
ALTER TABLE RecordSummary DROP CONSTRAINT fk_recordsummary_datasets;
ALTER TABLE DCQP_RIGHTS DROP CONSTRAINT FK_DCQP_RIGHTS_Datasets;

-- Drop Tables, Stored Procedures and Views 
DROP TABLE Datasets;
DROP TABLE ISOQP_Abstract;
DROP TABLE ISOQP_AlternateTitle;
DROP TABLE ISOQP_BoundingBox;
DROP TABLE ISOQP_CouplingType;
DROP TABLE ISOQP_CreationDate;
DROP TABLE ISOQP_CRS;
DROP TABLE ISOQP_Format;
DROP TABLE ISOQP_GeographicDescriptionCode;
DROP TABLE ISOQP_Keyword;
DROP TABLE ISOQP_OperatesOnData;
DROP TABLE ISOQP_Operation;
DROP TABLE ISOQP_OrganisationName;
DROP TABLE ISOQP_PublicationDate;
DROP TABLE ISOQP_ResourceIdentifier;
DROP TABLE ISOQP_ResourceLanguage;
DROP TABLE ISOQP_RevisionDate;
DROP TABLE ISOQP_ServiceType;
DROP TABLE ISOQP_ServiceTypeVersion;
DROP TABLE ISOQP_SpatialResolution;
DROP TABLE ISOQP_TemporalExtent;
DROP TABLE ISOQP_Title;
DROP TABLE ISOQP_TopicCategory;
DROP TABLE ISOQP_Type;
DROP TABLE RecordBrief;
DROP TABLE RecordSummary;
DROP TABLE RecordFull;
DROP TABLE UserDefinedQueryableProperties;
--DROP TABLE DCQP_RIGHTS;



-- Create Tables 
CREATE TABLE Datasets ( 
	ID integer NOT NULL,
	version integer,    -- version of the record 
	status numeric(1),
	AnyText text,    -- common queryable property (ISO AP 1.0): Whole resource text. 
	Identifier varchar(50) NOT NULL,    -- common queryable property (ISO AP 1.0): MD_Metadata.fileIdentifier 
	Modified timestamp,    -- common queryable property (ISO AP 1.0): MD_Metadata.dateStamp .Date 
	HasSecurityConstraints boolean,    -- additional queryable property (ISO AP 1.0): MD_Metadata.AbstractMD_Identification.resourceConstraints.MD_securityConstraints (If an instance of the class MD_SecurityConstraint exists for a resource, the "HasSecurityConstraints" is "true", otherwise "false") 
	Language varchar(50),    -- additional queryable property (ISO AP 1.0): MD_Metadata.language 
	ParentIdentifier varchar(50)    -- additional queryable property (ISO AP 1.0): MD_Metadata.parentIdentifier 
);
COMMENT ON COLUMN Datasets.version
    IS 'version of the record';
COMMENT ON COLUMN Datasets.AnyText
    IS 'common queryable property (ISO AP 1.0): Whole resource text.';
COMMENT ON COLUMN Datasets.Identifier
    IS 'common queryable property (ISO AP 1.0): MD_Metadata.fileIdentifier';
COMMENT ON COLUMN Datasets.Modified
    IS 'common queryable property (ISO AP 1.0): MD_Metadata.dateStamp .Date';
COMMENT ON COLUMN Datasets.HasSecurityConstraints
    IS 'additional queryable property (ISO AP 1.0): MD_Metadata.AbstractMD_Identification.resourceConstraints.MD_securityConstraints (If an instance of the class MD_SecurityConstraint exists for a resource, the "HasSecurityConstraints" is "true", otherwise "false")';
COMMENT ON COLUMN Datasets.Language
    IS 'additional queryable property (ISO AP 1.0): MD_Metadata.language';
COMMENT ON COLUMN Datasets.ParentIdentifier
    IS 'additional queryable property (ISO AP 1.0): MD_Metadata.parentIdentifier';

CREATE TABLE ISOQP_Abstract ( 
	ID integer NOT NULL,
	fk_datasets integer NOT NULL,
	Abstract varchar(500) NOT NULL    -- MD_Metadata.identificationInfo.AbstractMD_Identification.abstract 
);
COMMENT ON TABLE ISOQP_Abstract
    IS 'common queryable property (ISO AP 1.0)';
COMMENT ON COLUMN ISOQP_Abstract.Abstract
    IS 'MD_Metadata.identificationInfo.AbstractMD_Identification.abstract';

CREATE TABLE ISOQP_AlternateTitle ( 
	ID integer NOT NULL,
	fk_datasets integer NOT NULL,
	AlternateTitle varchar(500) NOT NULL    -- MD_Metadata.identificationInfo.AbstractMD_Identification.citation.CI_Citation.alternateTitle 
);
COMMENT ON TABLE ISOQP_AlternateTitle
    IS 'additional queryable property (ISO AP 1.0)';
COMMENT ON COLUMN ISOQP_AlternateTitle.AlternateTitle
    IS 'MD_Metadata.identificationInfo.AbstractMD_Identification.citation.CI_Citation.alternateTitle';

CREATE TABLE ISOQP_BoundingBox ( 
	ID integer NOT NULL,
	fk_datasets integer NOT NULL
);
COMMENT ON TABLE ISOQP_BoundingBox
    IS 'common queryable property (ISO AP 1.0): MD_Metadata.identificationInfo.MD_DataIdentification.extent.EX_Extent.geographicElement.EX_GeographicBoundingBox.westBoundLongitude,  MD_Metadata.identificationInfo.MD_DataIdentification.extent.EX_Extent.geographicElement.EX_GeographicBoundingBox.southBoundLatitude, MD_Metadata.identificationInfo.MD_DataIdentification.extent.EX_Extent.geographicElement.EX_GeographicBoundingBox.eastBoundLongitude, MD_Metadata.identificationInfo.MD_DataIdentification.extent.EX_Extent.geographicElement.EX_GeographicBoundingBox.northBoundLatitude 
 as BoundingBox';

CREATE TABLE ISOQP_CouplingType ( 
	ID integer NOT NULL,
	fk_datasets integer NOT NULL,
	CouplingType varchar(5) NOT NULL    -- MD_Metadata.identificationInfo.SV_ServiceIdentification.couplingType.SV_CouplingType.code@codeListValue 
);
COMMENT ON TABLE ISOQP_CouplingType
    IS 'additional queryable property (ISO AP 1.0) - service';
COMMENT ON COLUMN ISOQP_CouplingType.CouplingType
    IS 'MD_Metadata.identificationInfo.SV_ServiceIdentification.couplingType.SV_CouplingType.code@codeListValue';

CREATE TABLE ISOQP_CreationDate ( 
	fk_datasets integer NOT NULL,
	CreationDate timestamp NOT NULL,    -- MD_Identification.citation.CI_Citation.date.CI_Date[dateType.CI_DateTypeCode.@codeListValue='creation'].date.Date 
	ID integer NOT NULL
);
COMMENT ON TABLE ISOQP_CreationDate
    IS 'additional queryable property (ISO AP 1.0)';
COMMENT ON COLUMN ISOQP_CreationDate.CreationDate
    IS 'MD_Identification.citation.CI_Citation.date.CI_Date[dateType.CI_DateTypeCode.@codeListValue=''creation''].date.Date';

CREATE TABLE ISOQP_CRS ( 
	ID integer NOT NULL,
	fk_datasets integer NOT NULL,
	Authority varchar(250),    -- MD_Metadata.referenceSystemInfo.MD_ReferenceSystem.referenceSystemIdentifier.RS_Identifier.codeSpace 
	ID_CRS varchar(50),    -- MD_Metadata.referenceSystemInfo.MD_ReferenceSystem.referenceSystemIdentifier.RS_Identifier.code 
	Version varchar(50)    -- MD_Metadata.referenceSystemInfo.MD_ReferenceSystem.referenceSystemIdentifier.RS_Identifier.version 
);
COMMENT ON TABLE ISOQP_CRS
    IS 'common queryable property (ISO AP 1.0)';
COMMENT ON COLUMN ISOQP_CRS.Authority
    IS 'MD_Metadata.referenceSystemInfo.MD_ReferenceSystem.referenceSystemIdentifier.RS_Identifier.codeSpace';
COMMENT ON COLUMN ISOQP_CRS.ID_CRS
    IS 'MD_Metadata.referenceSystemInfo.MD_ReferenceSystem.referenceSystemIdentifier.RS_Identifier.code';
COMMENT ON COLUMN ISOQP_CRS.Version
    IS 'MD_Metadata.referenceSystemInfo.MD_ReferenceSystem.referenceSystemIdentifier.RS_Identifier.version';

CREATE TABLE ISOQP_Format ( 
	ID integer NOT NULL,
	fk_datasets integer NOT NULL,
	Format varchar(500) NOT NULL    -- MD_Metadata.distributionInfo.MD_Distribution.distributionFormat.MD_Format.name 
);
COMMENT ON TABLE ISOQP_Format
    IS 'common queryable property (ISO AP 1.0)';
COMMENT ON COLUMN ISOQP_Format.Format
    IS 'MD_Metadata.distributionInfo.MD_Distribution.distributionFormat.MD_Format.name';

CREATE TABLE ISOQP_GeographicDescriptionCode ( 
	ID integer NOT NULL,
	fk_datasets integer NOT NULL,
	GeographicDescriptionCode varchar(50)    -- dataset, datasetcollection, application: MD_Metadata.identificationInfo.MD_DataIdentification.extent.EX_Extent.geographicElement.EX_GeographicDescription.geographicIdentifier.MD_Identifier.code 
-- service: MD_Metadata.identificationInfo.SV_ServiceIdentification.extent.EX_Extent.geographicElement.EX_GeographicDescription.geographicIdentifier.MD_Identifier.code 
);
COMMENT ON TABLE ISOQP_GeographicDescriptionCode
    IS 'additional queryable property (ISO AP 1.0) - dataset, datasetcollection, application, service';
COMMENT ON COLUMN ISOQP_GeographicDescriptionCode.GeographicDescriptionCode
    IS 'dataset, datasetcollection, application: MD_Metadata.identificationInfo.MD_DataIdentification.extent.EX_Extent.geographicElement.EX_GeographicDescription.geographicIdentifier.MD_Identifier.code 
 service: MD_Metadata.identificationInfo.SV_ServiceIdentification.extent.EX_Extent.geographicElement.EX_GeographicDescription.geographicIdentifier.MD_Identifier.code';

CREATE TABLE ISOQP_Keyword ( 
	ID integer NOT NULL,
	fk_datasets integer NOT NULL,
	KeywordType varchar(50),    -- MD_Metadata.identificationInfo.AbstractMD_Identification.descriptiveKeywords.MD_Keywords.type 
	Keyword varchar(500),    -- MD_Metadata.identificationInfo.AbstractMD_Identification.descriptiveKeywords.MD_Keywords.keyword 
	Thesaurus varchar(500)    -- MD_Metadata.identificationInfo.AbstractMD_Identification.descriptiveKeywords.MD_Keywords.thesaurusName.CI_Citation.title 
);
COMMENT ON TABLE ISOQP_Keyword
    IS 'contains the queryable properties:  KeywordType - additional queryable property (ISO AP 1.0) part of Subject (TopicCategory is missing) - common queryable property (ISO AP 1.0)';
COMMENT ON COLUMN ISOQP_Keyword.KeywordType
    IS 'MD_Metadata.identificationInfo.AbstractMD_Identification.descriptiveKeywords.MD_Keywords.type';
COMMENT ON COLUMN ISOQP_Keyword.Keyword
    IS 'MD_Metadata.identificationInfo.AbstractMD_Identification.descriptiveKeywords.MD_Keywords.keyword';
COMMENT ON COLUMN ISOQP_Keyword.Thesaurus
    IS 'MD_Metadata.identificationInfo.AbstractMD_Identification.descriptiveKeywords.MD_Keywords.thesaurusName.CI_Citation.title';

CREATE TABLE ISOQP_OperatesOnData ( 
	ID integer NOT NULL,
	fk_datasets integer NOT NULL,
	OperatesOn varchar(50),    -- MD_Metadata.identificationInfo.SV_ServiceIdentification.operatesOn.MD_DataIdentification.citation.CI_Citation.identifier 
	OperatesOnIdentifier varchar(50),    -- MD_Metadata.identificationInfo.SV_ServiceIdentification.coupledResource.SV_CoupledResource.identifier 
	OperatesOnName varchar(50)    -- MD_Metadata.identificationInfo.SV_ServiceIdentification.coupledResource.SV_CoupledResource.operationName 
);
COMMENT ON TABLE ISOQP_OperatesOnData
    IS 'additional queryable property (ISO AP 1.0) - service';
COMMENT ON COLUMN ISOQP_OperatesOnData.OperatesOn
    IS 'MD_Metadata.identificationInfo.SV_ServiceIdentification.operatesOn.MD_DataIdentification.citation.CI_Citation.identifier';
COMMENT ON COLUMN ISOQP_OperatesOnData.OperatesOnIdentifier
    IS 'MD_Metadata.identificationInfo.SV_ServiceIdentification.coupledResource.SV_CoupledResource.identifier';
COMMENT ON COLUMN ISOQP_OperatesOnData.OperatesOnName
    IS 'MD_Metadata.identificationInfo.SV_ServiceIdentification.coupledResource.SV_CoupledResource.operationName';

CREATE TABLE ISOQP_Operation ( 
	ID integer NOT NULL,
	fk_datasets integer NOT NULL,
	Operation varchar(50) NOT NULL    -- MD_Metadata.identificationInfo.SV_ServiceIdentification.containsOperations.SV_OperationMetadata.operationName 
);
COMMENT ON TABLE ISOQP_Operation
    IS 'additional queryable property (ISO AP 1.0) - service';
COMMENT ON COLUMN ISOQP_Operation.Operation
    IS 'MD_Metadata.identificationInfo.SV_ServiceIdentification.containsOperations.SV_OperationMetadata.operationName';

CREATE TABLE ISOQP_OrganisationName ( 
	ID integer NOT NULL,
	fk_datasets integer NOT NULL,
	OrganisationName varchar(500) NOT NULL    -- MD_Metadata.identificationInfo.AbstractMD_Identification.pointOfContact.CI_ResponsibleParty.organisationName 
);
COMMENT ON TABLE ISOQP_OrganisationName
    IS 'additional queryable property (ISO AP 1.0)';
COMMENT ON COLUMN ISOQP_OrganisationName.OrganisationName
    IS 'MD_Metadata.identificationInfo.AbstractMD_Identification.pointOfContact.CI_ResponsibleParty.organisationName';

CREATE TABLE ISOQP_PublicationDate ( 
	ID integer NOT NULL,
	fk_datasets integer NOT NULL,
	PublicationDate timestamp NOT NULL    -- MD_Metadata.identificationInfo.AbstractMD_Identification.citation.CI_Citation.date.CI_Date[dateType.CI_DateTypeCode.@codeListValue='publication'].date.Date 
);
COMMENT ON TABLE ISOQP_PublicationDate
    IS 'additional queryable property (ISO AP 1.0)';
COMMENT ON COLUMN ISOQP_PublicationDate.PublicationDate
    IS 'MD_Metadata.identificationInfo.AbstractMD_Identification.citation.CI_Citation.date.CI_Date[dateType.CI_DateTypeCode.@codeListValue=''publication''].date.Date';

CREATE TABLE ISOQP_ResourceIdentifier ( 
	ID integer NOT NULL,
	fk_datasets integer NOT NULL,
	ResourceIdentifier varchar(500) NOT NULL    -- MD_Metadata.identificationInfo.AbstractMD_Identification.citation.CI_Citation.identifier.MD_Identifier.code 
);
COMMENT ON TABLE ISOQP_ResourceIdentifier
    IS 'additional queryable property (ISO AP 1.0)';
COMMENT ON COLUMN ISOQP_ResourceIdentifier.ResourceIdentifier
    IS 'MD_Metadata.identificationInfo.AbstractMD_Identification.citation.CI_Citation.identifier.MD_Identifier.code';

CREATE TABLE ISOQP_ResourceLanguage ( 
	ID integer NOT NULL,
	fk_datasets integer NOT NULL,
	ResourceLanguage varchar(50) NOT NULL    -- MD_Metadata.identificationInfo.MD_DataIdentification.language 
);
COMMENT ON TABLE ISOQP_ResourceLanguage
    IS ' 	1) additional queryable property (ISO AP 1.0) - dataset, datasetcollection, application';
COMMENT ON COLUMN ISOQP_ResourceLanguage.ResourceLanguage
    IS 'MD_Metadata.identificationInfo.MD_DataIdentification.language';

CREATE TABLE ISOQP_RevisionDate ( 
	ID integer NOT NULL,
	fk_datasets integer NOT NULL,
	RevisionDate timestamp NOT NULL    -- MD_Metadata.identificationInfo.AbstractMD_Identification.citation.CI_Citation.date.CI_Date[dateType.CI_DateTypeCode.@codeListValue='revision'].date.Date 
);
COMMENT ON TABLE ISOQP_RevisionDate
    IS 'additional queryable property (ISO AP 1.0)';
COMMENT ON COLUMN ISOQP_RevisionDate.RevisionDate
    IS 'MD_Metadata.identificationInfo.AbstractMD_Identification.citation.CI_Citation.date.CI_Date[dateType.CI_DateTypeCode.@codeListValue=''revision''].date.Date';

CREATE TABLE ISOQP_ServiceType ( 
	ID integer NOT NULL,
	fk_datasets integer NOT NULL,
	ServiceType varchar(50) NOT NULL    -- MD_Metadata.identificationInfo.SV_ServiceIdentification.serviceType 
);
COMMENT ON TABLE ISOQP_ServiceType
    IS 'additional queryable property (ISO AP 1.0) - service';
COMMENT ON COLUMN ISOQP_ServiceType.ServiceType
    IS 'MD_Metadata.identificationInfo.SV_ServiceIdentification.serviceType';

CREATE TABLE ISOQP_ServiceTypeVersion ( 
	ID integer NOT NULL,
	fk_datasets integer NOT NULL,
	ServiceTypeVersion varchar(15) NOT NULL    -- MD_Metadata.identificationInfo.SV_ServiceIdentification.serviceTypeVersion 
);
COMMENT ON TABLE ISOQP_ServiceTypeVersion
    IS 'additional queryable property (ISO AP 1.0) - service';
COMMENT ON COLUMN ISOQP_ServiceTypeVersion.ServiceTypeVersion
    IS 'MD_Metadata.identificationInfo.SV_ServiceIdentification.serviceTypeVersion';

CREATE TABLE ISOQP_SpatialResolution ( 
	ID integer NOT NULL,
	fk_datasets integer NOT NULL,
	Denominator integer,    -- MD_Metadata.identificationInfo.MD_DataIdentification.spatialResolution.MD_Resolution.equivalentScale.MD_RepresentativeFraction.denominator 
	DistanceValue decimal(10,4),    -- MD_Metadata.identificationInfo.MD_DataIdentification.spatialResolution.MD_Resolution.distance.gco:Distance 
	DistanceUOM varchar(50)    -- MD_Metadata.identificationInfo.MD_DataIdentification.spatialResolution.MD_Resolution.distance.gco:Distance@uom 
);
COMMENT ON TABLE ISOQP_SpatialResolution
    IS 'additional queryable property (ISO AP 1.0) - dataset, datasetcollection, application';
COMMENT ON COLUMN ISOQP_SpatialResolution.Denominator
    IS 'MD_Metadata.identificationInfo.MD_DataIdentification.spatialResolution.MD_Resolution.equivalentScale.MD_RepresentativeFraction.denominator';
COMMENT ON COLUMN ISOQP_SpatialResolution.DistanceValue
    IS 'MD_Metadata.identificationInfo.MD_DataIdentification.spatialResolution.MD_Resolution.distance.gco:Distance';
COMMENT ON COLUMN ISOQP_SpatialResolution.DistanceUOM
    IS 'MD_Metadata.identificationInfo.MD_DataIdentification.spatialResolution.MD_Resolution.distance.gco:Distance@uom';

CREATE TABLE ISOQP_TemporalExtent ( 
	ID integer NOT NULL,
	fk_datasets integer NOT NULL,
	TempExtent_begin timestamp NOT NULL,    -- MD_Metadata.identificationInfo.MD_DataIdentification.extent.EX_Extent.temporalElement.EX_TemporalExtent.extent.TimePeriod.beginPosition 
	TempExtent_end timestamp NOT NULL    -- MD_Metadata.identificationInfo.MD_DataIdentification.extent.EX_Extent.temporalElement.EX_TemporalExtent.extent.TimePeriod.endPosition 
);
COMMENT ON TABLE ISOQP_TemporalExtent
    IS 'additional queryable property (ISO AP 1.0) - dataset, datasetcollection, application';
COMMENT ON COLUMN ISOQP_TemporalExtent.TempExtent_begin
    IS 'MD_Metadata.identificationInfo.MD_DataIdentification.extent.EX_Extent.temporalElement.EX_TemporalExtent.extent.TimePeriod.beginPosition';
COMMENT ON COLUMN ISOQP_TemporalExtent.TempExtent_end
    IS 'MD_Metadata.identificationInfo.MD_DataIdentification.extent.EX_Extent.temporalElement.EX_TemporalExtent.extent.TimePeriod.endPosition';

CREATE TABLE ISOQP_Title ( 
	ID integer NOT NULL,
	fk_datasets integer NOT NULL,
	Title varchar(500) NOT NULL    -- MD_Metadata.identificationInfo.AbstractMD_Identification.citation.CI_Citation.title 
);
COMMENT ON TABLE ISOQP_Title
    IS 'common queryable property (ISO AP 1.0)';
COMMENT ON COLUMN ISOQP_Title.Title
    IS 'MD_Metadata.identificationInfo.AbstractMD_Identification.citation.CI_Citation.title';

CREATE TABLE ISOQP_TopicCategory ( 
	ID integer NOT NULL,
	fk_datasets integer NOT NULL,
	TopicCategory varchar(50) NOT NULL    -- MD_Metadata.identificationInfo.MD_DataIdentification.topicCategory 
);
COMMENT ON TABLE ISOQP_TopicCategory
    IS 'additional queryable property (ISO AP 1.0) - dataset, datasetcollection, application';
COMMENT ON COLUMN ISOQP_TopicCategory.TopicCategory
    IS 'MD_Metadata.identificationInfo.MD_DataIdentification.topicCategory';

CREATE TABLE ISOQP_Type ( 
	ID integer NOT NULL,
	fk_datasets integer NOT NULL,
	Type varchar(50) NOT NULL    -- MD_Metadata.hierarchyLevel.MD_ScopeCode/@codeListValue. If MD_Metadata.hierarchyLevel is missing, 'Type' will be considered as "Dataset" (default). 
);
COMMENT ON TABLE ISOQP_Type
    IS 'common queryable property (ISO AP 1.0)';
COMMENT ON COLUMN ISOQP_Type.Type
    IS 'MD_Metadata.hierarchyLevel.MD_ScopeCode/@codeListValue. If MD_Metadata.hierarchyLevel is missing, ''Type'' will be considered as "Dataset" (default).';

CREATE TABLE RecordBrief ( 
	ID integer NOT NULL,
	fk_datasets integer NOT NULL,
	format numeric(2) NOT NULL,
	data bytea NOT NULL
);
COMMENT ON TABLE RecordBrief
    IS 'This is the table for the brief representation of a getRecords response, because a brief representation has to be allways provided.';

CREATE TABLE RecordSummary ( 
    ID integer NOT NULL,
	fk_datasets integer NOT NULL,
	format numeric(2) NOT NULL,
	data bytea NOT NULL
);
COMMENT ON TABLE RecordSummary
    IS 'This is the table for the summary representation of a getRecords response';

CREATE TABLE RecordFull ( 
    ID integer NOT NULL,
	fk_datasets integer NOT NULL,
	format numeric(2) NOT NULL,
	data bytea NOT NULL
);
COMMENT ON TABLE RecordFull
    IS 'This is the mandatory table for the full representation of a getRecords response';

CREATE TABLE UserDefinedQueryableProperties ( 
	fk_datasets integer NOT NULL
);
COMMENT ON TABLE UserDefinedQueryableProperties
    IS 'Collection of user defined queryable properties';


--CREATE TABLE DCQP_RIGHTS ( 
--	ID integer NOT NULL,
--	fk_datasets integer NOT NULL,
--	Rights varchar(100) NOT NULL   
--);
--COMMENT ON TABLE DCQP_RIGHTS
--    IS 'dublin core queryable property (DC)';
--COMMENT ON COLUMN DCQP_RIGHTS.Rights
--    IS 'Rights is not in the ISO AP but in DC';


-- Create Primary Key Constraints 
ALTER TABLE Datasets ADD CONSTRAINT PK_Datasets 
	PRIMARY KEY (ID);


ALTER TABLE ISOQP_Abstract ADD CONSTRAINT PK_ISOQP_Abstract 
	PRIMARY KEY (ID);


ALTER TABLE ISOQP_AlternateTitle ADD CONSTRAINT PK_ISOQP_AlternateTitle 
	PRIMARY KEY (ID);


ALTER TABLE ISOQP_BoundingBox ADD CONSTRAINT PK_ISOQP_BoundingBox 
	PRIMARY KEY (ID);


ALTER TABLE ISOQP_CouplingType ADD CONSTRAINT PK_ISOQP_CouplingType 
	PRIMARY KEY (ID);


ALTER TABLE ISOQP_CreationDate ADD CONSTRAINT PK_ISOQP_CreationDate 
	PRIMARY KEY (ID);


ALTER TABLE ISOQP_CRS ADD CONSTRAINT PK_ISOQP_CRS 
	PRIMARY KEY (ID);


ALTER TABLE ISOQP_Format ADD CONSTRAINT PK_ISOQP_Format 
	PRIMARY KEY (ID);


ALTER TABLE ISOQP_GeographicDescriptionCode ADD CONSTRAINT PK_ISOQP_GeographicDescriptionCode 
	PRIMARY KEY (ID);


ALTER TABLE ISOQP_Keyword ADD CONSTRAINT PK_ISOQP_Keyword 
	PRIMARY KEY (ID);


ALTER TABLE ISOQP_OperatesOnData ADD CONSTRAINT PK_ISOQP_OperatesOnData 
	PRIMARY KEY (ID);


ALTER TABLE ISOQP_Operation ADD CONSTRAINT PK_ISOQP_Operation 
	PRIMARY KEY (ID);


ALTER TABLE ISOQP_OrganisationName ADD CONSTRAINT PK_ISOQP_OrganisationName 
	PRIMARY KEY (ID);


ALTER TABLE ISOQP_PublicationDate ADD CONSTRAINT PK_ISOQP_PublicationDate 
	PRIMARY KEY (ID);


ALTER TABLE ISOQP_ResourceIdentifier ADD CONSTRAINT PK_ISOQP_ResourceIdentifier 
	PRIMARY KEY (ID);


ALTER TABLE ISOQP_ResourceLanguage ADD CONSTRAINT PK_ISOQP_ResourceLanguage 
	PRIMARY KEY (ID);


ALTER TABLE ISOQP_RevisionDate ADD CONSTRAINT PK_ISOQP_RevisionDate 
	PRIMARY KEY (ID);


ALTER TABLE ISOQP_ServiceType ADD CONSTRAINT PK_ISOQP_ServiceType 
	PRIMARY KEY (ID);


ALTER TABLE ISOQP_ServiceTypeVersion ADD CONSTRAINT PK_ISOQP_ServiceTypeVersion 
	PRIMARY KEY (ID);


ALTER TABLE ISOQP_SpatialResolution ADD CONSTRAINT PK_ISOQP_SpatialResolution 
	PRIMARY KEY (ID);


ALTER TABLE ISOQP_TemporalExtent ADD CONSTRAINT PK_ISOQP_TemporalExtent 
	PRIMARY KEY (ID);


ALTER TABLE ISOQP_Title ADD CONSTRAINT PK_ISOQP_Title 
	PRIMARY KEY (ID);


ALTER TABLE ISOQP_TopicCategory ADD CONSTRAINT PK_ISOQP_TopicCategory 
	PRIMARY KEY (ID);


ALTER TABLE ISOQP_Type ADD CONSTRAINT PK_ISOQP_Type 
	PRIMARY KEY (ID);


ALTER TABLE RecordBrief ADD CONSTRAINT PK_RecordBrief
	PRIMARY KEY (ID);


ALTER TABLE RecordSummary ADD CONSTRAINT PK_RecordSummary
	PRIMARY KEY (ID);


ALTER TABLE RecordFull ADD CONSTRAINT PK_RecordFull
	PRIMARY KEY (ID);


ALTER TABLE UserDefinedQueryableProperties ADD CONSTRAINT PK_SelfQueryableProperties 
	PRIMARY KEY (fk_datasets);


--ALTER TABLE DCQP_Rights ADD CONSTRAINT PK_DCQP_Rights 
--	PRIMARY KEY (ID);



-- Create Indexes 
ALTER TABLE Datasets
	ADD CONSTRAINT UQ_Datasets_ID UNIQUE (ID);
ALTER TABLE ISOQP_Abstract
	ADD CONSTRAINT UQ_ISOQP_Abstract_ID UNIQUE (ID);
ALTER TABLE ISOQP_AlternateTitle
	ADD CONSTRAINT UQ_ISOQP_AlternateTitle_ID UNIQUE (ID);
ALTER TABLE ISOQP_BoundingBox
	ADD CONSTRAINT UQ_ISOQP_BoundingBox_ID UNIQUE (ID);
ALTER TABLE ISOQP_CouplingType
	ADD CONSTRAINT UQ_ISOQP_CouplingType_ID UNIQUE (ID);
ALTER TABLE ISOQP_CreationDate
	ADD CONSTRAINT UQ_ISOQP_CreationDate_ID UNIQUE (ID);
ALTER TABLE ISOQP_CRS
	ADD CONSTRAINT UQ_ISOQP_CRS_ID UNIQUE (ID);
ALTER TABLE ISOQP_Format
	ADD CONSTRAINT UQ_ISOQP_Format_ID UNIQUE (ID);
ALTER TABLE ISOQP_GeographicDescriptionCode
	ADD CONSTRAINT UQ_ISOQP_GeographicDescriptionCode_ID UNIQUE (ID);
ALTER TABLE ISOQP_Keyword
	ADD CONSTRAINT UQ_ISOQP_Keyword_ID UNIQUE (ID);
ALTER TABLE ISOQP_OperatesOnData
	ADD CONSTRAINT UQ_ISOQP_OperatesOnData_ID UNIQUE (ID);
ALTER TABLE ISOQP_Operation
	ADD CONSTRAINT UQ_ISOQP_Operation_ID UNIQUE (ID);
ALTER TABLE ISOQP_OrganisationName
	ADD CONSTRAINT UQ_ISOQP_OrganisationName_ID UNIQUE (ID);
ALTER TABLE ISOQP_PublicationDate
	ADD CONSTRAINT UQ_ISOQP_PublicationDate_ID UNIQUE (ID);
ALTER TABLE ISOQP_ResourceIdentifier
	ADD CONSTRAINT UQ_ISOQP_ResourceIdentifier_ID UNIQUE (ID);
ALTER TABLE ISOQP_ResourceLanguage
	ADD CONSTRAINT UQ_ISOQP_ResourceLanguage_ID UNIQUE (ID);
ALTER TABLE ISOQP_RevisionDate
	ADD CONSTRAINT UQ_ISOQP_RevisionDate_ID UNIQUE (ID);
ALTER TABLE ISOQP_ServiceType
	ADD CONSTRAINT UQ_ISOQP_ServiceType_ID UNIQUE (ID);
ALTER TABLE ISOQP_ServiceTypeVersion
	ADD CONSTRAINT UQ_ISOQP_ServiceTypeVersion_ID UNIQUE (ID);
ALTER TABLE ISOQP_SpatialResolution
	ADD CONSTRAINT UQ_ISOQP_SpatialResolution_ID UNIQUE (ID);
ALTER TABLE ISOQP_TemporalExtent
	ADD CONSTRAINT UQ_ISOQP_TemporalExtent_ID UNIQUE (ID);
ALTER TABLE ISOQP_Title
	ADD CONSTRAINT UQ_ISOQP_Title_ID UNIQUE (ID);
ALTER TABLE ISOQP_TopicCategory
	ADD CONSTRAINT UQ_ISOQP_TopicCategory_ID UNIQUE (ID);
ALTER TABLE ISOQP_Type
	ADD CONSTRAINT UQ_ISOQP_Type_ID UNIQUE (ID);
ALTER TABLE UserDefinedQueryableProperties
	ADD CONSTRAINT UQ_SelfQueryableProperties_fk_datasets UNIQUE (fk_datasets);

--ALTER TABLE DCQP_Rights
--	ADD CONSTRAINT UQ_DCQP_Rights_ID UNIQUE (ID);

-- Create Foreign Key Constraints 
ALTER TABLE Datasets ADD CONSTRAINT FK_Datasets_SelfQueryableProperties 
	FOREIGN KEY (ID) REFERENCES UserDefinedQueryableProperties (fk_datasets);

ALTER TABLE ISOQP_Abstract ADD CONSTRAINT FK_ISOQP_Abstract_Datasets 
	FOREIGN KEY (fk_datasets) REFERENCES Datasets (ID);

ALTER TABLE ISOQP_AlternateTitle ADD CONSTRAINT FK_ISOQP_AlternateTitle_Datasets 
	FOREIGN KEY (fk_datasets) REFERENCES Datasets (ID);

ALTER TABLE ISOQP_BoundingBox ADD CONSTRAINT FK_ISOQP_BoundingBox_Datasets 
	FOREIGN KEY (fk_datasets) REFERENCES Datasets (ID);

ALTER TABLE ISOQP_CouplingType ADD CONSTRAINT FK_ISOQP_CouplingType_Datasets 
	FOREIGN KEY (fk_datasets) REFERENCES Datasets (ID);

ALTER TABLE ISOQP_CreationDate ADD CONSTRAINT FK_ISOQP_CreationDate_Datasets 
	FOREIGN KEY (fk_datasets) REFERENCES Datasets (ID);

ALTER TABLE ISOQP_CRS ADD CONSTRAINT FK_ISOQP_CRS_Datasets 
	FOREIGN KEY (fk_datasets) REFERENCES Datasets (ID);

ALTER TABLE ISOQP_Format ADD CONSTRAINT FK_ISOQP_Format_Datasets 
	FOREIGN KEY (fk_datasets) REFERENCES Datasets (ID);

ALTER TABLE ISOQP_GeographicDescriptionCode ADD CONSTRAINT FK_ISOQP_GeographicDescriptionCode_Datasets 
	FOREIGN KEY (fk_datasets) REFERENCES Datasets (ID);

ALTER TABLE ISOQP_Keyword ADD CONSTRAINT FK_ISOQP_KeywordType_Datasets 
	FOREIGN KEY (fk_datasets) REFERENCES Datasets (ID);

ALTER TABLE ISOQP_OperatesOnData ADD CONSTRAINT FK_ISOQP_OperatesOnData_Datasets 
	FOREIGN KEY (fk_datasets) REFERENCES Datasets (ID);

ALTER TABLE ISOQP_Operation ADD CONSTRAINT FK_ISOQP_Operation_Datasets 
	FOREIGN KEY (fk_datasets) REFERENCES Datasets (ID);

ALTER TABLE ISOQP_OrganisationName ADD CONSTRAINT FK_ISOQP_OrganisationName_Datasets 
	FOREIGN KEY (fk_datasets) REFERENCES Datasets (ID);

ALTER TABLE ISOQP_PublicationDate ADD CONSTRAINT FK_ISOQP_PublicationDate_Datasets 
	FOREIGN KEY (fk_datasets) REFERENCES Datasets (ID);

ALTER TABLE ISOQP_ResourceIdentifier ADD CONSTRAINT FK_ISOQP_ResourceIdentifier_Datasets 
	FOREIGN KEY (fk_datasets) REFERENCES Datasets (ID);

ALTER TABLE ISOQP_ResourceLanguage ADD CONSTRAINT FK_ISOQP_ResourceLanguage_Datasets 
	FOREIGN KEY (fk_datasets) REFERENCES Datasets (ID);

ALTER TABLE ISOQP_RevisionDate ADD CONSTRAINT FK_ISOQP_RevisionDate_Datasets 
	FOREIGN KEY (fk_datasets) REFERENCES Datasets (ID);

ALTER TABLE ISOQP_ServiceType ADD CONSTRAINT FK_ISOQP_ServiceType_Datasets 
	FOREIGN KEY (fk_datasets) REFERENCES Datasets (ID);

ALTER TABLE ISOQP_ServiceTypeVersion ADD CONSTRAINT FK_ISOQP_ServiceTypeVersion_Datasets 
	FOREIGN KEY (fk_datasets) REFERENCES Datasets (ID);

ALTER TABLE ISOQP_SpatialResolution ADD CONSTRAINT FK_ISOQP_SpatialResolution_Datasets 
	FOREIGN KEY (fk_datasets) REFERENCES Datasets (ID);

ALTER TABLE ISOQP_TemporalExtent ADD CONSTRAINT FK_ISOQP_TemporalExtent_Datasets 
	FOREIGN KEY (fk_datasets) REFERENCES Datasets (ID);

ALTER TABLE ISOQP_Title ADD CONSTRAINT FK_ISOQP_Title_Datasets 
	FOREIGN KEY (fk_datasets) REFERENCES Datasets (ID);

ALTER TABLE ISOQP_TopicCategory ADD CONSTRAINT FK_ISOQP_TopicCategory_Datasets 
	FOREIGN KEY (fk_datasets) REFERENCES Datasets (ID);

ALTER TABLE ISOQP_Type ADD CONSTRAINT FK_ISOQP_Type_Datasets 
	FOREIGN KEY (fk_datasets) REFERENCES Datasets (ID);

ALTER TABLE RecordBrief ADD CONSTRAINT FK_RecordBrief_Datasets 
	FOREIGN KEY (fk_datasets) REFERENCES Datasets (ID);

ALTER TABLE RecordSummary ADD CONSTRAINT FK_RecordSummary_Datasets 
	FOREIGN KEY (fk_datasets) REFERENCES Datasets (ID);

ALTER TABLE RecordFull ADD CONSTRAINT FK_RecordFull_Datasets 
	FOREIGN KEY (fk_datasets) REFERENCES Datasets (ID);

--ALTER TABLE DCQP_Rights ADD CONSTRAINT FK_DCQP_Rights_Datasets 
--	FOREIGN KEY (fk_datasets) REFERENCES Datasets (ID);
