//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.11.13 at 03:16:35 PM MEZ 
//


package org.deegree.feature.persistence.postgis.jaxbconfig;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Root element (container for all feature type
 *         declarations)
 * 
 * <p>Java class for ApplicationSchema element declaration.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;element name="ApplicationSchema">
 *   &lt;complexType>
 *     &lt;complexContent>
 *       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *         &lt;sequence>
 *           &lt;element ref="{http://www.deegree.org/feature/featuretype}GlobalMappingHints"/>
 *           &lt;element ref="{http://www.deegree.org/feature/featuretype}FeatureType" maxOccurs="unbounded"/>
 *         &lt;/sequence>
 *       &lt;/restriction>
 *     &lt;/complexContent>
 *   &lt;/complexType>
 * &lt;/element>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "globalMappingHints",
    "featureType"
})
@XmlRootElement(name = "ApplicationSchema")
public class ApplicationSchemaDecl {

    @XmlElement(name = "GlobalMappingHints", required = true)
    protected GlobalMappingHints globalMappingHints;
    @XmlElement(name = "FeatureType", required = true)
    protected List<FeatureTypeDecl> featureType;

    /**
     * Gets the value of the globalMappingHints property.
     * 
     * @return
     *     possible object is
     *     {@link GlobalMappingHints }
     *     
     */
    public GlobalMappingHints getGlobalMappingHints() {
        return globalMappingHints;
    }

    /**
     * Sets the value of the globalMappingHints property.
     * 
     * @param value
     *     allowed object is
     *     {@link GlobalMappingHints }
     *     
     */
    public void setGlobalMappingHints(GlobalMappingHints value) {
        this.globalMappingHints = value;
    }

    /**
     * Gets the value of the featureType property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the featureType property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFeatureType().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FeatureTypeDecl }
     * 
     * 
     */
    public List<FeatureTypeDecl> getFeatureType() {
        if (featureType == null) {
            featureType = new ArrayList<FeatureTypeDecl>();
        }
        return this.featureType;
    }

}
