//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.11.09 at 03:42:05 PM MEZ 
//


package org.deegree.feature.persistence.postgis.jaxbconfig;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Definition of a geometry-valued property of a
 *           feature type.
 * 
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.deegree.org/feature/featuretype}AbstractPropertyType">
 *       &lt;sequence>
 *         &lt;element name="Mapping">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice>
 *                   &lt;element ref="{http://www.deegree.org/feature/featuretype}GeometryDBColumn"/>
 *                   &lt;element ref="{http://www.deegree.org/feature/featuretype}GeometryPropertyTable"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="type" type="{http://www.deegree.org/feature/featuretype}GeometryType" />
 *       &lt;attribute name="coordinateDimension">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKENS">
 *             &lt;enumeration value="2D"/>
 *             &lt;enumeration value="3D"/>
 *             &lt;enumeration value="2D or 3D"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "mapping"
})
public class GeometryPropertyDecl
    extends AbstractPropertyDecl
{

    @XmlElement(name = "Mapping", required = true)
    protected GeometryPropertyDecl.Mapping mapping;
    @XmlAttribute
    protected GeometryType type;
    @XmlAttribute
    protected List<String> coordinateDimension;

    /**
     * Gets the value of the mapping property.
     * 
     * @return
     *     possible object is
     *     {@link GeometryPropertyDecl.Mapping }
     *     
     */
    public GeometryPropertyDecl.Mapping getMapping() {
        return mapping;
    }

    /**
     * Sets the value of the mapping property.
     * 
     * @param value
     *     allowed object is
     *     {@link GeometryPropertyDecl.Mapping }
     *     
     */
    public void setMapping(GeometryPropertyDecl.Mapping value) {
        this.mapping = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link GeometryType }
     *     
     */
    public GeometryType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link GeometryType }
     *     
     */
    public void setType(GeometryType value) {
        this.type = value;
    }

    /**
     * Gets the value of the coordinateDimension property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the coordinateDimension property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCoordinateDimension().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getCoordinateDimension() {
        if (coordinateDimension == null) {
            coordinateDimension = new ArrayList<String>();
        }
        return this.coordinateDimension;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice>
     *         &lt;element ref="{http://www.deegree.org/feature/featuretype}GeometryDBColumn"/>
     *         &lt;element ref="{http://www.deegree.org/feature/featuretype}GeometryPropertyTable"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "geometryDBColumn",
        "geometryPropertyTable"
    })
    public static class Mapping {

        @XmlElement(name = "GeometryDBColumn")
        protected GeometryDBColumn geometryDBColumn;
        @XmlElement(name = "GeometryPropertyTable")
        protected GeometryPropertyTable geometryPropertyTable;

        /**
         * Gets the value of the geometryDBColumn property.
         * 
         * @return
         *     possible object is
         *     {@link GeometryDBColumn }
         *     
         */
        public GeometryDBColumn getGeometryDBColumn() {
            return geometryDBColumn;
        }

        /**
         * Sets the value of the geometryDBColumn property.
         * 
         * @param value
         *     allowed object is
         *     {@link GeometryDBColumn }
         *     
         */
        public void setGeometryDBColumn(GeometryDBColumn value) {
            this.geometryDBColumn = value;
        }

        /**
         * Gets the value of the geometryPropertyTable property.
         * 
         * @return
         *     possible object is
         *     {@link GeometryPropertyTable }
         *     
         */
        public GeometryPropertyTable getGeometryPropertyTable() {
            return geometryPropertyTable;
        }

        /**
         * Sets the value of the geometryPropertyTable property.
         * 
         * @param value
         *     allowed object is
         *     {@link GeometryPropertyTable }
         *     
         */
        public void setGeometryPropertyTable(GeometryPropertyTable value) {
            this.geometryPropertyTable = value;
        }

    }

}
