//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.11.13 at 03:16:35 PM MEZ 
//


package org.deegree.feature.persistence.postgis.jaxbconfig;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.deegree.feature.persistence.postgis.jaxbconfig package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _GeometryProperty_QNAME = new QName("http://www.deegree.org/feature/featuretype", "GeometryProperty");
    private final static QName _CustomComplexProperty_QNAME = new QName("http://www.deegree.org/feature/featuretype", "CustomComplexProperty");
    private final static QName _MeasureProperty_QNAME = new QName("http://www.deegree.org/feature/featuretype", "MeasureProperty");
    private final static QName _SimplePropertyMapping_QNAME = new QName("http://www.deegree.org/feature/featuretype", "SimplePropertyMapping");
    private final static QName _SimpleProperty_QNAME = new QName("http://www.deegree.org/feature/featuretype", "SimpleProperty");
    private final static QName _CustomPropertyMapping_QNAME = new QName("http://www.deegree.org/feature/featuretype", "CustomPropertyMapping");
    private final static QName _PropertyMapping_QNAME = new QName("http://www.deegree.org/feature/featuretype", "PropertyMapping");
    private final static QName _AbstractProperty_QNAME = new QName("http://www.deegree.org/feature/featuretype", "AbstractProperty");
    private final static QName _FeatureProperty_QNAME = new QName("http://www.deegree.org/feature/featuretype", "FeatureProperty");
    private final static QName _FeaturePropertyMapping_QNAME = new QName("http://www.deegree.org/feature/featuretype", "FeaturePropertyMapping");
    private final static QName _MeasurePropertyMapping_QNAME = new QName("http://www.deegree.org/feature/featuretype", "MeasurePropertyMapping");
    private final static QName _GeometryPropertyMapping_QNAME = new QName("http://www.deegree.org/feature/featuretype", "GeometryPropertyMapping");
    private final static QName _FeatureType_QNAME = new QName("http://www.deegree.org/feature/featuretype", "FeatureType");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.deegree.feature.persistence.postgis.jaxbconfig
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GeometryPropertyMappingType }
     * 
     */
    public GeometryPropertyMappingType createGeometryPropertyMappingType() {
        return new GeometryPropertyMappingType();
    }

    /**
     * Create an instance of {@link CustomComplexPropertyDecl }
     * 
     */
    public CustomComplexPropertyDecl createCustomComplexPropertyDecl() {
        return new CustomComplexPropertyDecl();
    }

    /**
     * Create an instance of {@link CustomPropertyMappingType }
     * 
     */
    public CustomPropertyMappingType createCustomPropertyMappingType() {
        return new CustomPropertyMappingType();
    }

    /**
     * Create an instance of {@link FeatureTypeDecl }
     * 
     */
    public FeatureTypeDecl createFeatureTypeDecl() {
        return new FeatureTypeDecl();
    }

    /**
     * Create an instance of {@link DBColumn }
     * 
     */
    public DBColumn createDBColumn() {
        return new DBColumn();
    }

    /**
     * Create an instance of {@link MeasurePropertyMappingType }
     * 
     */
    public MeasurePropertyMappingType createMeasurePropertyMappingType() {
        return new MeasurePropertyMappingType();
    }

    /**
     * Create an instance of {@link ApplicationSchemaDecl }
     * 
     */
    public ApplicationSchemaDecl createApplicationSchemaDecl() {
        return new ApplicationSchemaDecl();
    }

    /**
     * Create an instance of {@link GeometryPropertyTable }
     * 
     */
    public GeometryPropertyTable createGeometryPropertyTable() {
        return new GeometryPropertyTable();
    }

    /**
     * Create an instance of {@link GeometryDBColumn }
     * 
     */
    public GeometryDBColumn createGeometryDBColumn() {
        return new GeometryDBColumn();
    }

    /**
     * Create an instance of {@link FeaturePropertyMappingType }
     * 
     */
    public FeaturePropertyMappingType createFeaturePropertyMappingType() {
        return new FeaturePropertyMappingType();
    }

    /**
     * Create an instance of {@link FeaturePropertyDecl }
     * 
     */
    public FeaturePropertyDecl createFeaturePropertyDecl() {
        return new FeaturePropertyDecl();
    }

    /**
     * Create an instance of {@link MeasurePropertyDecl }
     * 
     */
    public MeasurePropertyDecl createMeasurePropertyDecl() {
        return new MeasurePropertyDecl();
    }

    /**
     * Create an instance of {@link SimplePropertyMappingType }
     * 
     */
    public SimplePropertyMappingType createSimplePropertyMappingType() {
        return new SimplePropertyMappingType();
    }

    /**
     * Create an instance of {@link FeatureJoinTable }
     * 
     */
    public FeatureJoinTable createFeatureJoinTable() {
        return new FeatureJoinTable();
    }

    /**
     * Create an instance of {@link PropertyTable }
     * 
     */
    public PropertyTable createPropertyTable() {
        return new PropertyTable();
    }

    /**
     * Create an instance of {@link GlobalMappingHints }
     * 
     */
    public GlobalMappingHints createGlobalMappingHints() {
        return new GlobalMappingHints();
    }

    /**
     * Create an instance of {@link GeometryPropertyDecl }
     * 
     */
    public GeometryPropertyDecl createGeometryPropertyDecl() {
        return new GeometryPropertyDecl();
    }

    /**
     * Create an instance of {@link SimplePropertyDecl }
     * 
     */
    public SimplePropertyDecl createSimplePropertyDecl() {
        return new SimplePropertyDecl();
    }

    /**
     * Create an instance of {@link FeatureTypeMappingHints }
     * 
     */
    public FeatureTypeMappingHints createFeatureTypeMappingHints() {
        return new FeatureTypeMappingHints();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GeometryPropertyDecl }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.deegree.org/feature/featuretype", name = "GeometryProperty", substitutionHeadNamespace = "http://www.deegree.org/feature/featuretype", substitutionHeadName = "AbstractProperty")
    public JAXBElement<GeometryPropertyDecl> createGeometryProperty(GeometryPropertyDecl value) {
        return new JAXBElement<GeometryPropertyDecl>(_GeometryProperty_QNAME, GeometryPropertyDecl.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CustomComplexPropertyDecl }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.deegree.org/feature/featuretype", name = "CustomComplexProperty", substitutionHeadNamespace = "http://www.deegree.org/feature/featuretype", substitutionHeadName = "AbstractProperty")
    public JAXBElement<CustomComplexPropertyDecl> createCustomComplexProperty(CustomComplexPropertyDecl value) {
        return new JAXBElement<CustomComplexPropertyDecl>(_CustomComplexProperty_QNAME, CustomComplexPropertyDecl.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MeasurePropertyDecl }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.deegree.org/feature/featuretype", name = "MeasureProperty", substitutionHeadNamespace = "http://www.deegree.org/feature/featuretype", substitutionHeadName = "AbstractProperty")
    public JAXBElement<MeasurePropertyDecl> createMeasureProperty(MeasurePropertyDecl value) {
        return new JAXBElement<MeasurePropertyDecl>(_MeasureProperty_QNAME, MeasurePropertyDecl.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SimplePropertyMappingType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.deegree.org/feature/featuretype", name = "SimplePropertyMapping", substitutionHeadNamespace = "http://www.deegree.org/feature/featuretype", substitutionHeadName = "PropertyMapping")
    public JAXBElement<SimplePropertyMappingType> createSimplePropertyMapping(SimplePropertyMappingType value) {
        return new JAXBElement<SimplePropertyMappingType>(_SimplePropertyMapping_QNAME, SimplePropertyMappingType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SimplePropertyDecl }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.deegree.org/feature/featuretype", name = "SimpleProperty", substitutionHeadNamespace = "http://www.deegree.org/feature/featuretype", substitutionHeadName = "AbstractProperty")
    public JAXBElement<SimplePropertyDecl> createSimpleProperty(SimplePropertyDecl value) {
        return new JAXBElement<SimplePropertyDecl>(_SimpleProperty_QNAME, SimplePropertyDecl.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CustomPropertyMappingType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.deegree.org/feature/featuretype", name = "CustomPropertyMapping", substitutionHeadNamespace = "http://www.deegree.org/feature/featuretype", substitutionHeadName = "PropertyMapping")
    public JAXBElement<CustomPropertyMappingType> createCustomPropertyMapping(CustomPropertyMappingType value) {
        return new JAXBElement<CustomPropertyMappingType>(_CustomPropertyMapping_QNAME, CustomPropertyMappingType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PropertyMappingType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.deegree.org/feature/featuretype", name = "PropertyMapping")
    public JAXBElement<PropertyMappingType> createPropertyMapping(PropertyMappingType value) {
        return new JAXBElement<PropertyMappingType>(_PropertyMapping_QNAME, PropertyMappingType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AbstractPropertyDecl }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.deegree.org/feature/featuretype", name = "AbstractProperty")
    public JAXBElement<AbstractPropertyDecl> createAbstractProperty(AbstractPropertyDecl value) {
        return new JAXBElement<AbstractPropertyDecl>(_AbstractProperty_QNAME, AbstractPropertyDecl.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FeaturePropertyDecl }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.deegree.org/feature/featuretype", name = "FeatureProperty", substitutionHeadNamespace = "http://www.deegree.org/feature/featuretype", substitutionHeadName = "AbstractProperty")
    public JAXBElement<FeaturePropertyDecl> createFeatureProperty(FeaturePropertyDecl value) {
        return new JAXBElement<FeaturePropertyDecl>(_FeatureProperty_QNAME, FeaturePropertyDecl.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FeaturePropertyMappingType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.deegree.org/feature/featuretype", name = "FeaturePropertyMapping", substitutionHeadNamespace = "http://www.deegree.org/feature/featuretype", substitutionHeadName = "PropertyMapping")
    public JAXBElement<FeaturePropertyMappingType> createFeaturePropertyMapping(FeaturePropertyMappingType value) {
        return new JAXBElement<FeaturePropertyMappingType>(_FeaturePropertyMapping_QNAME, FeaturePropertyMappingType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MeasurePropertyMappingType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.deegree.org/feature/featuretype", name = "MeasurePropertyMapping", substitutionHeadNamespace = "http://www.deegree.org/feature/featuretype", substitutionHeadName = "PropertyMapping")
    public JAXBElement<MeasurePropertyMappingType> createMeasurePropertyMapping(MeasurePropertyMappingType value) {
        return new JAXBElement<MeasurePropertyMappingType>(_MeasurePropertyMapping_QNAME, MeasurePropertyMappingType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GeometryPropertyMappingType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.deegree.org/feature/featuretype", name = "GeometryPropertyMapping", substitutionHeadNamespace = "http://www.deegree.org/feature/featuretype", substitutionHeadName = "PropertyMapping")
    public JAXBElement<GeometryPropertyMappingType> createGeometryPropertyMapping(GeometryPropertyMappingType value) {
        return new JAXBElement<GeometryPropertyMappingType>(_GeometryPropertyMapping_QNAME, GeometryPropertyMappingType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FeatureTypeDecl }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.deegree.org/feature/featuretype", name = "FeatureType")
    public JAXBElement<FeatureTypeDecl> createFeatureType(FeatureTypeDecl value) {
        return new JAXBElement<FeatureTypeDecl>(_FeatureType_QNAME, FeatureTypeDecl.class, null, value);
    }

}
