//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.11.13 at 03:16:35 PM MEZ 
//


package org.deegree.feature.persistence.postgis.jaxbconfig;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PrimitiveType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="PrimitiveType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="STRING"/>
 *     &lt;enumeration value="BOOLEAN"/>
 *     &lt;enumeration value="DECIMAL"/>
 *     &lt;enumeration value="DOUBLE"/>
 *     &lt;enumeration value="INTEGER"/>
 *     &lt;enumeration value="DATE"/>
 *     &lt;enumeration value="DATE_TIME"/>
 *     &lt;enumeration value="TIME"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "PrimitiveType")
@XmlEnum
public enum PrimitiveType {


    /**
     * String-valued property (=xs:string)
     * 
     */
    STRING,

    /**
     * Boolean-valued property (=xs:boolean)
     * 
     */
    BOOLEAN,

    /**
     * Decimal-valued property (=xs:decimal)
     * 
     */
    DECIMAL,

    /**
     * Double-valued property (=xs:double)
     * 
     */
    DOUBLE,

    /**
     * Integer-valued property (=xs:integer)
     * 
     */
    INTEGER,

    /**
     * Date-valued property (=xs:date)
     * 
     */
    DATE,

    /**
     * Date-valued property (=xs:dateTime)
     * 
     */
    DATE_TIME,

    /**
     * Time-valued property (=xs:time)
     * 
     */
    TIME;

    public String value() {
        return name();
    }

    public static PrimitiveType fromValue(String v) {
        return valueOf(v);
    }

}
