<?xml version='1.0' encoding='UTF-8'?>
<!--Quelle: : Freie und Hansestadt Hamburg, Behörde für Arbeit, Soziales, Familie und Integration (Sozialbehörde) -->
<!-- https://geodienste.hamburg.de/HH_WFS_KitaEinrichtung?SERVICE=WFS&VERSION=1.1.0&REQUEST=GetCapabilities -->
<mic:Zuwanderung xmlns:mic="http://www.deegree.org/datasource/feature/sql" xmlns:gml="http://www.opengis.net/gml/3.2"
                 gml:id="ZUWANDERUNG_0"
                 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                 xsi:schemaLocation="http://www.deegree.org/datasource/feature/sql zeitreihe.xsd">
  <mic:wohnungslose_jep>
    <mic:zeitreihe>
      <mic:zeitreihen-element>
        <mic:datum>2014</mic:datum>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2020-05</mic:datum>
        <mic:wert>5432</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2019-08</mic:datum>
        <mic:wert>5274</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2019-09</mic:datum>
        <mic:wert>5257</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2019-10</mic:datum>
        <mic:wert>5310</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2019-11</mic:datum>
        <mic:wert>5358</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2019-12</mic:datum>
        <mic:wert>5436</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2020-01</mic:datum>
        <mic:wert>5466</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2020-04</mic:datum>
        <mic:wert>5500</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2020-06</mic:datum>
        <mic:wert>5464</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2015-06</mic:datum>
        <mic:wert>2543</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2015-07</mic:datum>
        <mic:wert>2586</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2015-08</mic:datum>
        <mic:wert>2634</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2015-09</mic:datum>
        <mic:wert>2649</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2015-10</mic:datum>
        <mic:wert>2709</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2015-11</mic:datum>
        <mic:wert>2791</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2015-12</mic:datum>
        <mic:wert>2982</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2016-01</mic:datum>
        <mic:wert>2908</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2016-02</mic:datum>
        <mic:wert>3003</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2016-03</mic:datum>
        <mic:wert>3010</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2016-04</mic:datum>
        <mic:wert>3095</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2016-05</mic:datum>
        <mic:wert>3114</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2016-06</mic:datum>
        <mic:wert>3151</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2016-07</mic:datum>
        <mic:wert>3226</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2016-08</mic:datum>
        <mic:wert>3269</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2016-09</mic:datum>
        <mic:wert>3251</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2016-10</mic:datum>
        <mic:wert>3282</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2016-11</mic:datum>
        <mic:wert>3303</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2016-12</mic:datum>
        <mic:wert>3319</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2017-01</mic:datum>
        <mic:wert>3366</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2017-02</mic:datum>
        <mic:wert>3405</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2017-03</mic:datum>
        <mic:wert>3580</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2017-04</mic:datum>
        <mic:wert>3660</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2017-05</mic:datum>
        <mic:wert>3716</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2017-06</mic:datum>
        <mic:wert>3897</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2017-07</mic:datum>
        <mic:wert>4027</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2017-08</mic:datum>
        <mic:wert>4173</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2017-09</mic:datum>
        <mic:wert>4294</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2017-10</mic:datum>
        <mic:wert>4321</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2017-11</mic:datum>
        <mic:wert>4442</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2017-12</mic:datum>
        <mic:wert>4505</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2018-01</mic:datum>
        <mic:wert>4625</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2018-02</mic:datum>
        <mic:wert>4652</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2018-03</mic:datum>
        <mic:wert>4649</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2018-04</mic:datum>
        <mic:wert>4612</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2018-05</mic:datum>
        <mic:wert>4676</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2018-06</mic:datum>
        <mic:wert>4716</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2018-07</mic:datum>
        <mic:wert>4762</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2018-08</mic:datum>
        <mic:wert>4810</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2018-09</mic:datum>
        <mic:wert>4926</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2018-10</mic:datum>
        <mic:wert>4966</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2018-11</mic:datum>
        <mic:wert>5008</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2018-12</mic:datum>
        <mic:wert>4954</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2019-01</mic:datum>
        <mic:wert>4991</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2019-02</mic:datum>
        <mic:wert>5007</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2019-03</mic:datum>
        <mic:wert>5051</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2019-04</mic:datum>
        <mic:wert>5164</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2019-05</mic:datum>
        <mic:wert>5210</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2019-06</mic:datum>
        <mic:wert>5276</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2019-07</mic:datum>
        <mic:wert>5289</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2020-02</mic:datum>
        <mic:wert>5474</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2020-03</mic:datum>
        <mic:wert>5506</mic:wert>
      </mic:zeitreihen-element>
    </mic:zeitreihe>
  </mic:wohnungslose_jep>
  <mic:wohnberechtigte_zuwanderer>
    <mic:zeitreihe>
      <mic:zeitreihen-element>
        <mic:datum>2015-06</mic:datum>
        <mic:wert>3395</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2015-07</mic:datum>
        <mic:wert>3420</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2015-08</mic:datum>
        <mic:wert>3478</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2015-09</mic:datum>
        <mic:wert>3533</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2015-10</mic:datum>
        <mic:wert>3563</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2015-11</mic:datum>
        <mic:wert>3632</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2020-04</mic:datum>
        <mic:wert>14464</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2020-05</mic:datum>
        <mic:wert>14301</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2020-06</mic:datum>
        <mic:wert>14110</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2015-12</mic:datum>
        <mic:wert>3635</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2016-01</mic:datum>
        <mic:wert>3886</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2016-02</mic:datum>
        <mic:wert>4021</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2016-03</mic:datum>
        <mic:wert>4103</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2016-04</mic:datum>
        <mic:wert>4069</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2016-05</mic:datum>
        <mic:wert>4499</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2016-06</mic:datum>
        <mic:wert>4592</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2016-07</mic:datum>
        <mic:wert>4779</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2016-08</mic:datum>
        <mic:wert>5101</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2016-09</mic:datum>
        <mic:wert>5678</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2016-10</mic:datum>
        <mic:wert>6190</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2016-11</mic:datum>
        <mic:wert>6976</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2016-12</mic:datum>
        <mic:wert>7344</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2017-01</mic:datum>
        <mic:wert>7904</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2017-02</mic:datum>
        <mic:wert>8493</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2017-03</mic:datum>
        <mic:wert>9475</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2017-04</mic:datum>
        <mic:wert>9949</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2017-05</mic:datum>
        <mic:wert>12128</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2017-06</mic:datum>
        <mic:wert>12314</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2017-07</mic:datum>
        <mic:wert>12828</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2017-08</mic:datum>
        <mic:wert>13317</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2017-09</mic:datum>
        <mic:wert>14014</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2017-10</mic:datum>
        <mic:wert>14693</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2017-11</mic:datum>
        <mic:wert>15112</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2017-12</mic:datum>
        <mic:wert>15218</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2018-01</mic:datum>
        <mic:wert>15302</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2018-02</mic:datum>
        <mic:wert>15282</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2018-03</mic:datum>
        <mic:wert>15459</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2018-04</mic:datum>
        <mic:wert>15461</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2018-05</mic:datum>
        <mic:wert>15522</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2018-06</mic:datum>
        <mic:wert>15616</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2018-07</mic:datum>
        <mic:wert>15562</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2018-08</mic:datum>
        <mic:wert>15493</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2018-09</mic:datum>
        <mic:wert>15450</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2018-10</mic:datum>
        <mic:wert>15406</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2018-11</mic:datum>
        <mic:wert>15524</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2018-12</mic:datum>
        <mic:wert>15439</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2019-01</mic:datum>
        <mic:wert>15397</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2019-02</mic:datum>
        <mic:wert>15399</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2019-03</mic:datum>
        <mic:wert>15369</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2019-04</mic:datum>
        <mic:wert>15267</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2019-05</mic:datum>
        <mic:wert>15338</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2019-06</mic:datum>
        <mic:wert>15275</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2019-07</mic:datum>
        <mic:wert>15090</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2019-08</mic:datum>
        <mic:wert>14953</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2019-09</mic:datum>
        <mic:wert>14842</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2019-10</mic:datum>
        <mic:wert>14877</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2019-11</mic:datum>
        <mic:wert>14756</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2019-12</mic:datum>
        <mic:wert>14631</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2020-01</mic:datum>
        <mic:wert>14590</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2020-02</mic:datum>
        <mic:wert>14721</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2020-03</mic:datum>
        <mic:wert>14535</mic:wert>
      </mic:zeitreihen-element>
    </mic:zeitreihe>
  </mic:wohnberechtigte_zuwanderer>
  <mic:nicht_wohnberechtigte_zuwanderer>
    <mic:zeitreihe>
      <mic:zeitreihen-element>
        <mic:datum>2020-04</mic:datum>
        <mic:wert>10453</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2020-05</mic:datum>
        <mic:wert>10489</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2020-06</mic:datum>
        <mic:wert>10496</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2015-06</mic:datum>
        <mic:wert>7486</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2015-07</mic:datum>
        <mic:wert>7734</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2015-08</mic:datum>
        <mic:wert>7720</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2015-09</mic:datum>
        <mic:wert>7912</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2015-10</mic:datum>
        <mic:wert>8447</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2015-11</mic:datum>
        <mic:wert>9088</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2015-12</mic:datum>
        <mic:wert>9625</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2016-01</mic:datum>
        <mic:wert>9848</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2016-02</mic:datum>
        <mic:wert>10202</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2016-03</mic:datum>
        <mic:wert>11031</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2016-04</mic:datum>
        <mic:wert>11096</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2016-05</mic:datum>
        <mic:wert>11952</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2016-06</mic:datum>
        <mic:wert>12536</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2016-07</mic:datum>
        <mic:wert>13248</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2016-08</mic:datum>
        <mic:wert>13968</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2016-09</mic:datum>
        <mic:wert>13828</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2016-10</mic:datum>
        <mic:wert>13445</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2016-11</mic:datum>
        <mic:wert>12980</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2016-12</mic:datum>
        <mic:wert>13153</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2017-01</mic:datum>
        <mic:wert>13139</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2017-02</mic:datum>
        <mic:wert>13330</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2017-03</mic:datum>
        <mic:wert>13049</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2017-04</mic:datum>
        <mic:wert>12813</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2017-05</mic:datum>
        <mic:wert>10873</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2017-06</mic:datum>
        <mic:wert>10867</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2017-07</mic:datum>
        <mic:wert>10424</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2017-08</mic:datum>
        <mic:wert>10000</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2017-09</mic:datum>
        <mic:wert>9787</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2017-10</mic:datum>
        <mic:wert>9428</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2017-11</mic:datum>
        <mic:wert>9403</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2017-12</mic:datum>
        <mic:wert>9520</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2018-01</mic:datum>
        <mic:wert>9509</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2018-02</mic:datum>
        <mic:wert>9545</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2018-03</mic:datum>
        <mic:wert>9519</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2018-04</mic:datum>
        <mic:wert>9652</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2018-05</mic:datum>
        <mic:wert>9939</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2018-06</mic:datum>
        <mic:wert>9981</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2018-07</mic:datum>
        <mic:wert>10362</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2018-08</mic:datum>
        <mic:wert>10684</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2018-09</mic:datum>
        <mic:wert>10783</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2018-10</mic:datum>
        <mic:wert>10970</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2018-11</mic:datum>
        <mic:wert>11200</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2018-12</mic:datum>
        <mic:wert>11136</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2019-01</mic:datum>
        <mic:wert>11210</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2019-02</mic:datum>
        <mic:wert>11272</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2019-03</mic:datum>
        <mic:wert>11055</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2019-04</mic:datum>
        <mic:wert>10953</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2019-05</mic:datum>
        <mic:wert>10797</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2019-06</mic:datum>
        <mic:wert>10671</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2019-07</mic:datum>
        <mic:wert>10692</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2019-08</mic:datum>
        <mic:wert>10606</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2019-09</mic:datum>
        <mic:wert>10653</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2019-10</mic:datum>
        <mic:wert>10554</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2019-11</mic:datum>
        <mic:wert>10517</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2019-12</mic:datum>
        <mic:wert>10534</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2020-01</mic:datum>
        <mic:wert>10572</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2020-02</mic:datum>
        <mic:wert>10432</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2020-03</mic:datum>
        <mic:wert>10436</mic:wert>
      </mic:zeitreihen-element>
    </mic:zeitreihe>
  </mic:nicht_wohnberechtigte_zuwanderer>
  <mic:summe_zuwanderer_wohnungslose>
    <mic:zeitreihe>
      <mic:zeitreihen-element>
        <mic:datum>2018-04</mic:datum>
        <mic:wert>29725</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2018-05</mic:datum>
        <mic:wert>30137</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2018-06</mic:datum>
        <mic:wert>30313</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2018-07</mic:datum>
        <mic:wert>30686</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2015-06</mic:datum>
        <mic:wert>13424</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2015-07</mic:datum>
        <mic:wert>13740</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2015-08</mic:datum>
        <mic:wert>13832</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2015-09</mic:datum>
        <mic:wert>14094</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2015-10</mic:datum>
        <mic:wert>14719</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2015-11</mic:datum>
        <mic:wert>15511</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2015-12</mic:datum>
        <mic:wert>16242</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2016-01</mic:datum>
        <mic:wert>16642</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2016-02</mic:datum>
        <mic:wert>17226</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2016-03</mic:datum>
        <mic:wert>18144</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2016-04</mic:datum>
        <mic:wert>18260</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2016-05</mic:datum>
        <mic:wert>19565</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2016-06</mic:datum>
        <mic:wert>20279</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2016-07</mic:datum>
        <mic:wert>21253</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2016-08</mic:datum>
        <mic:wert>22338</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2016-09</mic:datum>
        <mic:wert>22757</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2016-10</mic:datum>
        <mic:wert>22917</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2016-11</mic:datum>
        <mic:wert>23259</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2016-12</mic:datum>
        <mic:wert>23816</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2017-01</mic:datum>
        <mic:wert>24409</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2017-02</mic:datum>
        <mic:wert>25228</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2017-03</mic:datum>
        <mic:wert>26104</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2017-04</mic:datum>
        <mic:wert>26422</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2017-05</mic:datum>
        <mic:wert>26717</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2017-06</mic:datum>
        <mic:wert>27078</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2017-07</mic:datum>
        <mic:wert>27279</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2017-08</mic:datum>
        <mic:wert>27490</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2017-09</mic:datum>
        <mic:wert>28095</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2017-10</mic:datum>
        <mic:wert>28442</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2017-11</mic:datum>
        <mic:wert>28957</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2017-12</mic:datum>
        <mic:wert>29243</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2018-01</mic:datum>
        <mic:wert>29436</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2018-02</mic:datum>
        <mic:wert>29479</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2018-03</mic:datum>
        <mic:wert>29627</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2018-08</mic:datum>
        <mic:wert>30987</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2018-09</mic:datum>
        <mic:wert>31159</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2018-10</mic:datum>
        <mic:wert>31342</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2018-11</mic:datum>
        <mic:wert>31732</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2018-12</mic:datum>
        <mic:wert>31529</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2019-01</mic:datum>
        <mic:wert>31598</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2019-02</mic:datum>
        <mic:wert>31678</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2019-03</mic:datum>
        <mic:wert>31475</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2019-04</mic:datum>
        <mic:wert>31384</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2019-05</mic:datum>
        <mic:wert>31345</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2019-06</mic:datum>
        <mic:wert>31222</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2019-07</mic:datum>
        <mic:wert>31071</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2019-08</mic:datum>
        <mic:wert>30833</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2019-09</mic:datum>
        <mic:wert>30752</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2019-10</mic:datum>
        <mic:wert>30741</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2019-11</mic:datum>
        <mic:wert>30631</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2019-12</mic:datum>
        <mic:wert>30601</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2020-01</mic:datum>
        <mic:wert>30628</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2020-02</mic:datum>
        <mic:wert>30627</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2020-03</mic:datum>
        <mic:wert>30477</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2020-04</mic:datum>
        <mic:wert>30417</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2020-05</mic:datum>
        <mic:wert>30222</mic:wert>
      </mic:zeitreihen-element>
      <mic:zeitreihen-element>
        <mic:datum>2020-06</mic:datum>
        <mic:wert>30070</mic:wert>
      </mic:zeitreihen-element>
    </mic:zeitreihe>
  </mic:summe_zuwanderer_wohnungslose>
</mic:Zuwanderung>