CREATE TABLE LOCKS (
  ID INT NOT NULL GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  ACQUIRED TIMESTAMP NOT NULL,
  EXPIRES TIMESTAMP NOT NULL
);

CREATE TABLE LOCKED_FIDS (
  LOCK_ID INT REFERENCES LOCKS,
  FID VARCHAR(255) NOT NULL UNIQUE
);