
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Jan 13 09:57:11 CET 2010
//----------------------------------------------------

package org.deegree.commons.utils.templating;

/** CUP generated class containing symbol constants. */
public class TemplatingSymbols {
  /* terminals */
  public static final int MAP_VALUE_TOKEN = 12;
  public static final int GMLID_TOKEN = 13;
  public static final int TEXT_TOKEN = 2;
  public static final int TEMPLATE_DEFINITION_TOKEN = 3;
  public static final int MAP_CALL_TOKEN = 17;
  public static final int ODD_CALL_TOKEN = 6;
  public static final int NAME_TOKEN = 9;
  public static final int VALUE_TOKEN = 8;
  public static final int PROPERTY_TEMPLATE_CALL_TOKEN = 15;
  public static final int LINK_CALL_TOKEN = 10;
  public static final int EVEN_CALL_TOKEN = 5;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int FEATURE_TEMPLATE_CALL_TOKEN = 16;
  public static final int MAP_DEFINITION_TOKEN = 4;
  public static final int MAP_KEY_TOKEN = 11;
  public static final int INDEX_CALL_TOKEN = 7;
  public static final int END_DEFINITION_TOKEN = 14;
}

