

DROP TABLE area ;

DROP TABLE description;

DROP TABLE name ;

DROP TABLE version ;

DROP TABLE code ;

DROP VIEW identifiable_lookup;



DROP TABLE vertical_crs ;

DROP TABLE geocentric_crs ;

DROP TABLE projected_crs ;

DROP TABLE compound_crs ;




DROP TABLE lambert_conformal_conic ;

DROP TABLE stereographic_azimuthal ;

DROP TABLE transverse_mercator ;

DROP TABLE mercator ;

DROP TABLE stereographic_alternative ;

DROP TABLE lambert_azimuthal_equal_area ;

DROP TABLE custom_projection;

DROP TABLE projection_lookup;


DROP TABLE geographic_crs ;

DROP TABLE axis;

DROP TABLE crs_lookup;



DROP TABLE geodetic_datum ;

DROP TABLE prime_meridian ;

DROP TABLE ellipsoid ;

DROP TABLE vertical_datum ;



DROP TABLE helmert_transformation;

DROP TABLE least_square_transformation;

DROP TABLE polynomial_transformation;

DROP TABLE transformation_lookup;

