
ALTER TABLE ADDQP_Degree DROP CONSTRAINT FK_ADDQP_Degree;
ALTER TABLE ADDQP_Specification DROP CONSTRAINT FK_ADDQP_Specification;
ALTER TABLE ADDQP_Limitation DROP CONSTRAINT FK_ADDQP_Limitation;
ALTER TABLE ADDQP_Lineage DROP CONSTRAINT FK_ADDQP_Lineage;
ALTER TABLE ADDQP_AccessConstraint DROP CONSTRAINT FK_ADDQP_AccessConstraint;
ALTER TABLE ADDQP_OtherConstraint DROP CONSTRAINT FK_ADDQP_OtherConstraint;
ALTER TABLE ADDQP_Classification DROP CONSTRAINT FK_ADDQP_Classification;


DROP TABLE ADDQP_Degree;
DROP TABLE ADDQP_Specification;
DROP TABLE ADDQP_Limitation;
DROP TABLE ADDQP_Lineage;
DROP TABLE ADDQP_AccessConstraint;
DROP TABLE ADDQP_OtherConstraint;
DROP TABLE ADDQP_Classification;




	
