name: 'Close stale PRs'

# run on Wednesday mornings or manually
on:
  workflow_dispatch:
  schedule:
    - cron: '42 1 * * 3'

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/stale@v10
        with:
          # dry-run / no changes
          #debug-only: true
          # start with oldest
          ascending: true
          #
          enable-statistics: true
          # 
          stale-pr-label: "stuck"
          close-pr-label: "auto-closed"
          remove-pr-stale-when-updated: true
          #
          stale-pr-message: 'Thank you for your contribution. Unfortunately, this PR has been inactive for 90 days (see [PR stuck workflow](https://github.com/deegree/deegree3/wiki/Working-with-pull-requests#pull-requests-stuck-workflow)). Of course this is not the final word. The PR can become unstuck, for example, by reengaging in the discussion, answering open questions, rebasing, or adding new commits to this PR.'
          close-pr-message: 'Thank you for your contribution. Unfortunately, this PR got stuck (see [PR stuck workflow](https://github.com/deegree/deegree3/wiki/Working-with-pull-requests#pull-requests-stuck-workflow)). Of course this is not the final word. If you think that we did wrong, then reopening this pull request, continuing the conversation, and/or finishing any outstanding tasks will help to restart the decision-making process. Perhaps we can then, with additional information, merge the pull request. Anyhow, we do appreciate your commitment to open source and to deegree in particular.'
          #
          days-before-pr-stale: 90
          days-before-pr-close: 90
          # disabled for issues
          days-before-issue-stale: -1
          days-before-issue-close: -1
          #
          repo-token: ${{ secrets.GITHUB_TOKEN }}
