//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-792 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.02.19 at 03:44:10 PM MEZ 
//


package org.deegree.services.sos.configuration;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Offering" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="srsName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Datastore">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="Connection">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="Driver" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="Url" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="User" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="Password" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="Class" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="Table" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element ref="{http://www.deegree.org/services/sos}Column" maxOccurs="unbounded" minOccurs="0"/>
 *                             &lt;element ref="{http://www.deegree.org/services/sos}Option" maxOccurs="unbounded" minOccurs="0"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="Procedure" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="FeatureOfInterest">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;attribute ref="{http://www.w3.org/1999/xlink}href"/>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="Sensor">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;attribute ref="{http://www.w3.org/1999/xlink}href"/>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element ref="{http://www.deegree.org/services/sos}Column" maxOccurs="unbounded" minOccurs="0"/>
 *                             &lt;element ref="{http://www.deegree.org/services/sos}Option" maxOccurs="unbounded" minOccurs="0"/>
 *                           &lt;/sequence>
 *                           &lt;attribute ref="{http://www.w3.org/1999/xlink}href"/>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="Property" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element ref="{http://www.deegree.org/services/sos}Column" maxOccurs="unbounded" minOccurs="0"/>
 *                             &lt;element ref="{http://www.deegree.org/services/sos}Option" maxOccurs="unbounded" minOccurs="0"/>
 *                           &lt;/sequence>
 *                           &lt;attribute ref="{http://www.w3.org/1999/xlink}href"/>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "offering"
})
@XmlRootElement(name = "ServiceConfiguration")
public class ServiceConfiguration {

    @XmlElement(name = "Offering", required = true)
    protected List<ServiceConfiguration.Offering> offering;

    /**
     * Gets the value of the offering property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the offering property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOffering().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ServiceConfiguration.Offering }
     * 
     * 
     */
    public List<ServiceConfiguration.Offering> getOffering() {
        if (offering == null) {
            offering = new ArrayList<ServiceConfiguration.Offering>();
        }
        return this.offering;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="srsName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Datastore">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="Connection">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="Driver" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="Url" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="User" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="Password" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="Class" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="Table" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element ref="{http://www.deegree.org/services/sos}Column" maxOccurs="unbounded" minOccurs="0"/>
     *                   &lt;element ref="{http://www.deegree.org/services/sos}Option" maxOccurs="unbounded" minOccurs="0"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Procedure" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="FeatureOfInterest">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;attribute ref="{http://www.w3.org/1999/xlink}href"/>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="Sensor">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;attribute ref="{http://www.w3.org/1999/xlink}href"/>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element ref="{http://www.deegree.org/services/sos}Column" maxOccurs="unbounded" minOccurs="0"/>
     *                   &lt;element ref="{http://www.deegree.org/services/sos}Option" maxOccurs="unbounded" minOccurs="0"/>
     *                 &lt;/sequence>
     *                 &lt;attribute ref="{http://www.w3.org/1999/xlink}href"/>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="Property" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element ref="{http://www.deegree.org/services/sos}Column" maxOccurs="unbounded" minOccurs="0"/>
     *                   &lt;element ref="{http://www.deegree.org/services/sos}Option" maxOccurs="unbounded" minOccurs="0"/>
     *                 &lt;/sequence>
     *                 &lt;attribute ref="{http://www.w3.org/1999/xlink}href"/>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "name",
        "srsName",
        "datastore",
        "procedure",
        "property"
    })
    public static class Offering {

        @XmlElement(required = true)
        protected String name;
        @XmlElement(required = true)
        protected String srsName;
        @XmlElement(name = "Datastore", required = true)
        protected ServiceConfiguration.Offering.Datastore datastore;
        @XmlElement(name = "Procedure", required = true)
        protected List<ServiceConfiguration.Offering.Procedure> procedure;
        @XmlElement(name = "Property", required = true)
        protected List<ServiceConfiguration.Offering.Property> property;

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the srsName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSrsName() {
            return srsName;
        }

        /**
         * Sets the value of the srsName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSrsName(String value) {
            this.srsName = value;
        }

        /**
         * Gets the value of the datastore property.
         * 
         * @return
         *     possible object is
         *     {@link ServiceConfiguration.Offering.Datastore }
         *     
         */
        public ServiceConfiguration.Offering.Datastore getDatastore() {
            return datastore;
        }

        /**
         * Sets the value of the datastore property.
         * 
         * @param value
         *     allowed object is
         *     {@link ServiceConfiguration.Offering.Datastore }
         *     
         */
        public void setDatastore(ServiceConfiguration.Offering.Datastore value) {
            this.datastore = value;
        }

        /**
         * Gets the value of the procedure property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the procedure property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getProcedure().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ServiceConfiguration.Offering.Procedure }
         * 
         * 
         */
        public List<ServiceConfiguration.Offering.Procedure> getProcedure() {
            if (procedure == null) {
                procedure = new ArrayList<ServiceConfiguration.Offering.Procedure>();
            }
            return this.procedure;
        }

        /**
         * Gets the value of the property property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the property property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getProperty().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ServiceConfiguration.Offering.Property }
         * 
         * 
         */
        public List<ServiceConfiguration.Offering.Property> getProperty() {
            if (property == null) {
                property = new ArrayList<ServiceConfiguration.Offering.Property>();
            }
            return this.property;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="Connection">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="Driver" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="Url" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="User" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="Password" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="Class" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="Table" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element ref="{http://www.deegree.org/services/sos}Column" maxOccurs="unbounded" minOccurs="0"/>
         *         &lt;element ref="{http://www.deegree.org/services/sos}Option" maxOccurs="unbounded" minOccurs="0"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "connection",
            "clazz",
            "table",
            "column",
            "option"
        })
        public static class Datastore {

            @XmlElement(name = "Connection", required = true)
            protected ServiceConfiguration.Offering.Datastore.Connection connection;
            @XmlElement(name = "Class", required = true)
            protected String clazz;
            @XmlElement(name = "Table", required = true)
            protected String table;
            @XmlElement(name = "Column")
            protected List<Column> column;
            @XmlElement(name = "Option")
            protected List<Option> option;

            /**
             * Gets the value of the connection property.
             * 
             * @return
             *     possible object is
             *     {@link ServiceConfiguration.Offering.Datastore.Connection }
             *     
             */
            public ServiceConfiguration.Offering.Datastore.Connection getConnection() {
                return connection;
            }

            /**
             * Sets the value of the connection property.
             * 
             * @param value
             *     allowed object is
             *     {@link ServiceConfiguration.Offering.Datastore.Connection }
             *     
             */
            public void setConnection(ServiceConfiguration.Offering.Datastore.Connection value) {
                this.connection = value;
            }

            /**
             * Gets the value of the clazz property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getClazz() {
                return clazz;
            }

            /**
             * Sets the value of the clazz property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setClazz(String value) {
                this.clazz = value;
            }

            /**
             * Gets the value of the table property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTable() {
                return table;
            }

            /**
             * Sets the value of the table property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTable(String value) {
                this.table = value;
            }

            /**
             * Gets the value of the column property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the column property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getColumn().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Column }
             * 
             * 
             */
            public List<Column> getColumn() {
                if (column == null) {
                    column = new ArrayList<Column>();
                }
                return this.column;
            }

            /**
             * Gets the value of the option property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the option property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getOption().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Option }
             * 
             * 
             */
            public List<Option> getOption() {
                if (option == null) {
                    option = new ArrayList<Option>();
                }
                return this.option;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="Driver" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="Url" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="User" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="Password" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "driver",
                "url",
                "user",
                "password"
            })
            public static class Connection {

                @XmlElement(name = "Driver", required = true)
                protected String driver;
                @XmlElement(name = "Url", required = true)
                protected String url;
                @XmlElement(name = "User", required = true)
                protected String user;
                @XmlElement(name = "Password", required = true)
                protected String password;

                /**
                 * Gets the value of the driver property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getDriver() {
                    return driver;
                }

                /**
                 * Sets the value of the driver property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setDriver(String value) {
                    this.driver = value;
                }

                /**
                 * Gets the value of the url property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getUrl() {
                    return url;
                }

                /**
                 * Sets the value of the url property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setUrl(String value) {
                    this.url = value;
                }

                /**
                 * Gets the value of the user property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getUser() {
                    return user;
                }

                /**
                 * Sets the value of the user property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setUser(String value) {
                    this.user = value;
                }

                /**
                 * Gets the value of the password property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getPassword() {
                    return password;
                }

                /**
                 * Sets the value of the password property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setPassword(String value) {
                    this.password = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="FeatureOfInterest">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;attribute ref="{http://www.w3.org/1999/xlink}href"/>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="Sensor">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;attribute ref="{http://www.w3.org/1999/xlink}href"/>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element ref="{http://www.deegree.org/services/sos}Column" maxOccurs="unbounded" minOccurs="0"/>
         *         &lt;element ref="{http://www.deegree.org/services/sos}Option" maxOccurs="unbounded" minOccurs="0"/>
         *       &lt;/sequence>
         *       &lt;attribute ref="{http://www.w3.org/1999/xlink}href"/>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "featureOfInterest",
            "sensor",
            "column",
            "option"
        })
        public static class Procedure {

            @XmlElement(name = "FeatureOfInterest", required = true)
            protected ServiceConfiguration.Offering.Procedure.FeatureOfInterest featureOfInterest;
            @XmlElement(name = "Sensor", required = true)
            protected ServiceConfiguration.Offering.Procedure.Sensor sensor;
            @XmlElement(name = "Column")
            protected List<Column> column;
            @XmlElement(name = "Option")
            protected List<Option> option;
            @XmlAttribute(namespace = "http://www.w3.org/1999/xlink")
            @XmlSchemaType(name = "anyURI")
            protected String href;

            /**
             * Gets the value of the featureOfInterest property.
             * 
             * @return
             *     possible object is
             *     {@link ServiceConfiguration.Offering.Procedure.FeatureOfInterest }
             *     
             */
            public ServiceConfiguration.Offering.Procedure.FeatureOfInterest getFeatureOfInterest() {
                return featureOfInterest;
            }

            /**
             * Sets the value of the featureOfInterest property.
             * 
             * @param value
             *     allowed object is
             *     {@link ServiceConfiguration.Offering.Procedure.FeatureOfInterest }
             *     
             */
            public void setFeatureOfInterest(ServiceConfiguration.Offering.Procedure.FeatureOfInterest value) {
                this.featureOfInterest = value;
            }

            /**
             * Gets the value of the sensor property.
             * 
             * @return
             *     possible object is
             *     {@link ServiceConfiguration.Offering.Procedure.Sensor }
             *     
             */
            public ServiceConfiguration.Offering.Procedure.Sensor getSensor() {
                return sensor;
            }

            /**
             * Sets the value of the sensor property.
             * 
             * @param value
             *     allowed object is
             *     {@link ServiceConfiguration.Offering.Procedure.Sensor }
             *     
             */
            public void setSensor(ServiceConfiguration.Offering.Procedure.Sensor value) {
                this.sensor = value;
            }

            /**
             * Gets the value of the column property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the column property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getColumn().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Column }
             * 
             * 
             */
            public List<Column> getColumn() {
                if (column == null) {
                    column = new ArrayList<Column>();
                }
                return this.column;
            }

            /**
             * Gets the value of the option property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the option property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getOption().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Option }
             * 
             * 
             */
            public List<Option> getOption() {
                if (option == null) {
                    option = new ArrayList<Option>();
                }
                return this.option;
            }

            /**
             * Gets the value of the href property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getHref() {
                return href;
            }

            /**
             * Sets the value of the href property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setHref(String value) {
                this.href = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;attribute ref="{http://www.w3.org/1999/xlink}href"/>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class FeatureOfInterest {

                @XmlAttribute(namespace = "http://www.w3.org/1999/xlink")
                @XmlSchemaType(name = "anyURI")
                protected String href;

                /**
                 * Gets the value of the href property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getHref() {
                    return href;
                }

                /**
                 * Sets the value of the href property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setHref(String value) {
                    this.href = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;attribute ref="{http://www.w3.org/1999/xlink}href"/>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "")
            public static class Sensor {

                @XmlAttribute(namespace = "http://www.w3.org/1999/xlink")
                @XmlSchemaType(name = "anyURI")
                protected String href;

                /**
                 * Gets the value of the href property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getHref() {
                    return href;
                }

                /**
                 * Sets the value of the href property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setHref(String value) {
                    this.href = value;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element ref="{http://www.deegree.org/services/sos}Column" maxOccurs="unbounded" minOccurs="0"/>
         *         &lt;element ref="{http://www.deegree.org/services/sos}Option" maxOccurs="unbounded" minOccurs="0"/>
         *       &lt;/sequence>
         *       &lt;attribute ref="{http://www.w3.org/1999/xlink}href"/>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "column",
            "option"
        })
        public static class Property {

            @XmlElement(name = "Column")
            protected List<Column> column;
            @XmlElement(name = "Option")
            protected List<Option> option;
            @XmlAttribute(namespace = "http://www.w3.org/1999/xlink")
            @XmlSchemaType(name = "anyURI")
            protected String href;

            /**
             * Gets the value of the column property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the column property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getColumn().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Column }
             * 
             * 
             */
            public List<Column> getColumn() {
                if (column == null) {
                    column = new ArrayList<Column>();
                }
                return this.column;
            }

            /**
             * Gets the value of the option property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the option property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getOption().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Option }
             * 
             * 
             */
            public List<Option> getOption() {
                if (option == null) {
                    option = new ArrayList<Option>();
                }
                return this.option;
            }

            /**
             * Gets the value of the href property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getHref() {
                return href;
            }

            /**
             * Sets the value of the href property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setHref(String value) {
                this.href = value;
            }

        }

    }

}
