//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2008.07.01 at 03:49:29 PM CEST 
//


package org.deegree.model.geometry.configuration;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.deegree.model.geometry.configuration package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.deegree.model.geometry.configuration
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ModelConfiguration }
     * 
     */
    public ModelConfiguration createModelConfiguration() {
        return new ModelConfiguration();
    }

    /**
     * Create an instance of {@link SupportedSurfaceInterpolationType }
     * 
     */
    public SupportedSurfaceInterpolationType createSupportedSurfaceInterpolationType() {
        return new SupportedSurfaceInterpolationType();
    }

    /**
     * Create an instance of {@link SupportedGeometriesType }
     * 
     */
    public SupportedGeometriesType createSupportedGeometriesType() {
        return new SupportedGeometriesType();
    }

    /**
     * Create an instance of {@link InitParamType }
     * 
     */
    public InitParamType createInitParamType() {
        return new InitParamType();
    }

    /**
     * Create an instance of {@link GeometryFactoryType }
     * 
     */
    public GeometryFactoryType createGeometryFactoryType() {
        return new GeometryFactoryType();
    }

    /**
     * Create an instance of {@link GeometryFactoriesType }
     * 
     */
    public GeometryFactoriesType createGeometryFactoriesType() {
        return new GeometryFactoriesType();
    }

    /**
     * Create an instance of {@link SupportedCurveInterpolationType }
     * 
     */
    public SupportedCurveInterpolationType createSupportedCurveInterpolationType() {
        return new SupportedCurveInterpolationType();
    }

}
